### ISSUE TITLE
关于浏览记录功能

### ISSUE THREAD

**Issue by Sabermoon** [leoding86/webextension-pixiv-toolkit#10]
浏览记录是非常好的功能，但是我发现记录好像会遗漏一些，浏览之后根据“viewed_at”查看发现最新的记录时间居然相差十多个小时（已转换本地时间），最新的时间是1573442340而我最近的浏览时间则是2019/11/12 2:00:00左右。
我发现‘viewed_at’仅保存第一次浏览的时间，这使得使用它有一些困难，我希望它能保存最近的时间，或者拆分成两个如‘first_viewed’和‘last_viewed’等等。thanks。

**Comment by leoding86** [comment]
viewed_at确实是保存最后一次浏览时间。插件保存浏览记录是在插件被完全加载以后执行的，所以如果在插件被完全加载之前就跳转到别的作品，就会导致记录没有保存。我有时间会再具体测试一下。最近在计划重新设计浏览记录的ui。

**Comment by Sabermoon** [comment]
浏览的页面比较多，但是viewed_at的时间里没有一个是当天的，而且我看到有几个最近打开过但时间很老的记录，所以我觉得还是有点问题的。中间碰到了两次浏览器卡住和页面崩溃，不知道有没有关系，如果能提高下可靠性就很好了。

**Comment by leoding86** [comment]
我不能重现你说的问题，是否能够提供下运行的浏览器环境。

**Comment by Sabermoon** [comment]
Windwos insider 18900+ 和 Chrome78无痕模式，这个Chrome版本内存占用较高的时候会崩溃新开的标签页，有概率卡死和闪退。

**Comment by leoding86** [comment]
你可以用新版的浏览记录看下是否还有类似的问题，我确实复现不了这个问题，如果有还是有问题可以reopen。
