### ISSUE TITLE
在Firefox下面FANBOX没有下载按钮

### ISSUE THREAD

**Issue by Godoword** [leoding86/webextension-pixiv-toolkit#100]
pixiv是正常的，FANBOX下没有显示下载按钮。

Firefox 87.0

**Comment by leoding86** [comment]
是的，因为FireFox是老版本的，有一段时间没有维护了。我会找个时间传一份新的。

**Comment by msc-scrim** [comment]
@leoding86 any progress on this?

**Comment by leoding86** [comment]
I'll release a new version in a few days.
