### ISSUE TITLE
Generate WEBM on Firefox always stuck on 100% Generated - Works in Edge Browser

### ISSUE THREAD

**Issue by stargatexg1** [leoding86/webextension-pixiv-toolkit#101]
**Describe the bug**

Generate WEBM on Firefox always stuck on 100% Generated. works fine in edge browser but not in firefox. it's been over 6 moths maybe a year and still not fixed.

**Expected behavior**
i expect it to ask me where to save the file?

**Example work from Pixiv**
If applicable, add work url to help me to reproduce the problem.

**Screenshots**

**Browser and Version (please complete the following information):**
 - e.g. chrome, edge，firefox

FireFox Version 87.0

**Settings of extension**
You can export the settings of extension in setting page.

[pixiv_toolkit_settings-1617973833989.zip](https://github.com/leoding86/webextension-pixiv-toolkit/files/6285932/pixiv_toolkit_settings-1617973833989.zip)

**Additional context**

**Comment by leoding86** [comment]
It's a bug related to FireFox. So I can't do anything about it. You can check bug information [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1559743)

**Comment by leoding86** [comment]
duplicated #4
