### ISSUE TITLE
FANBOX打包下载的图片呈现乱序和倒序

### ISSUE THREAD

**Issue by Godoword** [leoding86/webextension-pixiv-toolkit#102]
如果一篇文章里只有jpeg格式，排序正常；
如果jpeg+png混杂，则打包下载的图片为乱序；
如果全部为png格式，则图片编号为倒序。

**Comment by leoding86** [comment]
能否提供一个免费的作品链接我测试一下？

**Comment by Godoword** [comment]
> 
> 
> 能否提供一个免费的作品链接我测试一下？

示例一：
https://www.fanbox.cc/@kedamaa/posts/933416
全部为png格式，打包下载得到的图片命名顺序是反过来的。

示例二：
https://www.fanbox.cc/@kedamaa/posts/1986033
该例中第一张图片为png格式，第二张图片为jpeg格式。打包下载得到的是倒序命名。

但是示例二只有两张图片，FANBOX我找了半天实在没找到多个图片里同时含有png和jpeg的免费作品。所以先前反馈的乱序不太好复现。

PS：尚不知其他图片格式有没有问题。使用的扩展为商店最新版。

**Comment by leoding86** [comment]
已经在[https://github.com/leoding86/webextension-pixiv-toolkit/commit/4bdb8e3ff408ecf7c306c7b0b1f20506bf7b3edf](https://github.com/leoding86/webextension-pixiv-toolkit/commit/4bdb8e3ff408ecf7c306c7b0b1f20506bf7b3edf)修复了，最近会发一个版本。
