### ISSUE TITLE
每个图片下载后名字都有个0，建议在不设置重命名格式再加0。

### ISSUE THREAD

**Issue by awawawawawawa** [leoding86/webextension-pixiv-toolkit#103]
**描述错误**
清楚简明地描述错误是什么。

**预期行为**
对你期望发生的事情的简洁明了的描述。

**示例作品**
如果可以，请提供发生错误的作品链接。

**截图**
如果可以，请添加屏幕截图以帮助解释你的问题。

**浏览器以及版本（请填写以下信息）：**
  -例如 Chrome，Edge，Firefox

**插件设置**
你可以在设置页面导出插件设置。

**其他内容**
其他可用的信息。

**Comment by leoding86** [comment]
如果是下载的漫画或者图集的话，一定会包含页码。如果只有一张的时候会根据配置默认设置为0或1，这个目前没有更新逻辑的计划。

**Comment by leoding86** [comment]
你下载的是只有一张图片的图集有这个问题？还是下载有多张图的图集有这个问题？

**Comment by awawawawawawa** [comment]
一张和多个都是这样



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月16日(星期三) 下午5:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [leoding86/webextension-pixiv-toolkit] 每个图片下载后名字都有个0，建议在不设置重命名格式再加0。 (#103)





 
你下载的是只有一张图片的图集有这个问题？还是下载有多张图的图集有这个问题？

**Comment by leoding86** [comment]
麻烦提供一下你的重命名配置以及示例作品，有时间的时候我会看下。

**Comment by awawawawawawa** [comment]
这就是我的，每个图片结尾都带个0，而且没有间隔




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月16日(星期三) 晚上7:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [leoding86/webextension-pixiv-toolkit] 每个图片下载后名字都有个0，建议在不设置重命名格式再加0。 (#103)





 
麻烦提供一下你的重命名配置以及示例作品，有时间的时候我会看下。

**Comment by leoding86** [comment]
@awawawawawawa 你是不是将截图附在邮件里面回复的？这个在issues里面是看不到截图的。建议你直接将重命名配置通过文本粘贴进来。
