### ISSUE TITLE
多个图片下载没法制定下载，希望能指定选择下载哪张和全下的选项

### ISSUE THREAD

**Issue by awawawawawawa** [leoding86/webextension-pixiv-toolkit#104]
**描述错误**
清楚简明地描述错误是什么。

**预期行为**
对你期望发生的事情的简洁明了的描述。

**示例作品**
如果可以，请提供发生错误的作品链接。

**截图**
如果可以，请添加屏幕截图以帮助解释你的问题。

**浏览器以及版本（请填写以下信息）：**
  -例如 Chrome，Edge，Firefox

**插件设置**
你可以在设置页面导出插件设置。

**其他内容**
其他可用的信息。

**Comment by leoding86** [comment]
这个并不好实现，我先记下来，有时间想想。
