### ISSUE TITLE
火狐浏览器插件无法导入历史记录和恢复历史记录

### ISSUE THREAD

**Issue by histion** [leoding86/webextension-pixiv-toolkit#106]
**描述错误**
  pixiv toolkit版本v4.2.1-2020063020  火狐中无法导入记录和恢复记录，一直卡在0，但可以正常导出、

**截图**
![QQ截图20210505134513](https://user-images.githubusercontent.com/65994410/117101259-5c533500-ada8-11eb-8bc2-64f2f39b7cd3.png)

**浏览器以及版本（请填写以下信息）：**
火狐版本，88.0 (64 位）

**Comment by leoding86** [comment]
有时间的时候看一下吧，实在是没有精力维护两个版本。
