### ISSUE TITLE
小说epub版本下载缺页

### ISSUE THREAD

**Issue by ggpjar** [leoding86/webextension-pixiv-toolkit#107]
作品epub格式下载打开后，报内容错误。大部分页面缺失。
id=15339605
Chrome 86.0.4240.198
P站工具箱 v4.7.1
![685](https://user-images.githubusercontent.com/85214583/120432409-7898c080-c3ac-11eb-85fc-99f03496a028.jpg)

**Comment by leoding86** [comment]
@ggpjar 是所有的都缺页还是特定的？最好能提供一个实例作品的链接。

**Comment by ggpjar** [comment]
@leoding86 
https://www.pixiv.net/novel/show.php?id=15339605
前几页不缺，后面都缺。缺的超过4/5
上为作品链接。其他作品没有发现类似情况。

**Comment by leoding86** [comment]
@ggpjar 我可以正常下载并且使用Calibre正常打开。用你能否换一个软件试一试能不能看下是否正常？
