### ISSUE TITLE
Fanbox downloads images out of order

### ISSUE THREAD

**Issue by 501stRookie** [leoding86/webextension-pixiv-toolkit#108]
**Describe the bug**
When downloading images off Pixiv Fanbox, sometimes the images are downloaded out of order. Ie, the names/order they are in when downloaded do not match the order they were in in the post.

**Expected behavior**
I expected the images to be downloaded in the correct order.

**Example work from Pixiv**
I am currently unable to find an example that is not behind a paywall.
_**NSFW _WARNING**_
https://yoshiragi.fanbox.cc/posts/788488

**Screenshots**
_**NSFW _WARNING**_
https://i.imgur.com/VlsG0Gj.mp4
https://i.imgur.com/TP7RuUn.png
https://i.imgur.com/Hx6DnE7.png

**Browser and Version (please complete the following information):**
Google Chrome Version 91.0.4472.77

**Settings of extension**
You can export the settings of extension in setting page.

[pixiv_toolkit_settings-1623086970820.zip](https://github.com/leoding86/webextension-pixiv-toolkit/files/6610952/pixiv_toolkit_settings-1623086970820.zip)

**Comment by 501stRookie** [comment]
I found a free link that downloads out of order.

_**NSFW WARNING**_
https://ico.fanbox.cc/posts/617876

**Comment by leoding86** [comment]
I'll investigate it later.

**Comment by leoding86** [comment]
I'll release a new version in a few days.
