### ISSUE TITLE
Image numbering

### ISSUE THREAD

**Issue by scampadversary** [leoding86/webextension-pixiv-toolkit#109]
Please change the tag {pageNum} to put a 0 before the first 10 images. Like this: 00, 01, 02, 03, 04, 05, 06, 07, 08, 09 (and then 10). 

Right now sorting by order is impossible after 9 because 10 goes directly after 1 rather than after 9. 20 goes after 2 rather than 19, and so on.

Please!

**Comment by leoding86** [comment]
New version will be released in few days.
