### ISSUE TITLE
Illegal characters for filenames should be filtered

### ISSUE THREAD

**Issue by ian-coog** [leoding86/webextension-pixiv-toolkit#11]
If a illustration title or author name contain illegal characters like 
? * < > | : "
the filename can't be saved. The illegal characters should be filtered/replaced with _ (underline) or at least give an option to automatically filter them before creating the filename.

The forbidden printable ASCII characters are:

Linux/Unix:

* / (forward slash) (you can use if you escape with \\/ )

Windows:

* < (less than)
* \> (greater than)
* : (colon - sometimes works, but is actually NTFS Alternate Data Streams)
* " (double quote)
* / (forward slash)
* \ (backslash)
* | (vertical bar or pipe)
* ? (question mark)
* \* (asterisk)

**Comment by leoding86** [comment]
I didn't notice the that. I'll fix when I have time.

**Comment by ian-coog** [comment]
for some reason it doesn't work here because of forward slash, I think (note, some are NSFW)
https://www.pixiv.net/en/artworks/76488684
title: 18/11~19/08のR18差分まとめ
while it worked ok with
https://www.pixiv.net/en/artworks/77859652
https://www.pixiv.net/en/artworks/75503126

**Comment by leoding86** [comment]
I can repo it. Will fix it later.

**Comment by leoding86** [comment]
Fixed in version 3.4.2. Chrome treat the filename which include ~ is a invalid filename. Sorry for the late fix because I'm working on the new standalone Pixiv download app these days.

**Comment by ian-coog** [comment]
3.4.2 works perfectly, thank you
