### ISSUE TITLE
Fanbox 图片下载顺序混乱，编码错误

### ISSUE THREAD

**Issue by wanzzhehe** [leoding86/webextension-pixiv-toolkit#110]
**Describe the bug**

图像下标（页码）没有从1开始，且前四张丢失。

**Expected behavior**

**Example work from Pixiv**

https://ginklaga.fanbox.cc/posts/2394946
这个是个fanbox页……我现在不知道有没有什么多页的免费公开在fanbox里面
（如果需要，我可以提供页面的HTML（看不了图））

**Screenshots**

![image](https://user-images.githubusercontent.com/26498686/123016153-8dd99b80-d3fc-11eb-94c7-ecf654fa737e.png)

**Browser and Version (please complete the following information):**
Edge 91.0.864.54

**Settings of extension**

{"MangaPageNumberStartWithOne":false,"alwaysPack":true,"animationJsonFormat":1,"askDownloadSavedWork":true,"autoActivateDownloadPanel":true,"displayWorkTypeLabel":true,"downloadRelativeLocation":null,"downloadSaveAs":true,"downloadTasksWhenDownloadingImages":4,"enableExtTakeOverDownloads":false,"enableExtend":false,"enableExtension":true,"enablePackUgoiraFramesInfo":true,"enablePtkSearch":true,"enableSaveDownloadHistory":1,"enableSaveVisitHistory":true,"enableWhenUnderSeconds":1,"extendDuration":3,"featureKnown":false,"guideShowed":false,"illustrationImageRenameFormat":"{title}-{pageNum}","illustrationKeepPageNumber":false,"illustrationPageNumberStartWithOne":true,"illustrationRelativeLocation":"","illustrationRenameFormat":"{title}","importantNoticeDisplayed":false,"language":"zh_CN","mangaImageRenameFormat":"{title}-{pageNum}","mangaPageNumberStartWithOne":true,"mangaPagesInChunk":99,"mangaRelativeLocation":"","mangaRenameFormat":"{title}","maxDownloadRecords":10000,"maxHistoryItems":10000,"notSaveNSFWWorkInHistory":false,"novelIncludeDescription":true,"novelRelativeLocation":"","novelRenameFormat":"{title}","statIllustDownloaded":0,"statMangaDownloaded":1,"statNovelDownloaded":0,"statUgoiraDownloaded":0,"ugoiraQuanlity":1,"ugoiraRelativeLocation":"","ugoiraRenameFormat":"{title}","version":"4.7.1","visitHistoryType":"list","workCoverSize":3}

**Additional context**

**Comment by wanzzhehe** [comment]
啊，抱歉，标题忘改了，只有缺页的问题。

**Comment by leoding86** [comment]
缺页的问题还没有人反应过。主要是有些页面我看不了，没法调试。

你这个页面里的资源都是图片吗？会不会有动图和图片混排的情况？

**Comment by wanzzhehe** [comment]
> 缺页的问题还没有人反应过。主要是有些页面我看不了，没法调试。
> 
> 你这个页面里的资源都是图片吗？会不会有动图和图片混排的情况？

全都是图片

**Comment by leoding86** [comment]
那理论上不应该会缺页，你会使用浏览器调试模式吗？如果能看到一个xhr请求的数据对调试插件会有些帮助。

**Comment by wanzzhehe** [comment]
> 那理论上不应该会缺页，你会使用浏览器调试模式吗？如果能看到一个xhr请求的数据对调试插件会有些帮助。

嘶……我等到现在又试了一下，发现能下载完了

可能是网络问题

**Comment by wanzzhehe** [comment]
> 那理论上不应该会缺页，你会使用浏览器调试模式吗？如果能看到一个xhr请求的数据对调试插件会有些帮助。

其实，我突然想到，可以对这个插件添加一下下载完成后检查是否全部下载完的功能。如果没有下载完，重新下载，失败一定次数后报错什么的。

**Comment by leoding86** [comment]
是应该有重试的功能，不过一直没有去处理。最近比较忙，忙完了这段时间一起处理下。
