### ISSUE TITLE
multi-image packed download naming

### ISSUE THREAD

**Issue by tallos** [leoding86/webextension-pixiv-toolkit#114]
Is there currently a way for the packed downloads to be named with a range of images contained within?
ex: a set with 9 images would be {id}_p0-8
ive tried {id}_p0#{pageNum}# but it is incredibly inconsistent, sometimes it will give me the correct p0_8, but with other times it doesn't work and will give an incorrect p0_0 or p0_(random image number within the set)

example:
https://www.pixiv.net/en/artworks/83251649 with the following rename {id}_p0#{pageNum}# gives 83251649_p0_0 but the gallery should be 83251649_p0_1
 https://www.pixiv.net/en/artworks/89933727 using the same rename gives 89933727_p0_5, when it should give 89933727_p0_6 because the set is 7 images.

**Comment by leoding86** [comment]
What's the expected filename(s) you want to get? I'll try to give you a rename setting to get that name.

**Comment by tallos** [comment]
id#_p0-p(lastPageNum) is the desired naming scheme, compatible with the page number 0 start numbering scheme.

**Comment by leoding86** [comment]
So you want to the zip filename include start page number and last page number at same time, and prefix a `p` to the two page numbers. If I understand it right, you can't do that at this moment.

The `pageNum` meta shouldn't be included in `Illustration Rename` setting, or the renaming feature will work in unexpected way.

But the feature you want can be done, I'll put it on todo list.

**Comment by tallos** [comment]
Yep that about sums it up. This will allow me to seamlessly merge any new zip downloads via toolkit to all my pre-toolkit download zips i had made.
Thank you for the hard work and quick replies.
