### ISSUE TITLE
Webm are not playable

### ISSUE THREAD

**Issue by ian-coog** [leoding86/webextension-pixiv-toolkit#116]
Generated webm don't play in any player (vlc, irfanview, windows media player) from this update v4.10.0

https://www.pixiv.net/en/artworks/91370773
but actually any ugoira saved as webm

they work as gif or apng

**Comment by SomeRandomGithubUsers** [comment]
Can confirm it on the latest Chrome version (92.0.4515.107).
Downgrading to Chrome version 91.0.4472.106 fixed it for me. Should also work with Chrome version 91.0.4472.106.
Using v4.10.0

**Comment by ian-coog** [comment]
> Can confirm it on the latest Chrome version (92.0.4515.107).

Oh nicely spotted, I have infact just updated to Vivaldi 4.1.2358.15 which is based on Chrome 92.0.4515.76
So it's not exactly the extension fault, it's a bug in Chromium

**Comment by leoding86** [comment]
Since Chrome version 92, there are some new policies released. I'll investigate it when I have more time.

**Comment by leoding86** [comment]
I think the library whammy.js used for converting images to webm is broken in Chrome 92 and above, and it won't work in any browsers use Chromium 92 and above as the kernal.

I need some time to find a replacement.

**Comment by SomeRandomGithubUsers** [comment]
Someone at whammy.js github page found a solution for it.
I edited the whammy.js file from the pixiv toolkit 5.0 and recompiled it and webm works again.
Link to fix: https://github.com/antimatter15/whammy/issues/70#issuecomment-890312941

Someone else found a better fix, but haven't tested it yet. 
Link to better fix, but untested: https://github.com/antimatter15/whammy/issues/70#issuecomment-890317018

**Comment by Racelgard** [comment]
> Someone at whammy.js github page found a solution for it.
> I edited the whammy.js file from the pixiv toolkit 5.0 and recompiled it and webm works again.
> Link to fix: [antimatter15/whammy#70 (comment)](https://github.com/antimatter15/whammy/issues/70#issuecomment-890312941)
> 
> Someone else found a better fix, but haven't tested it yet.
> Link to better fix, but untested: [antimatter15/whammy#70 (comment)](https://github.com/antimatter15/whammy/issues/70#issuecomment-890317018)

Is it hard to do that?, I dont rly know about coding, if you could give me some light  in the issue would be greatly aprecciated.
