### ISSUE TITLE
Select & DL display

### ISSUE THREAD

**Issue by scampadversary** [leoding86/webextension-pixiv-toolkit#118]
When I click Select & DL, the selection box is zoomed in on some but not all images with no way to scroll from the first image to the last. I had to zoom my browser way out to see every image in the post. I also had to zoom out to see the Download button. Could you please make the selection panel more navigable?

**Comment by leoding86** [comment]
Any example? A url would be better.

**Comment by scampadversary** [comment]
Say I want to Select & DL this artwork: https://www.pixiv.net/en/artworks/91299618

Here's an imgur album with captions showing the issue: https://imgur.com/a/CZHfPQc

**Comment by scampadversary** [comment]
Hi there, I noticed I'm still having this problem. Would you mind explaining why you closed the issue?

**Comment by leoding86** [comment]
@scampadversary I fixed the issue in source code, but the Chrome version is still in review state, it need some time to complete publish.
<img src="https://i.imgur.com/GCZqNyi.png">
