### ISSUE TITLE
Downloaded images don't follow standard pixiv numbering

### ISSUE THREAD

**Issue by Tamren** [leoding86/webextension-pixiv-toolkit#12]
The download feature uses a different numbering scheme that causes problems with sorting. For instance on pixiv if a gallery number is "5544" the individual images will be named 5544_p1, 5544_p2 etc when downloaded directly. If I use this addon to download the same images as a zip and tell it to add the ID and NUMBER to the images it will name them 55441, 55442 instead without the underscore. This causes problems when sorting because image numbers 0-9 will be displayed on a different row from images 10+ because the extra digit added to the end makes it a larger number.

So it would nice if the toolkit followed the standard pixiv naming format of ####_p#. Ideally it would do this by default so that the names of downloaded images match whether you do it manually or through the toolkit.

**Comment by leoding86** [comment]
As what I understand, use {id}_p{pageNum} rename rule will do the job as you want.

**Comment by Tamren** [comment]
Oh that's great. I didn't realize I could manually type into the ruleset, I thought that was a just an output display for the existing buttons. Thanks for the tip.

Now that I know how it works it's a non issue, though I would still suggest making {id}_p{pageNum} the default setting.
