### ISSUE TITLE
WEBM Generation Error

### ISSUE THREAD

**Issue by Racelgard** [leoding86/webextension-pixiv-toolkit#120]
I tried with different browsers and other pcs, but whenever I create a WEBN video its always just a black screen, please confirm if its an issue of the app

**Comment by SomeRandomGithubUsers** [comment]
It's a known issue: https://github.com/leoding86/webextension-pixiv-toolkit/issues/116
There is also a solution to fix the problem linked in the thread.

We just need to wait for the developer to implement those fixes or if you can't wait you can do the fix yourself and recompile it.
If thats not possible either use a non chromium based browser or not the latest chromium version.

**Comment by Racelgard** [comment]
> It's a known issue: #116
> There is also a solution to fix the problem linked in the thread.
> 
> We just need to wait for the developer to implement those fixes or if you can't wait you can do the fix yourself and recompile it.
> If thats not possible either use a non chromium based browser or not the latest chromium version.

I would love to try, but im afaid im not be able to, since I know nothing about coding.
