### ISSUE TITLE
Return the old setting for zipping only multiple images | Missed images

### ISSUE THREAD

**Issue by TestPolygon** [leoding86/webextension-pixiv-toolkit#124]
Return the old setting for zipping only multiple images.

---

I don't like to extract every single image from an archive. It makes no sense to zip them if there is only 1 image.

But with the new update if I choose the downloading without zipping, then it leads to data loosing in cases when images over 10. **Some image will be not downloaded!** Because the extension saves them at one moment.

**Chromium does not allow to save _correctly_ more than 10 images in a second (per a tab). (approximately)**

So if I download 24 images, I can expect that only 10 images will be downloaded. The downloading of the other 14 ones is depends only on luck.

Just try to save 24 (for example) images. You will download 10-24 (24 if you are very lucky) images.

**Comment by TestPolygon** [comment]
So you should use a semaphore that will limit the downloading count of images within one second within one tab.
8-10 images per a second.

**Comment by tallos** [comment]
also experiencing this, tried to download a 32 image set without zip and had 2/3rds of them not download. I really like the feature of not having them zipped, but it needs a limiter so it does not do them all at once.

**Comment by leoding86** [comment]
Zipping files will not work properly while downloading manga. The issue is confirmed, will fixed it in the next version.
