### ISSUE TITLE
Weird behavior when downloading image/s without zipping

### ISSUE THREAD

**Issue by sleektako** [leoding86/webextension-pixiv-toolkit#126]
**Describe the bug**
Whenever I try to download a single file or a bunch of files without zipping them, it always create a folder with its artwork filename and the more annoying thing is it will ignore my specified download location, for example downloads/pixiv, and instead create a folder in downloads UNLESS I zipped it THEN it will put the file in the right location.

Then I thought, maybe let's just type the specified location the "Illustration" settings, so I did... It fixed the wrong location part when downloading a file without zipping them but it only create empty folder with the artwork's name.

**Example work from Pixiv**
Every single or multiple page artwork.

**Browser and Version (please complete the following information):**
 - Vivaldi 4.1.2369.16 (Stable channel) (64-bit)

**Settings of extension**
{"MangaPageNumberStartWithOne":false,"alwaysPack":false,"animationJsonFormat":1,"askDownloadSavedWork":true,"autoActivateDownloadPanel":true,"displayWorkTypeLabel":true,"downloadPackFiles":false,"downloadRelativeLocation":"Pixiv/","downloadSaveAs":false,"downloadTasksWhenDownloadingImages":3,"enableExtTakeOverDownloads":true,"enableExtend":true,"enableExtension":true,"enablePackUgoiraFramesInfo":true,"enablePtkSearch":true,"enableSaveDownloadHistory":1,"enableSaveVisitHistory":true,"enableWhenUnderSeconds":1,"extendDuration":3,"featureKnown":false,"guideShowed":true,"illustrationImageRenameFormat":"{id}{title}{author}{pageNum}","illustrationKeepPageNumber":false,"illustrationPageNumberLength":0,"illustrationPageNumberStartWithOne":false,"illustrationRelativeLocation":"","illustrationRenameFormat":"{id}{title}{author}","importantNoticeDisplayed":true,"language":"default","mangaImageRenameFormat":"{id}{title}{author}{pageNum}","mangaPageNumberLength":0,"mangaPagesInChunk":99,"mangaRelativeLocation":"","mangaRenameFormat":"{id}{title}{author}","maxDownloadRecords":10000,"maxHistoryItems":10000,"notSaveNSFWWorkInHistory":false,"novelIncludeDescription":true,"novelRelativeLocation":"","novelRenameFormat":"{id}{title}{author}","showUpdateChangeLog":true,"statIllustDownloaded":181,"statMangaDownloaded":1,"statNovelDownloaded":0,"statUgoiraDownloaded":42,"ugoiraConvertTool":"default","ugoiraCustomFFmpegCommand":"","ugoiraQuanlity":5,"ugoiraRelativeLocation":"","ugoiraRenameFormat":"{id}{title}{author}","version":"5.0.2","visitHistoryType":"list","workCoverSize":1}

**Additional context**
Danke.

**Comment by leoding86** [comment]
Issue confirmed. Will be fixed in the next version.
