### ISSUE TITLE
Saving multi-page manga works downloads files individually

### ISSUE THREAD

**Issue by hal0thane** [leoding86/webextension-pixiv-toolkit#127]
**Describe the bug**
With version 5.0.2 and probably 5.0.0 as well based on the changelog, downloading mangas is broken. Now, instead of creating a zip file with all the pages of the manga, it creates a subdirectory with the name of what would be the zip file, then downloads each page one at a time into that directory. For a manga of 100 pages, that means 100 downloads.

**Expected behavior**
Return to previous behavior: zip the pages into a single file and download only the zip file.

**Example work from Pixiv**
https://www.pixiv.net/en/artworks/92016927 -- Selected the top ranked manga today. Any Pixiv manga will reproduce the problem.

**Screenshots**
Not relevant

**Browser and Version (please complete the following information):**
Chrome Version 93.0.4577.25 (Official Build) beta (x86_64) on Mac OS

**Settings of extension**
```js
1 | {"MangaPageNumberStartWithOne":false,"alwaysPack":false,"animationJsonFormat":1,"askDownloadSavedWork":true,"autoActivateDownloadPanel":true,"displayWorkTypeLabel":true,"downloadPackFiles":true,"downloadRelativeLocation":"","downloadSaveAs":false,"downloadTasksWhenDownloadingImages":2,"enableExtTakeOverDownloads":true,"enableExtend":false,"enableExtension":true,"enablePackUgoiraFramesInfo":true,"enablePtkSearch":true,"enableSaveDownloadHistory":1,"enableSaveVisitHistory":true,"enableWhenUnderSeconds":1,"extendDuration":3,"featureKnown":true,"guideShowed":true,"illustrationImageRenameFormat":"{authorId}-{id}_p{pageNum}","illustrationKeepPageNumber":true,"illustrationPageNumberLength":3,"illustrationPageNumberStartWithOne":false,"illustrationRelativeLocation":"px-{authorId}/","illustrationRenameFormat":"{authorId}-{id}_p","importantNoticeDisplayed":true,"language":"default","mangaImageRenameFormat":"{authorId}-{id}_p{pageNum}","mangaPageNumberLength":3,"mangaPagesInChunk":900,"mangaRelativeLocation":"px-{authorId}/","mangaRenameFormat":"{authorId}-{id}_m","maxDownloadRecords":10000,"maxHistoryItems":10000,"notSaveNSFWWorkInHistory":false,"novelIncludeDescription":false,"novelRelativeLocation":"","novelRenameFormat":"","showUpdateChangeLog":true,"statIllustDownloaded":42090,"statMangaDownloaded":2135,"statNovelDownloaded":0,"statUgoiraDownloaded":759,"ugoiraConvertTool":"default","ugoiraCustomFFmpegCommand":"","ugoiraQuanlity":10,"ugoiraRelativeLocation":"ugoira/px-{authorId}/","ugoiraRenameFormat":"{authorId}-{id}_p000","version":"5.0.2","visitHistoryType":"list","workCoverSize":2}
-- | --
```

**Additional context**
Note that the behavior is the same whether `alwaysPack` is `true` or `false`. Multi-page images ("logs") seem to download correctly as a single zip file. Only works considered manga are downloading incorrectly.

At least one other user has encountered the bug, based on comments at the Chrome Web Store. I have notified that user to post here as well.

**Comment by leoding86** [comment]
related #125
