### ISSUE TITLE
当只有一张图片时不进行打包 设置失效

### ISSUE THREAD

**Issue by MrTrueChina** [leoding86/webextension-pixiv-toolkit#128]
**描述错误**
在我保存仅有一张图片的作品时依然进行了打包。
我已经尝试过开启和关闭设置中的 [绘画->始终打包]，都会对单图作品进行打包。
我也尝试了开关 [下载->打包文件]，但关闭这个设置会导致多图下载不打包。

**预期行为**
我期望当我保存仅有一张图片的作品时不进行打包，在下载多张图片的作品时进行打包

**示例作品**
https://www.pixiv.net/artworks/88310099
https://www.pixiv.net/artworks/89434682
https://www.pixiv.net/artworks/89819855

**截图**
![QQ图片20210818180535](https://user-images.githubusercontent.com/34619569/129879922-098279d8-73a9-4c6a-845d-5c494b63a5ca.png)

**浏览器以及版本（请填写以下信息）：**
Chrome 92.0.4515.159 (x64)

**插件设置**
[pixiv_toolkit_settings-1629281456558.txt](https://github.com/leoding86/webextension-pixiv-toolkit/files/7006367/pixiv_toolkit_settings-1629281456558.txt)

**其他内容**
这个问题大约在 2021.8.16 发现
Chrome 商店显示上次更新是 2021.8.15
我可以查到的最近一次正确使用是在 2021.8.14 14:06:39 (UTF+8)

**Comment by leoding86** [comment]
5.0.2 版本有很多问题。 我已经将 5.0.3 版本提交到 Chrome Store 并等待审核。 您可以在发布页面下载此版本并手动更新。
