### ISSUE TITLE
当图片过多时不进行打包 设置失效

### ISSUE THREAD

**Issue by 330421370** [leoding86/webextension-pixiv-toolkit#129]
**描述错误**
清楚简明地描述错误是什么。
打包文件的设置失效
**预期行为**
对你期望发生的事情的简洁明了的描述。
希望扩展程序会将下载的图像打包为 zip 文件并下载
**示例作品**
如果可以，请提供发生错误的作品链接。
所有作品
**截图**
如果可以，请添加屏幕截图以帮助解释你的问题。
![微信截图_20210819042005](https://user-images.githubusercontent.com/89162797/129966724-eb5a2aa7-5dfd-4d1b-96c1-c9ca254eecbc.png)

**浏览器以及版本（请填写以下信息）：**
  -例如 Chrome，Edge，Firefox
Cent Browser4.3.9.248（正式版本） （32 位） (Chromium 86.0.4240.198)

你可以在设置页面导出插件设置。
[pixiv_toolkit_settings-1629318433706.txt](https://github.com/leoding86/webextension-pixiv-toolkit/files/7010025/pixiv_toolkit_settings-1629318433706.txt)

**其他内容**
其他可用的信息。

**Comment by leoding86** [comment]
版本 5.0.2 目前有很多问题。 我已经将 5.0.3 版本提交到 Chrome Store 并等待审核。 您可以在发布页面下载此版本并手动更新。
