### ISSUE TITLE
null in front of filename

### ISSUE THREAD

**Issue by takase1121** [leoding86/webextension-pixiv-toolkit#13]
![image](https://user-images.githubusercontent.com/20792268/69707875-84f7e980-1135-11ea-8fbc-c37e2b15cf6e.png)

and this is my setting:
![image](https://user-images.githubusercontent.com/20792268/69707890-8de8bb00-1135-11ea-81d9-df56914e3e08.png)

**Comment by leoding86** [comment]
I cannot repo it. Which version do you use?

**Comment by takase1121** [comment]
pixiv toolkit: v3.4.2
browser: edge canary Version 80.0.345.0 (Official build) canary (64-bit)

**Comment by leoding86** [comment]
Edge 🤔 ? I'll investigate it later, I cannot use Edge for this moment.

**Comment by takase1121** [comment]
Its edge but technically it's chromium. Next release of microsoft edge i
think. That's why its able to use the google web store.

**Comment by leoding86** [comment]
I kown that. But something just goes wrong sometimes.

**Comment by takase1121** [comment]
True. Good luck

**Comment by leoding86** [comment]
Download the Edge which the version you mentioned, still cannot repo this. Maybe a reinstallation can fix this. Remember export you visit history if you don't want to lose your visit history.

![#13](https://raw.githubusercontent.com/leoding86/image-storage/master/webext-pixiv-toolkit-issue%2313.gif)

**Comment by takase1121** [comment]
Interesting. Will try

**Comment by leoding86** [comment]
I'll leave it open. If you find any further information, please let me know.

**Comment by takase1121** [comment]
![2019-11-28_01-37-37](https://user-images.githubusercontent.com/20792268/69746687-d036ea00-117f-11ea-99f7-b69091ab646e.gif)

Looks like the almighty reinstall method worked, and yes that is and Edge/Windows bug. Sucks to live with Windows Insider.
