### ISSUE TITLE
bug报告

### ISSUE THREAD

**Issue by Meitake** [leoding86/webextension-pixiv-toolkit#131]
**描述错误**
下载漫画的时候无法打包

**预期行为**
可以打包下载全部。

**示例作品**
所有漫画都是如此

**截图**

**浏览器以及版本（请填写以下信息）：**
 Chrome

**插件设置**
[pixiv_toolkit_settings-1629339761389.zip](https://github.com/leoding86/webextension-pixiv-toolkit/files/7011305/pixiv_toolkit_settings-1629339761389.zip)

**其他内容**
无

**Comment by leoding86** [comment]
related to #124
