### ISSUE TITLE
Extension built from source for firefox can't be added (add-on corrupt)

### ISSUE THREAD

**Issue by telumletiferum** [leoding86/webextension-pixiv-toolkit#132]
**Describe the bug**
The extension built from source for Firefox is not working

**Expected behavior**
1. Build from source
2. Compress /dist/firefox/ into a zip
3. Install extension
4. Should be added but instead says that the add-on is corrupt

**Screenshots**
![Screenshot 2021-08-19 211100](https://user-images.githubusercontent.com/46684919/130122220-2bbe4131-c733-40f3-a94e-6e55b3122367.png)

Folder content after being built
![Screenshot 2021-08-19 211435](https://user-images.githubusercontent.com/46684919/130122491-3587cd07-eba8-44f9-af43-16a0baccca2a.png)

**Browser and Version**
 - Firefox

**Additional context**
The build was exactly replicated as CircleCI workflow

**Comment by leoding86** [comment]
The latest version isn't test on Firefox. CircleCI is only used for building.

**Comment by leoding86** [comment]
I've done some simple tests. It can be installed and works as expected (except it can't use ffmpeg as converter to convert ugoira to other formats). Need for information to investigate further.

I tested it on Window 10 and Firefox 90.0.1

**Comment by telumletiferum** [comment]
So I was only able to add it via debugging page where you can load temporary extension. Is there a way to properly install it? How did you get it installed in your case @leoding86 ?

**Comment by leoding86** [comment]
@telumletiferum I think I used the same way as you did. Loading it as temporary add-on in `about:debugging#/runtime/this-firefox`.

**Comment by telumletiferum** [comment]
So is that the only way to get it loaded?

**Comment by leoding86** [comment]
Yes, it is the only way to load the extension for now. I don't submit it to Firefox Add-on site because there are issues need to fix.

**Comment by telumletiferum** [comment]
Alright then I'm closing this issue

**Comment by telumletiferum** [comment]
I'm commenting to this issue to quickly show people how to install the add-on forever, because if you install it via about:debugging it will disappear on browser restart. So here's how to do it:
1. Build the extension from source or grab the artifact for firefox from CircleCI
2. In about:config page of firefox, search for `xpinstall.signatures.required` and change it's value from `true` to `false`
3. In the extension folder, open manifest.json and add this property `"browser_specific_settings": { "gecko": { "id": "extension@xScruffers.github.com" }}`
4. Zip the folder contents with whatever tool you use and rename the file extension to .xpi
5. Drag the .xpi file into about:addons and now the extension should be installed and not disappearing on restart
