### ISSUE TITLE
Toolkit not showing on Fanbox anymore

### ISSUE THREAD

**Issue by Spitoven** [leoding86/webextension-pixiv-toolkit#133]
Hello, the problem is pretty simple, Pixiv Toolkit used to add a small tool bar on the bottom left corner when I was on a Fanbox post page so I could directly download everything in a .rar archive, and for some reason this tool bar totally disappreared a few days ago, while everything on the main Pixiv website is still there and working. I haven't touched anything on the extension though... 🤔

**Comment by leoding86** [comment]
related to #123
