### ISSUE TITLE
Remove the folder, please

### ISSUE THREAD

**Issue by SWN-002** [leoding86/webextension-pixiv-toolkit#137]
With the new version. Even when download only single picture, the extention still put it into a folder. Please, NO. It is REALLY annoying. Please REMOVE it! I don't want any compressed file and an only one file folder.

**Comment by leoding86** [comment]
Version 5.2.0 has been published, please update it and try again.

**Comment by SWN-002** [comment]
Unfortunately, the problem was still there when I set "Relative Location" by myself. Even I set disable download shelf, the extension STILL put the picture into a folder. You still keep the annoying function and unable to disable it.

**Comment by leoding86** [comment]
The extension allow you download all images into one folder or download the images into their own folder. Could you describe what you exactly want to do?

**Comment by SWN-002** [comment]
I want to see multiple images in one folder, not a folder only have one single image. Like what the old version did.

**Comment by SWN-002** [comment]
I hope your group have someone can read Mandarin. I will use Mandarin to describe my question again.
OK, 新版本增加「下載多張圖片時不做成壓縮檔」，這個功能很好，很實用。但是這時候發生一個問題，如果我設定將下載路徑設定在Download底下的子資料夾時，就會發生「即使只下載單張圖片，也會被強制放在同名的資料夾下」，這部份就非常讓我頭痛，因為我在整理時還得多一個動作去把圖從資料夾裡面拿出來，明明舊版本就不會另外建一個資料夾放圖，為什麼新版本偏偏要多此一舉？

**Comment by leoding86** [comment]
There is one group, just me.

按我的理解，你想要的是有多张图片的时候放在自己的目录里，只有一张图片时就不要放到自己的文件夹下？如果是这样，目前确实不支持这样设置。

**Comment by SWN-002** [comment]
應該這麼說，目前的情況是：無論多張圖片或是單張圖片，都會在自己的目錄裡面另外建一個與圖片檔名相關的資料夾，但我只要多張圖片的時候這樣作，單張圖片的時候不要建資料夾。希望未來可以這樣設定...
