### ISSUE TITLE
Downloaded files are all .bib

### ISSUE THREAD

**Issue by WindFox** [leoding86/webextension-pixiv-toolkit#143]
**Describe the bug**
Weather it's a single image, packing a gallery, or an ugoira, the files all get the .bib extension instead of .png, .zip, or .gif (etc)
Manually changing the extension of the files fixes them.

**Expected behavior**
For the proper extensions to be applied.

**Example work from Pixiv**
Any and all.

**Screenshots**

**Browser and Version (please complete the following information):**
Chrome. Extension version 5.2.0

**Settings of extension**
You can export the settings of extension in setting page.
[pixiv_toolkit_settings-1632114645734.zip](https://github.com/leoding86/webextension-pixiv-toolkit/files/7193693/pixiv_toolkit_settings-1632114645734.zip)

**Comment by leoding86** [comment]
I can't reproduce the issue. But I think I know what cause it. Try to fix it in the next version.

**Comment by WindFox** [comment]
Yup. It's working properly again. Thanks!
