### ISSUE TITLE
Why is the name of the downloaded file prefixed with null？(为什么下载文件的名称前面会加上null？)

### ISSUE THREAD

**Issue by li2412360774** [leoding86/webextension-pixiv-toolkit#15]
![image](https://user-images.githubusercontent.com/38518506/69837791-74598780-128b-11ea-84eb-06387aa4838f.png)

**Comment by leoding86** [comment]
这个和 #13 重复了。你是新装发现的问题还是升级以后发现的问题？

**Comment by leoding86** [comment]
这个问题是新装插件出现的还是更新插件后出现的？

**Comment by Omskbird-tech** [comment]
> 这个问题是新装插件出现的还是更新插件后出现的？

是现在的最新版。而且另问一句，为什么下载的GIF点开是空白的？但预览里显示封面，而且为什么点开动图后长时间只显示Downloading？

**Comment by Omskbird-tech** [comment]
> 这个问题是新装插件出现的还是更新插件后出现的？

我不是提问者（今天新下的），但也是出现了一样的问题。（以及一个没被问过的问题。）

**Comment by leoding86** [comment]
长时间显示Downloading是因为资源没有下载完成，P站更改目前使用了fetch接口获取资源，我尝试过依旧使用xhr但是请求一直失败，fetch目前不能获得下载进度，所以只能显示Downloading。至于null的问题，我在 #13 有截动图，除非能提供更详细的步骤，不然我也不好分析是什么问题。

**Comment by Omskbird-tech** [comment]
> 长时间显示Downloading是因为资源没有下载完成，P站更改目前使用了fetch接口获取资源，我尝试过依旧使用xhr但是请求一直失败，fetch目前不能获得下载进度，所以只能显示Downloading。至于null的问题，我在 #13 有截动图，除非能提供更详细的步骤，不然我也不好分析是什么问题。

好迅速！让我试试。。。

**Comment by Omskbird-tech** [comment]
> 长时间显示Downloading是因为资源没有下载完成，P站更改目前使用了fetch接口获取资源，我尝试过依旧使用xhr但是请求一直失败，fetch目前不能获得下载进度，所以只能显示Downloading。至于null的问题，我在 #13 有截动图，除非能提供更详细的步骤，不然我也不好分析是什么问题。

是更改→命名动图下载文件吗？如果是的话，改完了。正在测试是否成功，另外，刚才下载得GIF图点开后是空白。。。？

**Comment by Omskbird-tech** [comment]
> 长时间显示Downloading是因为资源没有下载完成，P站更改目前使用了fetch接口获取资源，我尝试过依旧使用xhr但是请求一直失败，fetch目前不能获得下载进度，所以只能显示Downloading。至于null的问题，我在 #13 有截动图，除非能提供更详细的步骤，不然我也不好分析是什么问题。

但预览图显示有图。

**Comment by Omskbird-tech** [comment]
> 长时间显示Downloading是因为资源没有下载完成，P站更改目前使用了fetch接口获取资源，我尝试过依旧使用xhr但是请求一直失败，fetch目前不能获得下载进度，所以只能显示Downloading。至于null的问题，我在 #13 有截动图，除非能提供更详细的步骤，不然我也不好分析是什么问题。

更改后还是有null。。。

**Comment by leoding86** [comment]
麻烦提供下浏览器以及浏览器版本，然后是出现问题的作品链接，我明天看看吧。

**Comment by Omskbird-tech** [comment]
> 麻烦提供下浏览器以及浏览器版本，然后是出现问题的作品链接，我明天看看吧。

https://www.pixiv.net/artworks/77937115（这还是短的了，刚才重登了一下甚至连触发文件启动都没成功。。。）
版本：3.4.3-19112809

**Comment by Omskbird-tech** [comment]
> 麻烦提供下浏览器以及浏览器版本，然后是出现问题的作品链接，我明天看看吧。

啊不对。我提供的是插件版本。

**Comment by Omskbird-tech** [comment]
> 麻烦提供下浏览器以及浏览器版本，然后是出现问题的作品链接，我明天看看吧。

78.0.3904.108（正式版本） （64 位）

**Comment by Omskbird-tech** [comment]
> 麻烦提供下浏览器以及浏览器版本，然后是出现问题的作品链接，我明天看看吧。

（还看了几个那啥图就不给网址了哈哈。）

**Comment by Omskbird-tech** [comment]
> 麻烦提供下浏览器以及浏览器版本，然后是出现问题的作品链接，我明天看看吧。

先睡觉了。。。晚安、感谢帮助。

**Comment by leoding86** [comment]
使用Edge insder dev，从3.4.2升级至3.4.3，没有重现问题；
使用Chrome dev，从3.4.2升级至3.4.3，没有重现问题；
使用Chrome正式版，从3.4.2升级至3.4.3，没有重现问题。
目前的情况是我没法复现问题，如果你会使用浏览器开发者工具（Development Tool）可以尝试分析下。如果不会的话就只能重装插件了，如果你想保留浏览记录请记得先导出数据（在“设置”页的“历史记录”部分）。

**Comment by li2412360774** [comment]
> 使用Edge insder dev，从3.4.2升级至3.4.3，没有重现问题；
> 使用Chrome dev，从3.4.2升级至3.4.3，没有重现问题；
> 使用Chrome正式版，从3.4.2升级至3.4.3，没有重现问题。
> 目前的情况是我没法复现问题，如果你会使用浏览器开发者工具（Development Tool）可以尝试分析下。如果不会的话就只能重装插件了，如果你想保留浏览记录请记得先导出数据（在“设置”页的“历史记录”部分）。
我的浏览器版本是
![image](https://user-images.githubusercontent.com/38518506/69924060-44f18780-14e4-11ea-8256-91cb214ae27d.png)
目前是下载任意文件都会带上一个null

**Comment by li2412360774** [comment]
> 使用Edge insder dev，从3.4.2升级至3.4.3，没有重现问题；
> 使用Chrome dev，从3.4.2升级至3.4.3，没有重现问题；
> 使用Chrome正式版，从3.4.2升级至3.4.3，没有重现问题。
> 目前的情况是我没法复现问题，如果你会使用浏览器开发者工具（Development Tool）可以尝试分析下。如果不会的话就只能重装插件了，如果你想保留浏览记录请记得先导出数据（在“设置”页的“历史记录”部分）。

现在我重新安装插件后又没了，奇怪的问题。。。

**Comment by li2412360774** [comment]
> > 麻烦提供下浏览器以及浏览器版本，然后是出现问题的作品链接，我明天看看吧。
> 
> 先睡觉了。。。晚安、感谢帮助。

重新安装问题就没了。。。

**Comment by Omskbird-tech** [comment]
> > > 麻烦提供下浏览器以及浏览器版本，然后是出现问题的作品链接，我明天看看吧。
> > 
> > 
> > 先睡觉了。。。晚安、感谢帮助。
> 
> 重新安装问题就没了。。。

搞定了。。。

**Comment by Omskbird-tech** [comment]
> 使用Edge insder dev，从3.4.2升级至3.4.3，没有重现问题；
> 使用Chrome dev，从3.4.2升级至3.4.3，没有重现问题；
> 使用Chrome正式版，从3.4.2升级至3.4.3，没有重现问题。
> 目前的情况是我没法复现问题，如果你会使用浏览器开发者工具（Development Tool）可以尝试分析下。如果不会的话就只能重装插件了，如果你想保留浏览记录请记得先导出数据（在“设置”页的“历史记录”部分）。

搞定了，感谢。
