### ISSUE TITLE
可以添加在作者页面批量下载作品吗？

### ISSUE THREAD

**Issue by passingamd** [leoding86/webextension-pixiv-toolkit#154]
有的时候刚刚发现一个作者的图片很符合XP，但是作品量太大了 一个个下我得累死，好人一生平安

**Comment by leoding86** [comment]
插件版本目前不会实现这个功能。如果你使用的是PC，可以尝试我的另一个项目[Pixiv Omina](https://github.com/leoding86/pixiv-omina/releases)，不过有段时间没有维护了，不保证没什么问题。
