### ISSUE TITLE
gif下载错误

### ISSUE THREAD

**Issue by xuyuan-Chen** [leoding86/webextension-pixiv-toolkit#156]
**描述错误**
更新插件后，生成gif时显示√完成，但是实际下并没有下载下来

**示例作品**
所有gif下载都是，不是单一图片问题

**浏览器以及版本（请填写以下信息）：**
chrome 95.0.4638.54

**其他内容**
转化工具：默认，打包帧类型1
FFmpeg也无法正常下载

**Comment by hal0thane** [comment]
I have also encountered this problem, whether trying to save as ZIP, GIF, WEBM, or APNG. No download shelf (normally I see it). Verified that files are not being downloaded. First encountered with upgrade from v5.2.1 to v5.3.0.

I am using Chrome 96.0.4664.27 (Official Build) beta (x86_64) on MacOS 10.11.6.

**Comment by sakurairsora** [comment]
5.30版本下，txt一样无法下载

**Comment by makotosxx** [comment]
gif太占地方，于是尝试webm，但是现在的版本保存的webm无法播放；几个月前还是OK的

**Comment by leoding86** [comment]
似乎是Chrome的兼容性有问题，我用Edge没任何问题。我抽时间看看🤔

**Comment by leoding86** [comment]
找到问题了，有个`return`的位置写错地方了，导致如果启用了插件接管下载后无法创建下载任务。我Edge的测试配置没有启用这个设置，所以一直是正常的。插件设置太多了，总会有测试项忘了做🤦‍♂️

明天提交一个修复版本。

**Comment by hal0thane** [comment]
Thank you! I'm glad to know I will be able to download ugoira again.
Apologies for writing in English.
