### ISSUE TITLE
Files not being saved after generating when I enable Relative Locations

### ISSUE THREAD

**Issue by rinalee** [leoding86/webextension-pixiv-toolkit#157]
**Describe the bug**
My generated ugoira are not being saved/downloaded after generating when I enable "Allow extension takes over downloads" and thus the Relative Locations. Nothing happens after the file generation and it shows "Save WEBM" but when I click on it nothing happens. (the download works when I disable them)

**Expected behavior**
The file should be directly downloaded after the WebM generation into the folder I attributed it to (into pixiv_downloads/{author}({id})/ with the filename {title}({id}).webm )

**Example work from Pixiv**
https://www.pixiv.net/en/artworks/78593462

**Screenshots**

**Browser and Version (please complete the following information):**
Google Chrome Version 95.0.4638.69 (Official Build) (64-bit)

**Settings of extension**
`{"MangaPageNumberStartWithOne":false,
"alwaysPack":false,
"animationJsonFormat":1,
"askDownloadSavedWork":true,
"autoActivateDownloadPanel":false,
"disableDownloadsShelf":false,
"displayWorkTypeLabel":true,
"downloadPackFiles":false,
"downloadRelativeLocation":"pixiv_downloads/",
"downloadSaveAs":false,
"downloadTasksWhenDownloadingImages":3,
"enableExtTakeOverDownloads":true,
"enableExtend":false,
"enableExtension":true,
"enablePackUgoiraFramesInfo":true,
"enablePtkSearch":true,
"enableSaveDownloadHistory":1,
"enableSaveVisitHistory":true,
"enableWhenUnderSeconds":1,
"extendDuration":3,
"featureKnown":false,
"guideShowed":true,
"illustrationCreateSubdirectory":1,
"illustrationImageRenameFormat":"",
"illustrationKeepPageNumber":false,
"illustrationPageNumberLength":0,
"illustrationPageNumberStartWithOne":false,
"illustrationRelativeLocation":"pixiv_downloads/",
"illustrationRenameFormat":"",
"importantNoticeDisplayed":true,
"language":"default",
"mangaImageRenameFormat":"",
"mangaPageNumberLength":0,
"mangaPagesInChunk":99,
"mangaRelativeLocation":"pixiv_downloads/",
"mangaRenameFormat":"",
"maxDownloadRecords":10000,
"maxHistoryItems":10000,
"multipleDownloadsGapTime":150,
"notSaveNSFWWorkInHistory":false,
"novelIncludeDescription":false,
"novelRelativeLocation":"pixiv_downloads/",
"novelRenameFormat":"",
"showUpdateChangeLog":true,
"statIllustDownloaded":0,
"statMangaDownloaded":0,
"statNovelDownloaded":0,
"statUgoiraDownloaded":5,
"ugoiraConvertTool":"default",
"ugoiraCustomFFmpegCommand":"",
"ugoiraQuanlity":1,
"ugoiraRelativeLocation":"pixiv_downloads/{author}({authorId})/",
"ugoiraRenameFormat":"{title}({id})",
"version":"5.3.0",
"visitHistoryType":"list",
"workCoverSize":1}`

**Additional context**

**Comment by leoding86** [comment]
5.3.0 has a issue about the extension can't download anything when the setting `Allow extension takes over downloads` is enabled. I'll submit a new version tomorrow.
