### ISSUE TITLE
Novels not downloading

### ISSUE THREAD

**Issue by scampadversary** [leoding86/webextension-pixiv-toolkit#159]
Neither the epub nor txt download buttons work for novels. They display a checkmark when I click them and the work goes under Toolkit's download history, but nothing shows up under chrome's download history or in my files. I'm using chrome version 95.0.4638.69.

Here's a [link](https://www.pixiv.net/novel/show.php?id=696710) so you can reproduce the problem. I have Toolkit set to rename the novel and include the novel description at the start. It's not set to save in a relative location.

**Comment by momonenet** [comment]
我也下载不了，但我学习脚本后解决了，可能是pixiv更新了什么？
`import requests
from bs4 import BeautifulSoup as soup
from fake_useragent import UserAgent
import json


# 开头输出
print("\n该脚本爬取 https://www.pixiv.net/ 的小说")

# 初始化
init_req = input("\nexample:https://www.pixiv.net/novel/show.php?id=16175388\n输入您下载小说的网址: ")
sign_page = init_req.replace('https://www.pixiv.net/novel/show.php?id=', '')

# 使用代理访问外网
port_sock = input("\n由于国内封锁pixiv，请使用vpn进行下载\n1.打开vpn客户端\n2.打开全局模式\n3.找到自己的sock接口，example：10808\n您的sock接口为： ")
proxy = '127.0.0.1:' + port_sock
proxies = {'http': 'socks5://' + proxy, 'https': 'socks5://' + proxy}
print("\n使用socks端口成功")

# 使用fake代理
ua = UserAgent(path="D:/Books/fakeuseragent.json")
response = requests.get(init_req, proxies=proxies, headers={'User-Agent': ua.random})
print("\nfake代理成功")

# 分析html页面
response.encoding = 'utf-8'
page_soup = soup(response.content, "html.parser")
print("\n载入页面成功")

list_meta = page_soup.findAll("meta")
# 寻找主体内容
dict_novel = json.loads(page_soup.findAll("meta")[14]['content'])
# 标题
title = dict_novel['novel'][sign_page]['title']
# 作者
userName = dict_novel['novel'][sign_page]['userName']
# 创建日期
createDate = dict_novel['novel'][sign_page]['createDate']
# 描述
description = dict_novel['novel'][sign_page]['description']
# 内容
content = dict_novel['novel'][sign_page]['content']

# 装到文件中
filename = title + '.txt'
with open(filename, "w", encoding="utf-8") as f:
    f.write(title + "\n\n")
    f.write(userName + "\n\n")
    f.write(createDate + "\n\n")
    f.write(description + "\n\n")
    f.write(content)
f.close()
print("\n下载成功")


`

**Comment by leoding86** [comment]
@scampadversary I can't reproduce the problem. I tested the link you given and downloaded the novel as epub or txt without any problem. Could you provide the information in the browser inspect console? I need more information for further investigation.

@momonenet 我没有能够复现不能下载的问题，能提供浏览器调试模式中的终端信息吗？如果不能下载应该会有错误提示。

**Comment by scampadversary** [comment]
@leoding86 Looking under my console when I load the novel, I see these messages about Toolkit: 
 
> DevTools failed to load source map: Could not load content for chrome-extension://ajlcnbbeidbackfknkgknjefhmbngdnj/lib/gifjs/gif.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
> DevTools failed to load source map: Could not load content for chrome-extension://ajlcnbbeidbackfknkgknjefhmbngdnj/lib/ffmpeg/ffmpeg.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

When I click the button to download an epub, I get this, but nothing happens:

> js-epub-maker.js:107 generating epub for: 悪意は貴方の傍にある

Nothing shows up when I press the button to download it as .txt. 

I hope this is what you meant for me to share. I'm at absolute commoner level in terms of understanding code, so I wasn't even sure what I should be providing or how. I'm sorry...

**Comment by leoding86** [comment]
@scampadversary If you enable the setting `Allow extension takes over downloads`?

**Comment by scampadversary** [comment]
@leoding86 Yes, it's enabled.

**Comment by leoding86** [comment]
The new version has been released and the issue should be fixed.

**Comment by scampadversary** [comment]
Yes, it works now! Thank you so much.
