### ISSUE TITLE
Stuck on "downloading" on ugoira

### ISSUE THREAD

**Issue by karasawa-user** [leoding86/webextension-pixiv-toolkit#16]
Is there any way to know how far this extension downloading ugoira data before download menu available or at least indicator of it working on something?
It seems never completed on some ugoiras and I really can't tell reloading the addon really fix the issue. Here's the sample work that keep stuck at downloading no matter what I do:
https://www.pixiv.net/en/artworks/73031132

I using vivaldi 2.9.1705.41 and firefox 61.0.2 on windows 10
![Screenshot_2019-12-03 cowgirl position, creampie, Yuzuki Yukari 結月ゆかりS○XROID版 - pixiv](https://user-images.githubusercontent.com/58468168/70044394-de0fc380-15f4-11ea-9b80-34e37ffdd82a.png)

**Comment by leoding86** [comment]
Downloading means the extension is downloading the resources, I'm pretty sure it caused by slow network.

The Pixiv uses fetch api to get resources data and the api can't tell the download progress. I tried to use xhr to request resources, but after several tries there was no luck.

I could use response.body property, it's a ReadableStream, to computed the progress. It's not widely supported but I'll give it a try later.

**Comment by karasawa-user** [comment]
I afraid it's not caused by slow network because some long ugoiras downloaded pretty fast... But just in case, is "wrong IP" case could happen in this addon? If that so then it's still my net's fault

**Comment by leoding86** [comment]
I tried the url in vivaldi (2.9.1705.41), the extension works fine. Could you screenshot the red lines in the Console of DevTools of the browser. It will display more infomations I need to investigate the issue.
I haven't updated the addon on Firefox for a long time. I can't make sure the addon on Firefox will works as expected.

**Comment by karasawa-user** [comment]
Somehow link above managed to be downloaded today, this from different work, https://www.pixiv.net/en/artworks/75954856

![2019-12-04 13 42 14-dbfa1792a830_n](https://user-images.githubusercontent.com/58468168/70119044-fe468d80-169b-11ea-8d78-2b26d5756f01.png)
![2019-12-04 13 43 57-fa7b1be32418_n](https://user-images.githubusercontent.com/58468168/70119176-4d8cbe00-169c-11ea-803d-409e4959fa58.png)

**Comment by karasawa-user** [comment]
And this is from firefox side, this extension can't work if tracking protection is on so I turn it off first
![2019-12-04_14-00-36](https://user-images.githubusercontent.com/58468168/70120191-7a41d500-169e-11ea-93bb-8ac5e9fc7597.png)

**Comment by leoding86** [comment]
It seems like the extension has been interrupted by something to make the fetch api cannot fetch data properly. I need to do some test work to find what's going on.

**Comment by leoding86** [comment]
Still have no idea what‘s caused this. Will add a retry button after download is interrupted. Update in next version.
