### ISSUE TITLE
Ugoira download with "Allow extensions take over download" turned on in chrome not working

### ISSUE THREAD

**Issue by joneschong** [leoding86/webextension-pixiv-toolkit#160]
**Describe the bug**
When turned on "Allow extensions take over download" in chrome, when downloading ugoira in GIF, after it reaches 100% in generating, nothing happens and the GIF is not downloaded at all. 

**Expected behavior**
GIF should be downloaded into the relative location

**Example work from Pixiv**
[If applicable, add work url to help me to reproduce the problem.]
(https://www.pixiv.net/en/artworks/88726801)

**Screenshots**
![image](https://user-images.githubusercontent.com/90016686/142373490-d602c780-9b25-40de-94d5-c026ac677817.png)
![image](https://user-images.githubusercontent.com/90016686/142373506-a288cf8b-e401-41e9-adf8-2926a08e1b75.png)
![image](https://user-images.githubusercontent.com/90016686/142373567-ef45a44d-d658-4923-bc9a-a03ff772323a.png)
![image](https://user-images.githubusercontent.com/90016686/142373588-4e8d171f-255f-4f71-b919-60e9abcb4e30.png)
![image](https://user-images.githubusercontent.com/90016686/142375767-82c0be9b-9e96-4695-adce-dc73df92673e.png)
![image](https://user-images.githubusercontent.com/90016686/142375855-e8271818-09a5-44f1-8ba1-7614a4f11b7c.png)
**Browser and Version (please complete the following information):**
 - Chrome Version 96.0.4664.45 (Official Build) (64-bit)
**Settings of extension**
You can export the settings of extension in setting page.
{"MangaPageNumberStartWithOne":false,"alwaysPack":false,"animationJsonFormat":1,"askDownloadSavedWork":false,"autoActivateDownloadPanel":false,"disableDownloadsShelf":false,"displayWorkTypeLabel":true,"downloadPackFiles":true,"downloadRelativeLocation":"GIF/","downloadSaveAs":false,"downloadTasksWhenDownloadingImages":5,"enableExtTakeOverDownloads":true,"enableExtend":false,"enableExtension":true,"enablePackUgoiraFramesInfo":true,"enablePtkSearch":true,"enableSaveDownloadHistory":1,"enableSaveVisitHistory":false,"enableWhenUnderSeconds":1,"extendDuration":3,"featureKnown":false,"guideShowed":true,"illustrationCreateSubdirectory":1,"illustrationImageRenameFormat":"","illustrationKeepPageNumber":false,"illustrationPageNumberLength":0,"illustrationPageNumberStartWithOne":false,"illustrationRelativeLocation":"","illustrationRenameFormat":"","importantNoticeDisplayed":true,"language":"default","mangaImageRenameFormat":"","mangaPageNumberLength":0,"mangaPagesInChunk":99,"mangaRelativeLocation":"","mangaRenameFormat":"","maxDownloadRecords":10000,"maxHistoryItems":10000,"multipleDownloadsGapTime":150,"notSaveNSFWWorkInHistory":false,"novelIncludeDescription":false,"novelRelativeLocation":"","novelRenameFormat":"{title}","showUpdateChangeLog":true,"statIllustDownloaded":0,"statMangaDownloaded":0,"statNovelDownloaded":0,"statUgoiraDownloaded":89,"ugoiraConvertTool":"default","ugoiraCustomFFmpegCommand":"","ugoiraQuanlity":10,"ugoiraRelativeLocation":"","ugoiraRenameFormat":"","version":"5.3.0","visitHistoryType":"list","workCoverSize":1}

**Additional context**

**Comment by leoding86** [comment]
I already submitted a new version to Chrome Store. But you can download the crx version [here](https://github.com/leoding86/webextension-pixiv-toolkit/releases/tag/5.4.0) if you want to use the new version early.
