### ISSUE TITLE
Pixiv Toolkit has not been receiving updates on Firefox Addons

### ISSUE THREAD

**Issue by Pxartist** [leoding86/webextension-pixiv-toolkit#165]
Title says it all

[https://addons.mozilla.org/en-US/firefox/addon/pixiv-toolkit/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search](https://addons.mozilla.org/en-US/firefox/addon/pixiv-toolkit/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search)

**Comment by Pxartist** [comment]
Spent like 6+ hours on figuring out how to build and sign the extension to work with Firefox, only to end up with a nonfunctional extension.





For anyone who wants to attempt to build the extension using source code, I installed Python 2.7.18 and nvm version 1.1.9.
I then used nvm to install nodejs 14.18.3 using a terminal. The code seems to have compatability issues with more up to date versions.

Be sure to install everything with administrative privileges and add any necessary PATH / environment variables.

Unzipped the source code folder and navigated a terminal to it.

I then added a manifest.json file and copy and pasted the contents from package.json into it. (Probably why the extension does nothing at all)

Following instructions from [https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/](https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/), added a `"manifest_version": 2,` and `"browser_specific_settings": {
  "gecko": {
    "id": "{b8b97a90-2d56-4e8b-8a29-8981356311af}",
    "strict_min_version": "42.0"

  }`

to the manifest.json file



followed the instructions from the readme.md file
ran `web-ext build` in the terminal

and then followed instructions from [https://extensionworkshop.com/documentation/publish/distribute-sideloading/](https://extensionworkshop.com/documentation/publish/distribute-sideloading/)

Got the extension signed and able to added to Firefox and it does nothing at all. Probably has to do with how the manifest file was set up.

**Comment by leoding86** [comment]
I just update version 5.5.2 to Firefox add-ons. It'll take some time to get approved. I update the xpi file in release page, you can download it and install it manully.
BTW, I foget to updae the version number, so you could see the version number is 5.5.1, but it's not a big deal.
