### ISSUE TITLE
下载小说时无法标注系列名以及序号

### ISSUE THREAD

**Issue by zhantshen** [leoding86/webextension-pixiv-toolkit#168]
**描述错误**
目前在将小说下载为epub和txt文档时，并没有办法在文件名或者文档中标注小说系列名称以及编号，这样对于整理系列小说的时候会很麻烦

**预期行为**
在Rename novel中增加 {series} 和 {series_number} 两个选项，前者会提供小说系列名称，后者会提供小说在系列中的编号

例如：
下载小说 https://www.pixiv.net/novel/show.php?id=9643068 时，在小说重命名中标注名称为：
{author}-{series}-{series_number}-{title}-{id}  
下载文件名称应显示为：
神山-王道になりたくない！-2-王道になりたくない！ ②-9643068

**示例作品**
任何包括在系列小说中的小说

**浏览器以及版本（请填写以下信息）：**
Chrome 97

**Comment by leoding86** [comment]
版本5.5.0已添加此功能。
