### ISSUE TITLE
 Pixiv Omina Button Is Missing

### ISSUE THREAD

**Issue by resolutedreamer** [leoding86/webextension-pixiv-toolkit#174]
**Describe the bug**
In version 5.5.0 of Pixiv Toolkit, the button to download files from Pixiv Omina is gone.

**Expected behavior**
In previous versions, you could click on the Pixiv Omina button to send the file to the other application for download.

**Example work from Pixiv**
Applies to all Pixiv images.

**Screenshots**
<img width="353" alt="image" src="https://user-images.githubusercontent.com/3419924/154910379-1348b592-01c0-4cc9-b3e8-f8e22c294d7a.png">

**Comment by leoding86** [comment]
I removed it accidentally. It'll be fixed in the next version.

**Comment by leoding86** [comment]
It's fixed. Try the latest version.
