### ISSUE TITLE
fanbox下載完後為undefined.zip

### ISSUE THREAD

**Issue by ddante355101** [leoding86/webextension-pixiv-toolkit#175]
fanbox下載完後為undefined.zip，開啟zip檔後不是JPG檔，而是.html

![image](https://user-images.githubusercontent.com/100475441/155844799-f3fd990c-d749-4f91-909c-021dba6eea66.png)

**Comment by leoding86** [comment]
是否能提供目标链接？

**Comment by AmahaSuzune** [comment]
我也遇到了类似的问题，不过我的压缩包名称是正确的，但是打开里面只有一个html文件而没有图片，而且html文件也不是原本的网页，而是403forbidden

**Comment by leoding86** [comment]
@ddante355101 
原来的版本是好的吗？我使用免费的链接以及上面提供的链接我都没有发现问题。

@AmahaSuzune 
一般来说403可能是因为作品是NSFW并且没有确认年龄导致的。

**Comment by ddante355101** [comment]
@leoding86 我回去再試試！

**Comment by ddante355101** [comment]
@leoding86 測試過了，全體公開的解析沒問題，只是封包檔名還是顯示"undefined"，然後付費的就無法了，封包檔名顯示"undefined"，裡面的檔案也都是.html
![image](https://user-images.githubusercontent.com/100475441/155983184-1ffacc20-b213-4619-ae29-bf265d763c1a.png)
![image](https://user-images.githubusercontent.com/100475441/155983546-1cac981b-e7c9-4c56-9d48-035935bd2760.png)

**Comment by leoding86** [comment]
我刚刚订阅了一个用户，确实能复现问题。修复这个问题应该花不了很长时间。

**Comment by ddante355101** [comment]
好的，感謝！

**Comment by leoding86** [comment]
@ddante355101 能提供一下你的扩展的设置吗？我还是无法附件压缩包名为 undefined 的问题。

**Comment by ddante355101** [comment]
要如何提供擴展設置？

**Comment by leoding86** [comment]
@ddante355101 不需要了，已经找到是什么问题了。
