### ISSUE TITLE
Pixiv Omina button does not function

### ISSUE THREAD

**Issue by GreenSwede** [leoding86/webextension-pixiv-toolkit#177]
**Describe the bug**
Clicking on the "Pixiv Omina" button does nothing when viewing art on Pixiv.

**Expected behavior**
Clicking on the button should add the image to the installed Pixiv Omina application.

**Example work from Pixiv**
https://www.pixiv.net/en/artworks/96383906

**Screenshots**
![chrome_2022-02-26_22-45-07](https://user-images.githubusercontent.com/42186507/155860202-76b72df9-79df-44a5-abd9-0ae37d5717de.gif)

**Browser and Version (please complete the following information):**
Chrome (Version 98.0.4758.102 (Official Build) (64-bit))
Windows 10 (Version 21H1 (OS Build 19043.1526))

**Settings of extension**
[pixiv_toolkit_settings.zip](https://github.com/leoding86/webextension-pixiv-toolkit/files/8147581/pixiv_toolkit_settings.zip)

**Additional context**
N/A

**Comment by leoding86** [comment]
You could try this solution [https://github.com/leoding86/pixiv-omina/issues/27#issuecomment-605540955](https://github.com/leoding86/pixiv-omina/issues/27#issuecomment-605540955). Remember change the installation location to yours.

**Comment by GreenSwede** [comment]
Thank you, that worked
