### ISSUE TITLE
Download shelf automatically activates despite the setting being disabled

### ISSUE THREAD

**Issue by scampadversary** [leoding86/webextension-pixiv-toolkit#178]
Every time I load an illustration or novel page the download panel loads expanded. "Activate download panel automatically" is disabled in my settings, so I expected the shelf to load collapsed since that's what it was doing until now.

I was curious, so I also turned on the setting "Disable the downloads shelf." The panel still shows up then too.

My browser is Chrome 98.0.4758.102 

EDIT: If I've manually collapsed the panel after it loads expanded, it remains collapsed when I click to a different work on the same tab. However, when I open a new tab, it appears expanded. Not sure if this detail is helpful or not though.

**Comment by leoding86** [comment]
Download panel is the layer which contains buttons on the page. Downloads shelf is the browser download list that popup then a download is complete everytime. It's 2 different types of things.

I can't reproduce the issue. Could you provide the settings you're using?

**Comment by Michpem** [comment]
I'm having the same issue as OP on Opera beta 85.0.4341.6, and I can also confirm the behavior in the edit.

Here's my settings .json (... in .zip because Github doesn't like the format). "autoActivateDownloadPanel" is set to false, and changing the download panel style doesn't seem to affect the bug.
[pixiv_toolkit_settings-1646330353894.zip](https://github.com/leoding86/webextension-pixiv-toolkit/files/8180063/pixiv_toolkit_settings-1646330353894.zip)
.

**Comment by scampadversary** [comment]
Well, I always wondered about the terminology, so thanks for clarifying that.

Anyway, my settings: 

{"MangaPageNumberStartWithOne":false,"alwaysPack":false,"animationJsonFormat":1,"askDownloadSavedWork":true,"autoActivateDownloadPanel":false,"disableDownloadsShelf":false,"displayWorkTypeLabel":true,"downloadPackFiles":true,"downloadPanelPosition":"center","downloadPanelStyle":1,"downloadRelativeLocation":"pixiv/","downloadSaveAs":false,"downloadTasksWhenDownloadingImages":5,"enableExtTakeOverDownloads":true,"enableExtend":false,"enableExtension":true,"enablePackUgoiraFramesInfo":true,"enablePtkSearch":true,"enableSaveDownloadHistory":1,"enableSaveVisitHistory":true,"enableWhenUnderSeconds":1,"extendDuration":3,"featureKnown":false,"guideShowed":true,"illustrationCreateSubdirectory":0,"illustrationImageRenameFormat":"{authorId} {author} - {title} {id} - {pageNum}","illustrationKeepPageNumber":false,"illustrationPageNumberLength":2,"illustrationPageNumberStartWithOne":false,"illustrationRelativeLocation":"","illustrationRenameFormat":"{authorId} {author} - {title} {id}","importantNoticeDisplayed":true,"language":"default","mangaImageRenameFormat":"{authorId} {author} - {title} {id} - {pageNum}","mangaPageNumberLength":2,"mangaPagesInChunk":200,"mangaRelativeLocation":"","mangaRenameFormat":"{authorId} {author} - {title} {id}","maxDownloadRecords":10000,"maxHistoryItems":10000,"multipleDownloadsGapTime":150,"notSaveNSFWWorkInHistory":false,"novelIncludeDescription":true,"novelRelativeLocation":"","novelRenameFormat":"{authorId} {author} - {title} {id} ","pixivComicImageRenameFormat":"{episodeId}_{episodeTitle}_p{pageNum}","pixivComicPageNumberLength":0,"pixivComicPageNumberStartWithOne":false,"pixivComicRelativeLocation":"","pixivComicRenameFormat":"{episodeId}_{episodeTitle}","showPixivOmina":false,"showReloadInPopup":false,"showUpdateChangeLog":true,"statIllustDownloaded":1254,"statMangaDownloaded":636,"statNovelDownloaded":136,"statUgoiraDownloaded":5,"ugoiraConvertTool":"default","ugoiraCustomFFmpegCommand":"","ugoiraQuanlity":1,"ugoiraRelativeLocation":"","ugoiraRenameFormat":"{authorId} {author} - {title} {id}","version":"5.5.2","visitHistoryType":"list","workCoverSize":2}

**Comment by leoding86** [comment]
@scampadversary new version has been submitted. You can download it in release page and install it manually.
