### ISSUE TITLE
忽然发现不能用，不知道原因。

### ISSUE THREAD

**Issue by szw9536** [leoding86/webextension-pixiv-toolkit#18]
没有介绍里面的蓝色图标“P“，什么时候开始的说不清楚，因为有好几个月没去下载图片了
![image](https://user-images.githubusercontent.com/36043101/70843305-1e7c0680-1e6b-11ea-8be6-7c37fab64824.png)
![image](https://user-images.githubusercontent.com/36043101/70843308-263bab00-1e6b-11ea-9676-c8e2aaa869c9.png)
![image](https://user-images.githubusercontent.com/36043101/70843309-289e0500-1e6b-11ea-8715-e2aa425cf107.png)

**Comment by leoding86** [comment]
我试了试访问相同的作品，可以显示的出来。是否可以截下调试工具中的Console中的异常条目的图（F12->Console标签，需要在打开调试工具时刷新页面，否则可能不能捕捉的错误信息）？
![截图](https://raw.githubusercontent.com/leoding86/image-storage/master/webext-pixiv-toolkit-issue%2318.png)

**Comment by szw9536** [comment]
是这样吗？
![04](https://user-images.githubusercontent.com/36043101/70861533-22db1900-1f6a-11ea-901c-9119b968d59a.png)

**Comment by szw9536** [comment]
![05](https://user-images.githubusercontent.com/36043101/70861558-86654680-1f6a-11ea-847a-ddd1395d244b.png)

**Comment by leoding86** [comment]
看日志是在请求资源时超时了，目前我复现不了这个问题。如果你使用了科学上网可以试试使用全局规则试试能不能正常使用插件。或者可能和别的插件有冲突。

**Comment by szw9536** [comment]
可以了，十分感谢
