### ISSUE TITLE
"允许扩展程序接管下载"无法启用

### ISSUE THREAD

**Issue by ShenreiAL** [leoding86/webextension-pixiv-toolkit#184]
**描述错误**
清楚简明地描述错误是什么。

"允许扩展程序接管下载"无法启用，设定画面重整后就会取消勾选，也不会跳出任何要求下载权限提示。

**预期行为**
对你期望发生的事情的简洁明了的描述。

**示例作品**
如果可以，请提供发生错误的作品链接。

**截图**
如果可以，请添加屏幕截图以帮助解释你的问题。

**浏览器以及版本（请填写以下信息）：**
  -例如 Chrome，Edge，Firefox

Firefox

**插件设置**
你可以在设置页面导出插件设置。

**其他内容**
其他可用的信息。

**Comment by leoding86** [comment]
设置的问题已经修复了，但是接管下载的问题比我想的更复杂。Firefox对于插件下载接口的限制很奇怪，或者说是支持不足，没法使用插件的下载接口下载`content_page`中的`blob`类型链接。需要花一些时间来解决。

**Comment by leoding86** [comment]
目前修复的办法是个折中的方案，使用 Firefox 下载较大文件时（主要看前端线程和后端线程的通讯数据大小限制）会出现一些问题。

因为`manifest v2`已经进入计划废弃阶段，所以不在打算修改这一部分逻辑。整个下载逻辑在`manifest v2`完全废弃前进行重构。在较长时间内需要处理的事情非常多，所以不确定什么时候会开始实施。

版本的话会在几天内提交。

**Comment by leoding86** [comment]
我已经上传了最新版到Firefox addon，正在等待审核。你也可以在release页面下载并手动安装。

**Comment by ShenreiAL** [comment]
Firefox已自动更新，非常感谢您。
