### ISSUE TITLE
'Allow extension takes over downloads' doesn't stick or work.

### ISSUE THREAD

**Issue by SomeoneWhoJustWantsToBeHappy** [leoding86/webextension-pixiv-toolkit#185]
**Describe the bug**
I can't change the settings, particularly the 'allow extension takes over downloads' setting always resets whenever I close the settings and refuses to activate, including the 'ask where to save each file before downloading' option. 

**Expected behavior**
I expected it the settings to STICK.

**Example work from Pixiv**
No point since the issue isn't with pixiv, its with the settings.

**Screenshots**
Not applicable, its pretty self explanatory.

**Browser and Version (please complete the following information):**
Firefox 97.0.1 (64-bit)

**Settings of extension**
Exporting them and importing them doesn't actually do anything either, its just default settings.

**Additional context**
I just don't understand.

**Comment by leoding86** [comment]
Duplicate of #184

**Comment by SomeoneWhoJustWantsToBeHappy** [comment]
> Duplicate of #184

Oh yeah gee, thanks for marking it as a duplicate of something written completely in text I CAN'T READ.
