### ISSUE TITLE
最新版本的扩展在Firefox下会造成Fanbox无法正常浏览和登录

### ISSUE THREAD

**Issue by Godoword** [leoding86/webextension-pixiv-toolkit#187]
**描述错误**
更新Firefox扩展到最新的5.5.1后（Firefox那边显示的版本号还是5.5.1，看描述应该就是5.5.2），打开Fanbox无法浏览，提示出错，无法加载出来。清空缓存后登录也一样。

排查后发现是扩展更新后造成的，禁用后正常。新要求的权限已经给了。

Pixiv倒是正常的，我也没有使用其他相关的扩展或脚本。

**截图**
https://i.imgur.com/x9BKw2Z.png
https://i.imgur.com/rBR0HMS.png
https://i.imgur.com/GIQZwK6.png

**浏览器以及版本（请填写以下信息）：**
Firefox 97.0.1（PC）

**Comment by leoding86** [comment]
Duplicate of #183
