### ISSUE TITLE
版本更新後設定跑掉

### ISSUE THREAD

**Issue by SWN-002** [leoding86/webextension-pixiv-toolkit#189]
感謝在前幾版新增可設定「只在多個圖片檔案時增加子資料夾」選項，但現在有個問題，我如果印象沒錯，應該最晚是5.4.0版時開始的，從這版開始只要附加元件升級，上述設定就會自動跳回「永遠增加子資料夾」，需要手動去調回。

**Comment by SWN-002** [comment]
最新5.5.3又跳回去啦...

**Comment by leoding86** [comment]
这个bug源码已经修复了，下个版本应该不会再出问题了。
