### ISSUE TITLE
Still doesn't work on illust/manga pages after 3.0-beta update

### ISSUE THREAD

**Issue by appcell** [leoding86/webextension-pixiv-toolkit#2]
Browser: Google Chrome: Version 77.0.3865.90 (Official Build) (64-bit)
OS: Win 10 x64
Pixiv Toolkit: 3.0-beta (updated on 25th Sept 2019)

Tested page: https://www.pixiv.net/artworks/76962762
The "P*" button refused to appear.

**Comment by leoding86** [comment]
Everything works fine in Chrome 78 and Firefox 69. Could you screenshot messages in browser inspect console?

**Comment by appcell** [comment]
[Imgur](https://i.imgur.com/nfM4Qb1.png)

Does this screenshot contain info that you need?

**Comment by leoding86** [comment]
It seem like the scripts has not been injected to the page. I recommend you to reinstall the extension and try again. And could you screenshot the options page? Maybe some settings broken the extension when the extension has been updated. I'll give it more investigation.

**Comment by appcell** [comment]
[Imgur](https://i.imgur.com/knxtDTs.png)

[Imgur](https://i.imgur.com/2kM4suT.png)

Regarding download permission: somehow the grant permisson button doesn't work. I ran Chrome in administrator mode but nothing changed.

I reinstalled the plugin, also Chrome itself, for multiple times. Same thing happened. AFAIK Chrome 77 is still the stable release.

**Comment by leoding86** [comment]
Issue confirmed, trying to figure out why.

**Comment by leoding86** [comment]
> Issue confirmed, trying to figure out why.

Issue is located. I'll fix it soon.

**Comment by leoding86** [comment]
Issue has been fixed in 3.0.1 beta.
Closed

**Comment by appcell** [comment]
Thx for your fast reply ;)
