### ISSUE TITLE
(Suggestion) Adding more items to illustration name

### ISSUE THREAD

**Issue by Tvtossen** [leoding86/webextension-pixiv-toolkit#20]
Hi, I think it would be nice if you could add a {tags} option to the illustration name, {year} and {month} wouldn't hurt either :)

**Comment by leoding86** [comment]
The {year} and {month} placeholders can be done. But I can't figura out how to use the 'tags'. A illustration can have many tags that can take up many characters in filename. And a file with very long filename may not be accessible.
