### ISSUE TITLE
Page number issue when saving

### ISSUE THREAD

**Issue by basic2004** [leoding86/webextension-pixiv-toolkit#22]
1. saving page number is different when manga (multi page illust) downloading.
Currently saving page number is different.
Automatic download (Pack and download), page number starts from 0 to n.
Manually download (Save chunk 0-n), page number start from 1 to n+1.

2. No need 'Rename illustration image' (when one page illust).
Maybe this feature should need when packing zip this one page illust.
And no need {pageNum} with 'Rename illustration image' because this works with one page illust,
and more issue currently, unnessary page number 0 injected to end of filename when without {pageNum} prefix.

please fix these.
Thanks.

**Comment by leoding86** [comment]
I cannot reproduce the first issue you mentioned. Are you sure this issue happened when downloading manga? Manga and multiple pages illust are treated as different types work in the extension.

The second issue is not a issue but I'll improve the rename function.

**Comment by leoding86** [comment]
Second request is done. Still can't reproduce the first issue.
