### ISSUE TITLE
"I can't download manga on the comic.pixiv.net website."

### ISSUE THREAD

**Issue by jackie7841** [leoding86/webextension-pixiv-toolkit#235]
Today I used Pixiv Toolkit to download, but it didn't work. The console displayed an error like this. 
![image](https://github.com/leoding86/webextension-pixiv-toolkit/assets/146176005/fb189851-2225-4ff1-b2bc-ac992181e4ab)

I hope it will be fixed soon.

**Comment by bakukiku** [comment]
Same here.
I tried Chrome and Firefox extension.
The blue download tab doesn't show up on the comic.pixiv.net website.
I hope it will be fixed soon. Thank you!

**Comment by spiraldoll** [comment]
The toolbar no longer appears with manga posts: https://www.pixiv.net/artworks/115024197#manga
