### ISSUE TITLE
下载位置的问题

### ISSUE THREAD

**Issue by sdtptj** [leoding86/webextension-pixiv-toolkit#24]
他就是下不到我选的相对路径的文件夹里，就下到我浏览器的下载路径。。。。

**Comment by leoding86** [comment]
我没有重现你说的问题。能表述的更仔细些吗？比如提供一下你的设置。

**Comment by cwnevergg** [comment]
> 我没有重现你说的问题。能表述的更仔细些吗？比如提供一下你的设置。
sdtptj的问题应该是，浏览器本身设置了一个下载路径，假设为路径A，然后sdtptj使用了插件接管下载，设置保存相对位置，假设为路径B。然后使用pixiv_toolkit进行下载，发现下载到了路径A而不是路径B。

**Comment by cwnevergg** [comment]
> 我没有重现你说的问题。能表述的更仔细些吗？比如提供一下你的设置。


sdtptj的问题应该是，浏览器本身设置了一个下载路径，假设为路径A，然后sdtptj使用了插件接管下载，设置保存相对位置，假设为路径B。然后使用pixiv_toolkit进行下载，发现下载到了路径A而不是路径B。

**Comment by sdtptj** [comment]
pixiv/
此位置将作为浏览器下载设置路径的后缀。例如, 浏览器下载地址设置为 "D:/downloads/" ，那么插件将会把文件保存到 "D:/downloads/pixiv/"
然而下到了我的浏览器下载路径里，不过无所谓了，好用

**Comment by leoding86** [comment]
如果你开启浏览器中的了每次询问下载位置的，会使得插件无法接管下载，这个是主要是在使用Chrome或者类似Chrome浏览器的一个问题。
