### ISSUE TITLE
[Request] Support unlisted illustrations

### ISSUE THREAD

**Issue by daniels1989** [leoding86/webextension-pixiv-toolkit#241]
Apparently it's possible to create unlisted illustrations on Pixiv (I don't know how) 

Examples:
https://www.pixiv.net/en/artworks/unlisted/eE3fTYaROT9IsZmep386
https://www.pixiv.net/en/artworks/unlisted/nCjrDVZfPsbM9lmz5kge

Basically exact same url format as a normal image, just instead of a numeric id it's "unlisted/random 20 characters"

Ajax endpoint uses the same format:
https://www.pixiv.net/ajax/illust/unlisted/eE3fTYaROT9IsZmep386
https://www.pixiv.net/ajax/illust/unlisted/nCjrDVZfPsbM9lmz5kge

Data returned is also the same

**Comment by leoding86** [comment]
@daniels1989 Is there any ugoira or manga or illustration which has multiple images in unlisted area?
