### ISSUE TITLE
FFMPEG 生成GIF 有亮斑/FFMPEG GIF with yellow ripples

### ISSUE THREAD

**Issue by recentcabbage** [leoding86/webextension-pixiv-toolkit#242]
PIXIV toolkit很好用，但是用FFMPEG生成的gif有亮斑；
参照https://zhuanlan.zhihu.com/p/585480111，为文件生成一个调试板后再生成GIF亮斑就消失了;
只需增加一个执行步骤就能大幅提升GIF质量，同时文件大小不变，希望作者能增加此功能

通过TOOLkit下载动图的jpg zip，我自己目前生成GIF使用的cmd命令是：
ffmpeg -i %06d.jpg -vf palettegen name.jpg
ffmpeg -i %06d.jpg -i name.jpg -lavfi paletteuse  -crf 18 -preset slow output5.gif

**Comment by Rt39** [comment]
以前我是通过先下载apng再转换成gif的，这两条可以合并成一条

```
ffmpeg.exe -i input.apng -vf -vf "split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" output.gif
```

不过我不确定它能不能直接用在zip文件上面

现在版本更新至6.1.0，我好像还是只能使用这种方法，先在网页端设置里面把FFmpeg custom convert command设置为
```
-f concat -i input.txt -plays 0 output.apng
```

再在本地进行转换为gif的操作

**Comment by leoding86** [comment]
我需要想想怎么配置这个命令
