### ISSUE TITLE
DO NOT WORK

### ISSUE THREAD

**Issue by NanaKuka** [leoding86/webextension-pixiv-toolkit#247]
<img width="325" alt="image" src="https://github.com/user-attachments/assets/1f5d1d60-15ff-4838-9af9-008b7ddbaf9a">

Permissions
{"origins":["*://*.fanbox.cc/*","*://*.pixiv.net/*","*://*.pximg.net/*","*://*.techorus-cdn.com/*","*://comic.pixiv.net/*","*://www.pixiv.net/*"],"permissions":["downloads","downloads.shelf","storage","tabs","unlimitedStorage","declarativeNetRequest","declarativeNetRequestFeedback"]}
设置
{"alwaysPack":false,"animationJsonFormat":0,"askDownloadSavedWork":true,"autoActivateDownloadPanel":false,"disableDownloadsShelf":false,"displayWorkTypeLabel":true,"downloadPackFiles":true,"downloadPanelPosition":"center","downloadPanelStyle":1,"downloadRelativeLocation":"","downloadSaveAs":false,"downloadTasksWhenDownloadingImages":3,"enableDownloadMetadata":false,"enableExtTakeOverDownloads":false,"enableExtend":false,"enableExtension":true,"enablePackUgoiraFramesInfo":true,"enablePtkSearch":true,"enableSaveDownloadHistory":1,"enableSaveVisitHistory":true,"enableWhenUnderSeconds":1,"extendDuration":3,"fanboxPostPageNumberLength":-2,"fanboxPostPageNumberStartWithOne":-2,"fanboxPostRenameImageRule":"p{pageNum}","fanboxPostRenameRule":"{id}_{title}/{pageNum}","featureKnown":false,"globalTaskPageNumberLength":0,"globalTaskPageNumberStartWithOne":0,"globalZipMultipleImages":0,"guideShowed":true,"illustRenameImageRule":"p{pageNum}","illustRenameRule":"{id}_{title}","illustrationCreateSubdirectory":1,"illustrationImageRenameFormat":"","illustrationKeepPageNumber":false,"illustrationPageNumberLength":-2,"illustrationPageNumberStartWithOne":-2,"illustrationRelativeLocation":"","illustrationRenameFormat":"","importantNoticeDisplayed":true,"language":"default","mangaImageRenameFormat":"","mangaPageNumberLength":-2,"mangaPageNumberStartWithOne":-2,"mangaPagesInChunk":99,"mangaRelativeLocation":"","mangaRenameFormat":"","mangaRenameImageRule":"p{pageNum}","mangaRenameRule":"{id}_{title}}","maxDownloadRecords":10000,"maxHistoryItems":10000,"maxProcessDownloadTasks":5,"multipleDownloadsGapTime":150,"notSaveNSFWWorkInHistory":false,"novelIncludeDescription":false,"novelRelativeLocation":"","novelRenameFormat":"","novelRenameRule":"{id}_{title}","pixivComicEpisodePageNumberLength":-2,"pixivComicEpisodePageNumberStartWithOne":-2,"pixivComicEpisodeRenameImageRule":"p{pageNum}","pixivComicEpisodeRenameRule":"{id}_{title}/{numberingTitle}_{workTitle}","pixivComicImageRenameFormat":"{id}_{title}_p{pageNum}","pixivComicPageNumberLength":-2,"pixivComicPageNumberStartWithOne":-2,"pixivComicRelativeLocation":"","pixivComicRenameFormat":"{id}_{title}","pixivComicRenameImageRule":"p{pageNum}","pixivComicRenameRule":"{id}_{title}/{pageNum}","showPixivOmina":true,"showReloadInPopup":true,"showUpdateChangeLog":true,"statIllustDownloaded":1,"statMangaDownloaded":0,"statNovelDownloaded":0,"statUgoiraDownloaded":0,"ugoiraConvertTool":"default","ugoiraCustomFFmpegCommand":"","ugoiraQuanlity":10,"ugoiraRelativeLocation":"","ugoiraRenameFormat":"","ugoiraRenameRule":"{id}_{title}","version":"6.0.0","visitHistoryType":"list","workCoverSize":1}

**Comment by NanaKuka** [comment]
![image](https://github.com/user-attachments/assets/659e69da-2b36-41c5-894b-f64b20ad459c)

**Comment by spiraldoll** [comment]
Same issue.

Pixiv Toolkit Next does not work. It cannot download anything because “the download manager can’t open”, which it didn’t need to before.

**Comment by Mizzjix** [comment]
Same issue, no idea whats going on. Is there any fix?

**Comment by tipoima** [comment]
I'd really prefer if previous version was left as a legacy one

**Comment by VremiaMira** [comment]
I join, the same problem, after the update

**Comment by berserker465** [comment]
Same issue :\

**Comment by Rivaliant** [comment]
Same, Have Download manager tab open
Shows it download, Doesn't save anywhere

Change it back, this Download Manager is absolutely unnecessary

**Comment by aaaammm336** [comment]
I just can't use it. Please let me use the old version

**Comment by MkWilp-boot** [comment]
reinstalling fixed it for me, now it works basically as described in the README

**Comment by ef1500** [comment]
Reinstalled. Works only when I have the download manager tab open. Kind of annoying.

**Comment by tipoima** [comment]
> Same, Have Download manager tab open Shows it download, Doesn't save anywhere
> 
> Change it back, this Download Manager is absolutely unnecessary

These changes are mostly to support Chrome's V3 update (you know, the famous "fuck you" update that nukes half the features in name of security (read: breaking adblockers))
Older versions will only work if you corrupt Chrome's updater (since it doesn't let you just disable updates like a normal program)

**Comment by alexmonroi** [comment]
holy shi... I thought it was a search engine problem, I uninstalled it and reinstalled it, no, it wasn't that, then I found out, the new update doesn't work, so I went and uninstalled it, and put the 5.5 extension, that one works normally.

Use the one that says: "More Crx Package Information (Old Version)" 😘

https://www.crx4chrome.com/crx/273355/

**Comment by Mizzjix** [comment]
> reinstalling fixed it for me, now it works basically as described in the README

Could you link me to the read me? I think that  may be helpful, because right now the extension is essentially useless after this update.

**Comment by alexmonroi** [comment]
Sure, this is it, you download it and then put it in Extensions in Chrome.

https://www.crx4chrome.com/go.php?p=273355&i=ajlcnbbeidbackfknkgknjefhmbngdnj&s=zsKEvLEMOiN8g&l=https%3A%2F%2Ff6.crx4chrome.com%2Fcrx.php%3Fi%3Dajlcnbbeidbackfknkgknjefhmbngdnj%26v%3D5.5.0

**Comment by Mizzjix** [comment]
> Sure, this is it, you download it and then put it in Extensions in Chrome.
> 
> https://www.crx4chrome.com/go.php?p=273355&i=ajlcnbbeidbackfknkgknjefhmbngdnj&s=zsKEvLEMOiN8g&l=https%3A%2F%2Ff6.crx4chrome.com%2Fcrx.php%3Fi%3Dajlcnbbeidbackfknkgknjefhmbngdnj%26v%3D5.5.0

Thanks...Is there a way to make the extension work for microsoft edge?

**Comment by awkwardusername** [comment]
i did not like this update at all. previous version was a no brainer to use.

**Comment by Mizzjix** [comment]
> Reinstalled. Works only when I have the download manager tab open. Kind of annoying.

I have the download manager open, it says its downloaded, but it doesn't actually freaking download.

**Comment by Mizzjix** [comment]
> Same, Have Download manager tab open Shows it download, Doesn't save anywhere
> 
> Change it back, this Download Manager is absolutely unnecessary

Yeah, how do you fix this? Even with the download manager open it doesn't actually save in downloads or anywhere. Its just in the download manager.

**Comment by Mizzjix** [comment]
I think I've managed to fix it...Not sure if I'm using the prior or current version.

Uninstalled and redownloaded it.

**Comment by spiraldoll** [comment]
The old version is still in [the releases section](https://github.com/leoding86/webextension-pixiv-toolkit/releases/tag/5.5.3).

Fortunately, .crx files are just .zip files without further encryption.

1. Download chrome.crx
2. Rename from .crx to .zip
3. Unzip
4. Edit this line in manifest.json: `"update_url" = "https://192.168.0.0"` (Or replace it with any URL, so that checking for updates fails)
5. Re-zip the edited contents
6. Rename that from .zip to .crx
7. In Chrome, open extension settings and enable developer mode
8. Select your newly created .crx file to install it

**Comment by V972** [comment]
> > The old version is still in [the releases section](https://github.com/leoding86/webextension-pixiv-toolkit/releases/tag/5.5.3).
> > Fortunately, .crx files are just .zip files without further encryption.
> > 
> > 1. Download chrome.crx
> > 2. Rename from .crx to .zip
> > 3. Unzip
> > 4. Edit this line in manifest.json: `"update_url" = "https://192.168.0.0"` (Or replace it with any URL, so that checking for updates fails)
> > 5. Re-zip the edited contents
> > 6. Rename that from .zip to .crx
> > 7. In Chrome, open extension settings and enable developer mode
> > 8. Select your newly created .crx file to install it
> 
> Thanks. I was close to figuring this out initially (renaming to zip.) For me, I had to leave it unpacked and not re-zipped for this to work for me.

Both didn't work for me unfortunately.
Editing manifest in unzipped leads to "archive is damaged" error when saving while unzipping-editing-rezipping leads to import error in Chrom saying Extention header is missing

**Comment by spiraldoll** [comment]
> > > The old version is still in [the releases section](https://github.com/leoding86/webextension-pixiv-toolkit/releases/tag/5.5.3).
> > > Fortunately, .crx files are just .zip files without further encryption.
> > > 
> > > 1. Download chrome.crx
> > > 2. Rename from .crx to .zip
> > > 3. Unzip
> > > 4. Edit this line in manifest.json: `"update_url" = "https://192.168.0.0"` (Or replace it with any URL, so that checking for updates fails)
> > > 5. Re-zip the edited contents
> > > 6. Rename that from .zip to .crx
> > > 7. In Chrome, open extension settings and enable developer mode
> > > 8. Select your newly created .crx file to install it
> > 
> > 
> > Thanks. I was close to figuring this out initially (renaming to zip.) For me, I had to leave it unpacked and not re-zipped for this to work for me.
> 
> Both didn't work for me unfortunately. Editing manifest in unzipped leads to "archive is damaged" error when saving while unzipping-editing-rezipping leads to import error in Chrom saying Extention header is missing

Maybe your version of Chrome no longer accepts ManifestV2 extensions, and Pixiv Toolkit v5 will only work on a fork that hasn't dropped support for it.

**Comment by V972** [comment]
> > > > The old version is still in [the releases section](https://github.com/leoding86/webextension-pixiv-toolkit/releases/tag/5.5.3).
> > > > Fortunately, .crx files are just .zip files without further encryption.
> > > > 
> > > > 1. Download chrome.crx
> > > > 2. Rename from .crx to .zip
> > > > 3. Unzip
> > > > 4. Edit this line in manifest.json: `"update_url" = "https://192.168.0.0"` (Or replace it with any URL, so that checking for updates fails)
> > > > 5. Re-zip the edited contents
> > > > 6. Rename that from .zip to .crx
> > > > 7. In Chrome, open extension settings and enable developer mode
> > > > 8. Select your newly created .crx file to install it
> > > 
> > > 
> > > Thanks. I was close to figuring this out initially (renaming to zip.) For me, I had to leave it unpacked and not re-zipped for this to work for me.
> > 
> > 
> > Both didn't work for me unfortunately. Editing manifest in unzipped leads to "archive is damaged" error when saving while unzipping-editing-rezipping leads to import error in Chrom saying Extention header is missing
> 
> Maybe your version of Chrome no longer accepts ManifestV2 extensions, and Pixiv Toolkit v5 will only work on a fork that hasn't dropped support for it.

When I install unmodified PT v5, it installs successfully.
But the modified one.
Oh well.

**Comment by leoding86** [comment]
Please try the latest version which fixed some bugs and bring old download mode back.
