### ISSUE TITLE
v3.7.2 Rename Format

### ISSUE THREAD

**Issue by housenpineapple** [leoding86/webextension-pixiv-toolkit#25]
v3.7.2
Remove page number in filename when downloading illustation has only one image

but my rename format is {title}({id}_p{pageNum})
now i have to add filename "0"....
can add original filename? or add other tag like {originId}
example : {tag}=79012732_p0.jpg

**Comment by leoding86** [comment]
I'll improve the logic for removing the "pageNum".

What is {originId} mean? Do you mean the origin filename?

**Comment by housenpineapple** [comment]
yes  i mean origin filename
本來是希望{id}能像原始檔名一樣(ex.79012732_p0)
或者是新增新的標籤來代表原始檔名 new tag like {originId}

**Comment by leoding86** [comment]
你可以使用{id}_p0的规则来实现这个需求，3.7.3添加了设置可以在插画只有一张图片的时候也保留页码参数（计划今天发布）。

**Comment by housenpineapple** [comment]
對XD 但考慮到多張的情形 不能寫死成{id}_p0
感謝您今天將發布版本
