### ISSUE TITLE
每次保存都需要打开下载管理器

### ISSUE THREAD

**Issue by Fillair19** [leoding86/webextension-pixiv-toolkit#250]
**描述错误**
下载前需要打开管理器，多了一步没有必要的操作，非常难受
每个作品都保存到单独的文件夹，非常难受
无法设置不更新，换老版本也没用

**预期行为**
取消必须打开下载管理器才能进行下载的必要性
保存时可以保存到上一次保存的文件夹内
可以在设置中选择不更新版本

**浏览器以及版本（请填写以下信息）：**
  - Chrome 127.0.6533.99

**Comment by hubohuang** [comment]
我也是这样 每次下载图片都会弹窗提醒我没有打开下载管理器,让我从设置里面打开才能进行下载.
非常麻烦,我只是偶尔想保存一些图片,没有长时间把下载管理器挂在后台的必要.
希望原本的当前页面下载功能作为一个可选项回归到设置中以供选择.

**Comment by Fuxuanmylove** [comment]
问一下各位大佬，我现在甚至没法在本地找到已下载的图片，连文件夹都找不着

**Comment by Hydrapony** [comment]
另外就是下载管理器跟其他下载插件冲突了（例如Chrono），下载的文件标题为乱码

**Comment by leoding86** [comment]
最新版添加了旧的下载模式，不过已发布的版本还存在些许问题，可以在release页面下载最新的测试版。
