### ISSUE TITLE
"FFmpeg custom convert" no longer available in 6.0

### ISSUE THREAD

**Issue by tychoid** [leoding86/webextension-pixiv-toolkit#251]
Ugoira that should be .webp is downloaded as .zip instead.

![image](https://github.com/user-attachments/assets/83287aac-0a03-44c3-ba14-a5511efb5237)

![image](https://github.com/user-attachments/assets/42fe39ff-86a0-4c82-920c-bbfe0898403e)

![image](https://github.com/user-attachments/assets/a2e86ccd-5f05-409d-99a2-8511aba7e6bb)

![image](https://github.com/user-attachments/assets/c28c3a28-24fa-4f13-92e3-02b2589bd407)

I know you've got a lot of work ahead of you since 6.0.  Good luck!

**Comment by leoding86** [comment]
@tychoid The setting should be like this `-f concat -i input.txt -vf format=yuv420p -vcodec libwebp -lossless 0 -q:v 80 -loop 0 output.webp`. But there is a bug that the extension of the saved file become `txt`, I'll fixed it in next version.
