### ISSUE TITLE
pixiv omina download button is missing

### ISSUE THREAD

**Issue by resolutedreamer** [leoding86/webextension-pixiv-toolkit#253]
Previously, there used to be a download with pixiv-omina button, but now it's not appearing anymore
https://github.com/leoding86/pixiv-omina

**Comment by leoding86** [comment]
Yes, I remove it because I don't have time to maintain Pixiv Omina project.

I really don't know someone still using it. I add it back in next version if you can wait.

**Comment by resolutedreamer** [comment]
Oh, well, I have been making good use of it, especially the ability to move the output into sub folders using the different rename placeholders depending on the type of Pixiv work being saved.

**Comment by resolutedreamer** [comment]
I saw that you marked this issue as closed, and I can confirm that this is working for me.
https://github.com/leoding86/webextension-pixiv-toolkit/releases/tag/6.3.2-beta
Thank you very much!
