### ISSUE TITLE
改回舊版看這邊!

### ISSUE THREAD

**Issue by KeineKuni** [leoding86/webextension-pixiv-toolkit#254]
1. 先把設置跟紀錄導出備份
2. 去版本頁面載5.5.3舊版
3. 把6.0移除 安裝5.5.3舊版
4. 去以下路徑
    C:\使用者\(你的使用者名稱)\AppData\Local\Google\Chrome\User Data\Default\Extensions\ajlcnbbeidbackfknkgknjefhmbngdnj
    裡面會有個5.5.3_0子資料夾 打開manifest.json
    把這一行 "update_url":
    後面網址隨便改掉 例如 "https://localhost", "https://nmsl.sb", 之類
5. 右鍵ajlcnbbeidbackfknkgknjefhmbngdnj資料夾-內容-安全性
    把所有群組或使用者名稱的 "列出資料夾內容" 跟 "寫入 都改成拒絕

祝作者腦子被門夾壞早點恢復正常

**Comment by leoding86** [comment]
由于浏览器的原因，旧版本最终还是会停止支持。目前6.3.0-beta添加了经典下载模式的支持，虽然和旧版还是有一定区别，但是会持续优化。
