### ISSUE TITLE
近况说明以及后续计划

### ISSUE THREAD

**Issue by leoding86** [leoding86/webextension-pixiv-toolkit#255]
介于新版本的体验问题，感觉我需要做一点必要的说明。

1. 关于下载任务管理器的存在。

这个主要是为了解决ffmpeg-wasm的工作问题，由于manifest v3的策略问题导致wasm在内容页面中的工作存在问题，而ffmpeg可以有效解决gifjs只能单线程工作导致的CPU单个核心占用率过高的问题，并且ffmpeg在灵活性方面也远高于其他库。因此才实现了下载管理器来统一管理所有下载任务简化任务的维护。但是目前新建任务流程确实很复杂并且内容页中没有下载进度提示确实比较影响体验。6.2.0版本（已在审核）简化了新建任务的流程并且在内容页添加了下载进度，但这并不是最终解决方案；

2. 关于浏览历史的问题。

这个主要是前期规划存在问题，由于处理manifest v3的时间比较晚且比较仓促，没有提供一个窗口期来让用户备份历史记录并在新版本中进行还原（为了简化此模块更换了库），同时对于manifest v3的worker service理解也存在点问题，以为其不再支持持久化存储，就将存储功能移到了options page中导致现在体验相当不好。

3. 后续计划

主要分为两点：
- 一是尝试提供在内容页进行任务下载的方法，还原旧的下载体验，前提是能解决wasm在内容页工作；
- 二是优化历史记录，使用worker service在管理持久化存储。

4. 如果有什么其他建议可以在此issue中提出。感谢大家的耐心。

**Comment by kongokawaii** [comment]
现在连东西下载到哪里都找不到，这个路径功能完全不可用

**Comment by KeineKuni** [comment]
新版最讓人火大的bug
1.無論設定怎麼改 下載的檔名都是亂碼
2.一旦點了下載 就算跳出路徑視窗後取消 根本沒載到電腦裡也會被紀錄 就無法再次下載 到底為什麼只能載一次

**Comment by YOUNG-YAYA** [comment]
下载的每个作品都会单独保存到一个文件夹，如果我下载50张图，它就会建立50个文件夹....这个问题能解决一下吗？希望回到旧版那样所有文件保存到一个路径，不要自己新建文件夹，或者增加一个开关，让用户自行决定是否启用。

**Comment by leoding86** [comment]
@YOUNG-YAYA 能否将你的配置提供一下？

**Comment by leoding86** [comment]
> 介于新版本的体验问题，感觉我需要做一点必要的说明。
> 
> 1. 关于下载任务管理器的存在。
> 
> 这个主要是为了解决ffmpeg-wasm的工作问题，由于manifest v3的策略问题导致wasm在内容页面中的工作存在问题，而ffmpeg可以有效解决gifjs只能单线程工作导致的CPU单个核心占用率过高的问题，并且ffmpeg在灵活性方面也远高于其他库。因此才实现了下载管理器来统一管理所有下载任务简化任务的维护。但是目前新建任务流程确实很复杂并且内容页中没有下载进度提示确实比较影响体验。6.2.0版本（已在审核）简化了新建任务的流程并且在内容页添加了下载进度，但这并不是最终解决方案；
> 
> 2. 关于浏览历史的问题。
> 
> 这个主要是前期规划存在问题，由于处理manifest v3的时间比较晚且比较仓促，没有提供一个窗口期来让用户备份历史记录并在新版本中进行还原（为了简化此模块更换了库），同时对于manifest v3的worker service理解也存在点问题，以为其不再支持持久化存储，就将存储功能移到了options page中导致现在体验相当不好。
> 
> 3. 后续计划
> 
> 主要分为两点：
> 
> * 一是尝试提供在内容页进行任务下载的方法，还原旧的下载体验，前提是能解决wasm在内容页工作；
> * 二是优化历史记录，使用worker service在管理持久化存储。
> 
> 4. 如果有什么其他建议可以在此issue中提出。感谢大家的耐心。

最新进度：
1. 浏览记录可以通过worker service来操作，计划下个版本实现；
2. 关于ffmpeg，在内容页中工作基本是不可能的了，因为manifest v3下没有办法重写当前页面的响应头导致不能启用cross-origin isolation，也就无法启用必须的 SharedArrayBuffer。在考虑重新使用gifjs（生成gif）和whammy（生成webm）。🤔

**Comment by YOUNG-YAYA** [comment]
> @YOUNG-YAYA您的配置能否提供一下？

这和我的配置或设置没有关系，是6.0新版本更改了保存图片的方式，这是很多人都反映的问题，Chrome 应用商店已经很多人反映这个问题了，就是下载图片时会自动新建文件夹去保存图片，而设置里无法更改这一设定，虽然这个功能有一定好处，可以更好更有条理的分类，但是现在这样强制新建文件夹会很困扰，如果加一个开关选项让用户可以灵活开关这一功能就好了

**Comment by leoding86** [comment]
最新进度：

6.3.0-beta版本新增了经典下载模式的支持，同时新增了控制下载目录生成的选项。
