### ISSUE TITLE
下载每张图片都会单独生成一个文件夹

### ISSUE THREAD

**Issue by ghghjkjklo** [leoding86/webextension-pixiv-toolkit#256]
为啥要默认生成这么多文件夹？能否改回旧版？

**Comment by YOUNG-YAYA** [comment]
我也被这个功能困扰死了，这个功能适用于那些AI画师，每个作品页面有100、200张图片的那种画师，这种情况下单独生成文件夹还可以，是很好的功能，但是除此之外的常规情况下，每个作品都单独生成一个文件夹很不好，最好的办法是增加一个开关选项，用户根据自己的需要去自行开关。

**Comment by leoding86** [comment]
可以尝试下6.3.0-beta，新增了控制目录生成的选项。不过需要使用开发模式安装。

**Comment by FZpotato** [comment]
我下载的每一个都会生成一个压缩包，就算是单图也会是压缩包（）

**Comment by leoding86** [comment]
@FZpotato 目前打开打包模式是这样的行为，计划下个版本会添加选项控制。

**Comment by leoding86** [comment]
@ghghjkjklo 6.3.1新增了选项可以控制目录的生成。
