### ISSUE TITLE
Rename file doesn't work

### ISSUE THREAD

**Issue by nemesiscompletion** [leoding86/webextension-pixiv-toolkit#258]
**Describe the bug**
I'd like the downloaded pics to have same name as when I'd download them manually by saving the images with right click
So, I wanted to download them with ID and page number on each files
However, it's keep downloading files with random names like this
0fffc225-afaa-49f1-817c-0610dc1fe28a
f9e1f493-4869-4421-a082-8f633afa824b
06b18c0b-8307-4cf5-bf27-7d3dd3347f20
981508af-1871-4344-930a-4e06511514e5

**Expected behavior**
The file name has to show ID for the images and page number, just like the file name that shows if I'd manually download them

**Example work from Pixiv**
For example, if I'm to download first image from this page
https://www.pixiv.net/artworks/39602552
The file name is supposed to be 39602552_p0.jpg
However, when I use the application, the file name appears like this 656cff7e-4323-4c01-9732-9931db60289a.jpg

**Screenshots**
Here's example for both, first one is manually downloaded
Second one is downloaded by application
![39602552_p0](https://github.com/user-attachments/assets/feb3bf44-f629-4e0a-b31f-6fa39553eabc)
![656cff7e-4323-4c01-9732-9931db60289a](https://github.com/user-attachments/assets/6edcdefa-0f08-4da4-b6f0-c9eb405bd55c)
![20240815_033748](https://github.com/user-attachments/assets/71ba4e12-81f3-47d2-81e7-8798bb66dc15)

**Browser and Version (please complete the following information):**
Chrome 127.0.6533.101

**Settings of extension**
[pixiv_toolkit_settings-1723707537702.json](https://github.com/user-attachments/files/16622624/pixiv_toolkit_settings-1723707537702.json)

**Additional context**
I tried changing rename settings but it just keep shows some random names

**Comment by leoding86** [comment]
Could you provide the extension version?

**Comment by leoding86** [comment]
@nemesiscompletion I can't reproduce the problem, need further information.
![Snipaste_2024-08-16_23-10-54](https://github.com/user-attachments/assets/cb170599-0fab-412e-b889-416f3aaf0ec6)
![Snipaste_2024-08-16_23-12-00](https://github.com/user-attachments/assets/883ce075-0ef7-462d-8923-40d55c3fa9a4)
![Snipaste_2024-08-16_23-12-08](https://github.com/user-attachments/assets/99119c38-6aee-4367-a4b5-1bdd00bc6e05)

**Comment by leoding86** [comment]
@nemesiscompletion I tested with different settings, nothing wrong happened.
![Snipaste_2024-08-16_23-10-54](https://github.com/user-attachments/assets/dba6f23f-d0bc-454a-872c-576a3cfabe4a)
![Snipaste_2024-08-17_00-31-07](https://github.com/user-attachments/assets/d7674e01-3bf8-4c75-8a1d-64cc4a3acca1)

**Comment by nemesiscompletion** [comment]
I'm using this version 6.3.1 and settings are like this at the moment
![20240816_133408](https://github.com/user-attachments/assets/c8d11151-9dc8-453d-87ff-4b9d80283589)
![20240816_133422](https://github.com/user-attachments/assets/ae450d2c-3550-4d04-aca5-188691686f5a)

I'm still getting random names for the pics like this
![20240816_133716](https://github.com/user-attachments/assets/13e7b56a-5cdf-4bcd-9beb-ec9e3513e9ef)
Also, even for the same pics, it changes names randomly every time I download them

**Comment by DGCO** [comment]
I encountered the same issue, it also packs everything into a zipped file even if there is only one image to be downloaded. And it is not identifying downloaded images now.

**Comment by leoding86** [comment]
The problem is I can't repro this issue. I tested in Chrome and Edge, the renaming is working fine.🤔

**Comment by DDDDDuang** [comment]
我这边在6.0更新后也遇到了相同的问题，之前重命名是可以正常工作的。
不过我尝试关闭了Chrono下载管理器之后可以正常重命名下载了，可能是这两个插件之间某些功能发生了冲突。

**Comment by Pamlau** [comment]
same problem here

**Comment by DGCO** [comment]
> The problem is I can't repro this issue. I tested in Chrome and Edge, the renaming is working fine.🤔

I have an assumption, maybe this is a problem caused by having multiple extensions that have the rename permission. I have other image downloaders on my Chrome, is that possible to check on that?

In this example [https://www.pixiv.net/artworks/39602552] I will get a random name zip file and normal filename inside the zip file like p0 - p5.

**Comment by leoding86** [comment]
@DGCO Could you provide another extension you use?

**Comment by leoding86** [comment]
@DDDDDuang 这个[Chrono下载管理器](https://chromewebstore.google.com/detail/mciiogijehkdemklbdcbfkefimifhecn)？如果是的我可以先试试能不能浮现问题。

**Comment by SWN-002** [comment]
回報一下，我沒有安裝上述的Chrono下載管理器，也將我所有可能與下載管理有關的擴充(僅安裝Free Download Manager以及Down Them All)移除或停用，問題依舊

**Comment by DDDDDuang** [comment]
> @DDDDDuang 这个[Chrono下载管理器](https://chromewebstore.google.com/detail/mciiogijehkdemklbdcbfkefimifhecn)？如果是的我可以先试试能不能浮现问题。

是的，我禁用插件之后重命名可以正常工作

**Comment by leoding86** [comment]
@DDDDDuang @SWN-002 刚才看了下文档，可能是`chrome.downloads.onDeterminingFilename`这个接口调用抢占的问题。当前插件并没有调用此接口，目前没有完美的办法来解决，如果安装的其他扩展调用此接口的优先级更高那么就没有任何办法复写名称。我先尝试处理下。

技术细节在[这里](https://developer.chrome.com/docs/extensions/reference/api/downloads#event-onDeterminingFilename)

**Comment by DGCO** [comment]
> @DGCO Could you provide another extension you use?

Sure. 
[Imageye](https://chromewebstore.google.com/detail/agionbommeaifngbhincahgmoflcikhm)
[圖片助手(ImageAssistant) 批量圖片下載器](https://chromewebstore.google.com/detail/dbjbempljhcmhlfpfacalomonjpalpko)
[Image Downloader](https://chromewebstore.google.com/detail/cnpniohnfphhjihaiiggeabnkjhpaldj)
