### ISSUE TITLE
文件下载打包好后内部文件名完全是乱的

### ISSUE THREAD

**Issue by captain-wulidun** [leoding86/webextension-pixiv-toolkit#260]
在此版本中，下载完成在打包成ZIP文件并解压之后，解压出来的文件顺序完全是乱的，感觉是没有顺序下载的问题。此前版本没有出现这个问题。
并且在设置fanbox的命名规则时无法保存。
请解决此问题！

**Comment by leoding86** [comment]
@captain-wulidun  fanbox最大的问题是我没有订阅任何作者，只能用免费的做测试。我先试试复现这个问题😕

**Comment by captain-wulidun** [comment]
![微信图片_20240816234208](https://github.com/user-attachments/assets/4c985ba3-bddd-47ed-bc04-c6feb56ff133)
![微信图片_20240816234228](https://github.com/user-attachments/assets/ad8a788c-6f20-45d2-a6e0-2b482f5eaa20)
![微信图片_20240816234326](https://github.com/user-attachments/assets/a9ff36bd-7737-48e4-bf89-b6cb8387378f)
这是pixiv 绘画保存的问题，请查看！

**Comment by captain-wulidun** [comment]
@leoding86

**Comment by leoding86** [comment]
@captain-wulidun 我确实发现了些问题，我再看看你说的这个。

**Comment by leoding86** [comment]
> @captain-wulidun 我确实发现了些问题，我再看看你说的这个。

漫画和绘图使用了和你相同的配置，并没有复现出现压缩包内文件顺序不对的问题😕
[https://www.pixiv.net/en/artworks/101671914](https://www.pixiv.net/en/artworks/101671914)
![Snipaste_2024-08-17_00-11-18](https://github.com/user-attachments/assets/26ad833f-9497-487b-9b5c-e9d5b0dc5499)
[https://www.pixiv.net/en/artworks/121449744](https://www.pixiv.net/en/artworks/121449744)
![Snipaste_2024-08-17_00-15-29](https://github.com/user-attachments/assets/5d6000c2-265a-4068-a591-b79563849f26)

**Comment by captain-wulidun** [comment]
> > @captain-wulidun 我确实发现了些问题，我再看看你说的这个。
> 
> 漫画和绘图使用了和你相同的配置，并没有复现出现压缩包内文件顺序不对的问题😕 https://www.pixiv.net/en/artworks/101671914 ![Snipaste_2024-08-17_00-11-18](https://private-user-images.githubusercontent.com/7626859/358646311-26ad833f-9497-487b-9b5c-e9d5b0dc5499.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MjkyNDIsIm5iZiI6MTcyMzgyODk0MiwicGF0aCI6Ii83NjI2ODU5LzM1ODY0NjMxMS0yNmFkODMzZi05NDk3LTQ4N2ItOWI1Yy1lOWQ1YjBkYzU0OTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMTcyMjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDhiNGY1NDYzMTI1NDJmNjJmNWYxODc3NTU0YmIyMDQ5NGUzMGI0ZDI1NzQ2M2NlOWNlMDNkYzcwZjE1OTE2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YXCd2GnTufiCJc5kHj0R7aQHFLAXE9FYnQAiRkZw-9E) https://www.pixiv.net/en/artworks/121449744 ![Snipaste_2024-08-17_00-15-29](https://private-user-images.githubusercontent.com/7626859/358646322-5d6000c2-265a-4068-a591-b79563849f26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MjkyNDIsIm5iZiI6MTcyMzgyODk0MiwicGF0aCI6Ii83NjI2ODU5LzM1ODY0NjMyMi01ZDYwMDBjMi0yNjVhLTQwNjgtYTU5MS1iNzk1NjM4NDlmMjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMTcyMjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGU0NGJmOWE5OGMxNTczYzExMWYxYTViNzY1NjFhOGQzNzAyN2VkZDk4YmM5NjU1MjNjZjdmNWEzNjdmYTc0ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HUyXundTnrCYYZUtXVEevkBlkr8GYn1htuI0YWmEeb4)

请问您是用的什么排序方式？我一直用的都是按照修改时间进行排序，刚才我又试了一遍，发现在打开压缩包后，在压缩包内文件按照修改时间排序的顺序就是乱的，在之前的版本中没有出现过此问题。

**Comment by leoding86** [comment]
@captain-wulidun 你需要下载后的文件在时间上也是一致的？这个我倒没有注意过。

**Comment by captain-wulidun** [comment]
> @captain-wulidun 你需要下载后的文件在时间上也是一致的？这个我倒没有注意过。

@leoding86 主要是原来的版本根本没有出现这个问题，排序方式我就一直没有改，现在版本更新之后突然之间顺序错乱感觉非常头疼
