### ISSUE TITLE
Downloaded file's names are being randomized

### ISSUE THREAD

**Issue by osy999** [leoding86/webextension-pixiv-toolkit#262]
**Expected behavior**
![image](https://github.com/user-attachments/assets/13d02587-6c41-4564-9fcc-50feb1e15fda)

**Example work from Pixiv**
https://www.pixiv.net/en/artworks/121561484

**Screenshots**
![image](https://github.com/user-attachments/assets/bc9579cb-070a-4626-ba00-524b2f24d215)
![image](https://github.com/user-attachments/assets/588fa1cf-475d-437d-9a81-437c95f79a26)

**Browser and Version (please complete the following information):**
Chrome Version 127.0.6533.120 (Official Build) (64-bit)

**Settings of extension**
{"_download_manager_tab":{"tabId":976929586,"windowId":976929110},"alwaysPack":false,"animationJsonFormat":1,"askDownloadSavedWork":true,"autoActivateDownloadPanel":true,"combinWRRuleAndIRRuleWhenDontCreateWorkFolder":0,"disableDownloadsShelf":false,"displayWorkTypeLabel":true,"dontCreateWorkFolder":0,"downloadMode":1,"downloadPackFiles":true,"downloadPanelPosition":"center","downloadPanelStyle":1,"downloadRelativeLocation":"","downloadSaveAs":false,"downloadTasksWhenDownloadingImages":3,"enableDownloadMetadata":true,"enableExtTakeOverDownloads":false,"enableExtend":false,"enableExtension":true,"enablePackUgoiraFramesInfo":true,"enablePtkSearch":true,"enableSaveDownloadHistory":1,"enableSaveVisitHistory":true,"enableWhenUnderSeconds":1,"extendDuration":3,"fanboxPostPageNumberLength":-2,"fanboxPostPageNumberStartWithOne":-2,"fanboxPostRenameImageRule":"p{pageNum}","fanboxPostRenameRule":"{id}_{title}/{pageNum}","featureKnown":false,"globalTaskPageNumberLength":-1,"globalTaskPageNumberStartWithOne":1,"globalZipMultipleImages":0,"guideShowed":true,"illustRenameImageRule":"p{pageNum}","illustRenameRule":"{id}_{title}","illustrationCreateSubdirectory":1,"illustrationImageRenameFormat":"","illustrationKeepPageNumber":false,"illustrationPageNumberLength":-2,"illustrationPageNumberStartWithOne":-2,"illustrationRelativeLocation":"","illustrationRenameFormat":"","importantNoticeDisplayed":true,"language":"default","mangaImageRenameFormat":"","mangaPageNumberLength":-2,"mangaPageNumberStartWithOne":-2,"mangaPagesInChunk":99,"mangaRelativeLocation":"","mangaRenameFormat":"","mangaRenameImageRule":"p{pageNum}","mangaRenameRule":"{id}_{title}}","maxDownloadRecords":10000,"maxHistoryItems":10000,"maxProcessDownloadTasks":3,"multipleDownloadsGapTime":150,"notSaveNSFWWorkInHistory":false,"novelIncludeDescription":false,"novelRelativeLocation":"","novelRenameFormat":"","novelRenameRule":"{id}_{title}","pixivComicEpisodePageNumberLength":-2,"pixivComicEpisodePageNumberStartWithOne":-2,"pixivComicEpisodeRenameImageRule":"p{pageNum}","pixivComicEpisodeRenameRule":"{id}_{title}/{numberingTitle}_{workTitle}","pixivComicImageRenameFormat":"{id}_{title}_p{pageNum}","pixivComicPageNumberLength":-2,"pixivComicPageNumberStartWithOne":-2,"pixivComicRelativeLocation":"","pixivComicRenameFormat":"{id}_{title}","pixivComicRenameImageRule":"p{pageNum}","pixivComicRenameRule":"{id}_{title}/{pageNum}","showPixivOmina":true,"showReloadInPopup":false,"showUpdateChangeLog":false,"statIllustDownloaded":1,"statMangaDownloaded":0,"statNovelDownloaded":0,"statUgoiraDownloaded":0,"ugoiraConvertTool":"default","ugoiraCustomFFmpegCommand":"","ugoiraFFmpegAPNGCliArgs":"-f concat -i input.txt -plays 0 output.apng","ugoiraFFmpegGIFCliArgs":"-f concat -i input.txt -plays 0 out.gif","ugoiraFFmpegMP4CliArgs":"-f concat -i input.txt -safe 0 -c copy output.mp4","ugoiraFFmpegWEBMCliArgs":"-f concat -i input.txt -safe 0 output.webm","ugoiraQuanlity":10,"ugoiraRelativeLocation":"","ugoiraRenameFormat":"","ugoiraRenameRule":"{id}_{title}","version":"6.0.0","visitHistoryType":"list","workCoverSize":1}

**Comment by leoding86** [comment]
related to #258
