### ISSUE TITLE
Chrome disabled this extension due to new permissions of readnig browsing history and blocking content on any page.

### ISSUE THREAD

**Issue by Xdminsy** [leoding86/webextension-pixiv-toolkit#263]
I know that chrome disable extensions when they ask for new permissions, not meaning they are malicious.

These four new permissions are requested.
- Read and change your data on comic.pixiv.net
- Read your browsing history
- Block content on any page
- Manage your downloads

While I can understand and accept the first and fourth, the middle two look very suspicious at first glance, usually such things happen when an extension gets sold and updated with a malicious one, I've experienced some of such extensions.

But later I found that this is an open-source extension and provides the link to this repo on Chrome store page,  it's great so I can open an issue to confirm.

And I searched these phrases that the "block content on any page" is reported because of `declarativeNetRequest`, someone said that this can be replaced with `declarativeNetRequestWithHostAccess` to work only on host_permissions.

The browsing history is because of "tabs" permissions, it cannot view previous histories but is able to record new tabs when open so chrome warns this, while this extension only record pixiv histories I think and it is the feature.

So I see they're acceptable as this is an open-source extensions, appreciate your work :).

**Comment by leoding86** [comment]
@Xdminsy I think maybe I don't need `tabs` permission for doing stuff. I'll try remove it later.
