### ISSUE TITLE
Any changes in Download Task Settings of Fanbox are not applied

### ISSUE THREAD

**Issue by knackazzy** [leoding86/webextension-pixiv-toolkit#264]
**Describe the bug**
Any changes in Download Task Settings of Fanbox are not applied.

**Expected behavior**
Changes in fields in Download Task Settings of Fanbox ('Rename', 'Rename image in Fanbox Post', 'Page number start with 1', 'The length of page number') applied to downloading.

**Screenshots**
1. before making any changes
<img width="787" alt="1_before_change" src="https://github.com/user-attachments/assets/6f1f3dfb-9ea5-4324-80a0-97f80307c622">
2. right after changed
<img width="787" alt="2_after_change" src="https://github.com/user-attachments/assets/cbcc0bac-e647-457d-9003-3f8dc5a18769">
3.after re-open Pixiv Toolkit Next Settings page
<img width="787" alt="3_after_reopen" src="https://github.com/user-attachments/assets/03cad827-cab6-48ae-ba1d-4796402043fa">

**Browser and Version (please complete the following information):**
Google Chrome 127.0.6533.120（Official Build） （x86_64）
Pixiv Toolkit Next v6.3.1

**Settings of extension**
*export right after screenshots 2
[pixiv_toolkit_settings-1723865891635.json](https://github.com/user-attachments/files/16643266/pixiv_toolkit_settings-1723865891635.json)

**Additional context**
Changes in Download Task Settings of Global, Pixiv Ugoira, Pixiv Illustration and Pixiv Manga work.

**Comment by leoding86** [comment]
@knackazzy Fixed in 6.3.2-beta, will submit to Chrome Store for reviewing later.
