### ISSUE TITLE
【选择并下载】始终显示第一次打开该功能时的图片

### ISSUE THREAD

**Issue by kopision** [leoding86/webextension-pixiv-toolkit#266]
**描述错误**
当打开一个pixiv作品页面，点击【选择并下载】后，这时弹出的界面通常能正常显示当前作品的缩略图；然后在这个窗口内再点击其他作品（一次或数次），再点击【选择并下载】，这时弹出的界面显示的仍然是上一次打开的缩略图，之后再在这个页面内点击任何作品，这个界面都不会更新，始终显示第一次的缩略图，除非手动刷新网页。

**预期行为**
应该显示当前页面内图片的缩略图以供用户选择下载

**示例作品**
随意一个作品都可以复现。

**截图**
![image](https://github.com/user-attachments/assets/4bfb4166-4111-4d4c-bf50-ce3a8ac548b2)

**浏览器以及版本（请填写以下信息）：**
Microsoft Edge
版本 127.0.2651.105 (正式版本) (64 位)

**插件设置**
[pixiv_toolkit_settings-1724083952527.json](https://github.com/user-attachments/files/16662828/pixiv_toolkit_settings-1724083952527.json)

**其他内容**
无

**Comment by kopision** [comment]
改回经典下载之后正常了

**Comment by leoding86** [comment]
问题确认
