### ISSUE TITLE
在Microsoft Edge上自定義更名以及路徑功能失效

### ISSUE THREAD

**Issue by SWN-002** [leoding86/webextension-pixiv-toolkit#267]
**描述错误**
在setting中的自定義下載圖片、影片檔名格式，以及下載到位於Download路徑下指定路徑的功能在Microsoft Edge上全部失效，檔案只會用預設加密名稱下載至預設的下載資料夾中，用管理者權限開啟瀏覽器也一樣。

**预期行为**
照理來說按下下載按鍵後，檔案名稱應該是自動變更為在Setting中指定的格式(如{author} - {title} ({id}))儲存至預設下載路徑的指定路徑中(如Download\pixiv\)

**示例作品**
所有作品

**浏览器以及版本（请填写以下信息）：**
 Microsoft Edge Version 127.0.2651.105 (Official build) (64-bit)

**插件设置**
{"MangaPageNumberStartWithOne":false,"_download_manager_tab":{"tabId":1924939702,"windowId":1924939670},"alwaysPack":false,"animationJsonFormat":1,"askDownloadSavedWork":false,"autoActivateDownloadPanel":true,"disableDownloadsShelf":false,"displayWorkTypeLabel":true,"downloadMode":2,"downloadPackFiles":false,"downloadPanelPosition":"center","downloadPanelStyle":1,"downloadRelativeLocation":"Pictures/","downloadSaveAs":true,"downloadTasksWhenDownloadingImages":5,"enableDownloadMetadata":false,"enableExtTakeOverDownloads":true,"enableExtend":false,"enableExtension":true,"enablePackUgoiraFramesInfo":true,"enablePtkSearch":true,"enableSaveDownloadHistory":1,"enableSaveVisitHistory":true,"enableWhenUnderSeconds":1,"extendDuration":3,"fanboxPostPageNumberLength":-2,"fanboxPostPageNumberStartWithOne":-2,"fanboxPostRenameImageRule":"p{pageNum}","fanboxPostRenameRule":"{id}_{title}/{pageNum}","featureKnown":false,"globalTaskPageNumberLength":-1,"globalTaskPageNumberStartWithOne":0,"globalZipMultipleImages":0,"guideShowed":true,"illustRenameImageRule":"{author} - {title} ({id})","illustRenameRule":"Pictures/{author} - {title} ({id})","illustrationCreateSubdirectory":2,"illustrationImageRenameFormat":"{author} - {title} ({id})","illustrationKeepPageNumber":false,"illustrationPageNumberLength":-1,"illustrationPageNumberStartWithOne":0,"illustrationRelativeLocation":"Pictures/","illustrationRenameFormat":"{author} - {title} ({id})","importantNoticeDisplayed":true,"language":"default","mangaImageRenameFormat":"{author} - {title} ({id})","mangaPageNumberLength":-1,"mangaPageNumberStartWithOne":0,"mangaPagesInChunk":250,"mangaRelativeLocation":"Pictures/","mangaRenameFormat":"{author} - {title} ({id})","mangaRenameImageRule":"{author} - {title} ({id})","mangaRenameRule":"{author} - {title} ({id})","maxDownloadRecords":10000,"maxHistoryItems":10000,"maxProcessDownloadTasks":3,"multipleDownloadsGapTime":150,"notSaveNSFWWorkInHistory":true,"novelIncludeDescription":false,"novelRelativeLocation":"Pixiv/","novelRenameFormat":"{author} - {title} ({id})","novelRenameRule":"Pixiv/{author} - {title} ({id})","pixivComicEpisodePageNumberLength":-2,"pixivComicEpisodePageNumberStartWithOne":-2,"pixivComicEpisodeRenameImageRule":"p{pageNum}","pixivComicEpisodeRenameRule":"{id}_{title}","pixivComicImageRenameFormat":"{id}_{title}_p{pageNum}","pixivComicPageNumberLength":0,"pixivComicPageNumberStartWithOne":0,"pixivComicRelativeLocation":"Pixiv/","pixivComicRenameFormat":"{id}_{title}","pixivComicRenameImageRule":"p{pageNum}","pixivComicRenameRule":"{id}_{title}/{pageNum}","showPixivOmina":true,"showReloadInPopup":false,"showUpdateChangeLog":true,"statIllustDownloaded":6938,"statMangaDownloaded":89,"statNovelDownloaded":0,"statUgoiraDownloaded":0,"ugoiraConvertTool":"default","ugoiraCustomFFmpegCommand":"-f concat -i input.txt -safe 0 -c copy output.webm","ugoiraQuanlity":1,"ugoiraRelativeLocation":"Pictures/","ugoiraRenameFormat":"{author} - {title} ({id})","ugoiraRenameRule":"{author} - {title} ({id})","version":"6.0.0","visitHistoryType":"list","workCoverSize":3}

**其他内容**
這問題在FireFox上完全不會發生

**Comment by leoding86** [comment]
保存的图片是不是一串字符串，还是说可以重命名但是没有按照设置进行？

**Comment by SWN-002** [comment]
保存下來的圖片檔名是一串字串，而且不會存入指定的子資料夾中

**Comment by leoding86** [comment]
#258相关
