### ISSUE TITLE
创建作品文件夹与打包成zip功能没有正常运作

### ISSUE THREAD

**Issue by HansenLudwig** [leoding86/webextension-pixiv-toolkit#270]
**描述错误**
1. 选项：不创建作品文件夹（只对绘画和FanBox作品有效）
设为“只有一张图片”时，无论作品有几张图片都会建立文件夹。而且如果是多张图片，有时还会创建双层目录：[默认下载目录]\[作品名]\[作品名]\[文件名].jpg
2. 类似的，多张图片打包成ZIP文件设置，如果设置成启用，无论几张图片都会被打包

**预期行为**
单张图片时，不要创建新文件夹，不要打包。如果可以的话，每次提供下载目录选择应该在上次使用的目录，而不是每次都从默认目录开始。

**示例作品**
下载单张图片时被创建了新目录，且被打包
https://www.pixiv.net/artworks/120163636
下载多张图片时，创建了双层目录的情况
https://www.pixiv.net/artworks/117987821

**截图**
下载单张图片时被创建了新目录，且被打包
![image](https://github.com/user-attachments/assets/3f6ebc3c-f303-400a-af4d-b34204e84659)
发生问题时的设置
![image](https://github.com/user-attachments/assets/058bb9fe-122d-4b69-86ed-b49588de14a1)

下载多张图片时，创建了双层目录的情况
![image](https://github.com/user-attachments/assets/4c642e0a-035b-4a41-b151-2a2c0f0684ff)
下载多张图片时创建了双层目录时的设置：
![image](https://github.com/user-attachments/assets/d0fcd844-24fe-436b-a811-59f257f09cbe)

**浏览器以及版本（请填写以下信息）：**
 Chrome 版本 127.0.6533.120（正式版本） （64 位）

**插件设置**
你可以在设置页面导出插件设置。

**其他内容**
暂无

**Comment by leoding86** [comment]
@HansenLudwig 我需要你的配置来复现问题。关于创建文件夹的深度和重命名规则是有关系的，如果命名规则中有`/`则会创建文件夹。再就是默认下载目录通过插件实现不了，浏览器下载配置的优先级是最高的。
