### ISSUE TITLE
启用插件后，chrome本身的下载响应缓慢

### ISSUE THREAD

**Issue by Hydrapony** [leoding86/webextension-pixiv-toolkit#271]
**描述错误**
右键点击任意网络图片并选择图片另存为，chrome没有响应，大约15秒后跳出另存为对话框，期间若关闭chrome则会提示有文件正在下载是否确认关闭。重启浏览器或电脑都无效，禁用插件后恢复正常。

**浏览器以及版本（请填写以下信息）：**
Chrome 已是最新版本
版本 128.0.6613.85（正式版本） （64 位）

**Comment by hon-ele** [comment]
同样的问题。
猜测是[DownloadService](https://github.com/leoding86/webextension-pixiv-toolkit/blob/master/src/background/services/DownloadService.js)里API调用的问题(onDeterminingFilename)，但不确定。请作者查看一下。

**Comment by hon-ele** [comment]
> I had this problem as well.
> 
> It seems to be fixed now though.
> 
> I exported my settings. Uninstalled the addon. Reinstalled addon. Reimported settings.
> 
> Fixed!

Much thanks for providing the solution, gonna try it later.

**Comment by solo-nko** [comment]
I also had this issue. Saving things would cause the browser to hang for about 10 seconds or so, before proceeding. It didn't appear to be limited to images, any downloads would cause it. For example, exporting settings from the extension also caused a delay.

> I had this problem as well.
> 
> It seems to be fixed now though.
> 
> I exported my settings. Uninstalled the addon. Reinstalled addon. Reimported settings.
> 
> Fixed!

Following this fixed the issue.

I'm using Vivaldi 6.9.3447.37

**Comment by dyf19118** [comment]
same issue

**Comment by Invertex** [comment]
Yeah, the issues isn't fixed. Toggling the addon somehow gets rid of the issue temporarily, but it eventually comes back.
