### ISSUE TITLE
Pixiv Toolkit Not Working In Fanbox

### ISSUE THREAD

**Issue by Zhuo-Xing** [leoding86/webextension-pixiv-toolkit#277]
**描述错误**
Pixiv Toolkit Not Working In Fanbox,but working fine in pixiv.
**预期行为**
Download panel should be visible/present in the middle.

**示例作品**
https://www.fanbox.cc/@lambda/posts/7869008
It's the whole of fanbox in fact.Previously it worked fine.

**截图**
![Pixiv Not Working](https://github.com/user-attachments/assets/3c5f52db-3f26-4d50-9cf4-e3b1dd80564f)

**浏览器以及版本（请填写以下信息）：**
  Chrome, Version 128.0.6613.114 (Official Build) (64-bit)

**Comment by leoding86** [comment]
I think I know what's going on. Will fix it soon.
