### ISSUE TITLE
"Save As" window take's significantly longer to pop up

### ISSUE THREAD

**Issue by JohnSmith2007** [leoding86/webextension-pixiv-toolkit#278]
Title explains most of it. For unknown reasons, the extension (both the GitHub version & the Google Chrome version) are causing the "Save As" window to take significantly longer to pop up. It is also not remembering the last place something is downloaded to, and is defaulting to the "Downloads" folder on the main hard drive of anybody's PC.

**Expected behavior**
Literally the exact opposite of the main problem.

**Browser and Version (please complete the following information):**
 Opera GX - LVL 6 (core: 112.0.5197.104)

**Settings of extension**
N/A

**Additional context**
 On top of affecting Pixiv, it's also affecting other websites that allow users to download images via right clicking and selecting "Save As". This has been reported to be happening on multiple browsers, including, but not limited to;
- Google Chrome
- Mozilla Firefox
- Opera GX
- Microsoft Edge

**Comment by Rivaliant** [comment]
I can report that this is also happening to me

it effect's chrome as a whole as anything you attempt to Save As
 has a massive delay in the window popping up
 
 removing the Tookkit Extension makes the issue go away
 and it appears to come back after Using the download function on the toolkit
