### ISSUE TITLE
图片保存时间过长

### ISSUE THREAD

**Issue by ad2197** [leoding86/webextension-pixiv-toolkit#280]
**描述错误**
使用这个扩展程序时，点击按钮保存图片要等很长的时间才显示下载；
且影响到了非Pixiv的其他网站的图片的保存（如Twitter/X、Pinterest等）
这使得我无限次移除并重新安装这个扩展程序，移除后不存在这种情况，但安装后一段时间就又出现这种情况

**示例作品**
Pixiv 工具箱 Next

**浏览器以及版本（请填写以下信息）：
Google Chrome 128.0.6613.115

**Comment by ad2197** [comment]
跟#271的描述差不多
只是我受到的影响比较大

**Comment by leoding86** [comment]
#271 相关
