### ISSUE TITLE
360极速浏览器一旦开启工具箱就会导致所有网站的图片保存和下载有延迟

### ISSUE THREAD

**Issue by IABBI** [leoding86/webextension-pixiv-toolkit#282]
大概十几天前出现的情况，一旦开启工具箱，不管是右键保存图片还是所有的下载项目都会有10秒到30秒以上的延迟出现
关闭下载架后问题解决，但是工具箱又会自动打开下载架，选项不保存，
然后在pixiv上GIF不打包的选项既不生效也不保存

**Comment by IABBI** [comment]
退回到老版本5.5.3，现在一切正常
虽然下载架和允许扩展程序接管下载这两个选项都是灰的

**Comment by leoding86** [comment]
#271 相关
