### ISSUE TITLE
Cannot Locate the Metadata

### ISSUE THREAD

**Issue by Airborne2466** [leoding86/webextension-pixiv-toolkit#284]
**Describe the bug**
Could not find the metadata of the downloaded pixiv after downloading with "Download Metadata" selected.

**Expected behavior**

**Example work from Pixiv**
https://www.pixiv.net/en/artworks/122225579

**Screenshots**
<img width="802" alt="Screenshot 2024-09-11 at 1 53 40 AM" src="https://github.com/user-attachments/assets/9c846b6b-abcb-4db0-bf74-d3fe3f5375ee">
<img width="907" alt="Screenshot 2024-09-11 at 1 54 57 AM" src="https://github.com/user-attachments/assets/7a60a886-7427-4136-b12c-26821542711a">
<img width="759" alt="Screenshot 2024-09-11 at 1 56 18 AM" src="https://github.com/user-attachments/assets/8b10a2c2-ec61-4e4e-ad9a-597e184c67b0">

**Browser and Version (please complete the following information):**
 - Chrome, 6.3.2

**Settings of extension**
[pixiv_toolkit_settings-1726037895330.json](https://github.com/user-attachments/files/16959155/pixiv_toolkit_settings-1726037895330.json)

**Comment by leoding86** [comment]
Issue confirmed.
