### ISSUE TITLE
建议新增：倒序下载

### ISSUE THREAD

**Issue by guuzheg** [leoding86/webextension-pixiv-toolkit#285]
建议新增下载设置：在选择多张图片下载时，从{pageNum}数字最大的图片文件开始倒序下载

**Comment by leoding86** [comment]
我还是没有理解这个功能需要解决的问题或需要提升的体验。如果能更详细说明下会更好。

**Comment by guuzheg** [comment]
是的，这是我的小请求，以符合我的下载习惯。我希望在时间上，序号最大的图片是最早下载的。这样我可以选择使用“按修改时间倒序”来管理下载的文件

leoding86 ***@***.***> 于 2024年9月22日周日 上午10:52写道：
