### ISSUE TITLE
Using "Save Image As" on any page takes 10+ seconds for the box to appear

### ISSUE THREAD

**Issue by BlueDragonKaiser2** [leoding86/webextension-pixiv-toolkit#286]
When right clicking and choosing "Save Image As" normally it takes less than a second for the box to appear. However, recently when I have this extension activated,  it can take up to 10 seconds or more for it to appear. This isn't exclusive to Pixiv either, it's on any page which I find strange. I'm using Vivaldi 6.9.3447.44 (Stable channel) (64-bit) as my browser which uses Chromium.

Video of the issue:
https://u.pcloud.link/publink/show?code=XZrAWU0ZLEn5W5wcSmbliVI77BMKakhkwA9y

Settings:
[pixiv_toolkit_settings-1726537968695.json](https://github.com/user-attachments/files/17021917/pixiv_toolkit_settings-1726537968695.json)

**Comment by leoding86** [comment]
I can't reproduce the problem in version 6.4.1. Could you provide the version of the extension you use?

**Comment by leoding86** [comment]
relate to #271
