### ISSUE TITLE
小说下载重命名有时会失效

### ISSUE THREAD

**Issue by shanyuyulai1204** [leoding86/webextension-pixiv-toolkit#287]
**Describe the bug**
小说下载命名设置成了 
![renamerule](https://github.com/user-attachments/assets/405c4225-1cdf-4038-9646-16def2cd58b8)
有几天会正常，但有几天会变成“132bcfff-6fdf-4444-b2a6-2501815461c7”这样的格式
但是过几天又会突然正常一会
会如此反复出现如上情况
不确定是否是受我的VPN和运营商状态影响所导致的
Update:不只是小说，其他也会

**Example work from Pixiv**
例子（R18G警告）：小说https://www.pixiv.net/novel/show.php?id=22724244 ，按设置正常情况应该是“22724244_漫展千金失踪案_序章XXXX”这样的格式，下载时会变成“132bcfff-6fdf-4444-b2a6-2501815461c7”

**Browser and Version (please complete the following information):**
chrome 129.0.6668.58（正式版本） （64 位）
梯子用的是海豚湾的

**Additional context**
主要是会突然正常几天又突然不正常几天，我有点怀疑是不是我的网络运营商不稳定导致的

**Comment by leoding86** [comment]
保存文件的时候是存在类似的问题，是因为保存文件和获取文件名异步导致的。6.4.1时处理过一次，想问下你用的插件版本是多少？

**Comment by shanyuyulai1204** [comment]
我的版本就是v6.4.1 。我在chrome应用商店看到当下应用商店里的最新版本便是v6.4.1，显示更新日期为2024.09.12。是有新的版本我没同步吗？

**Comment by Hydrapony** [comment]
我也遇到了一样的问题。我使用的是经典下载模式，因为这个模式跟chrono插件不冲突，之前没有问题，但现在也出现了重命名乱码问题，停用chrono插件就可以了。另外开启插件会导致原另存为框延迟弹出的问题也没有解决，现在几乎已经无法正常使用这个插件了。

**Comment by leoding86** [comment]
等6.4.3发布了可以更新试试，应该不会再有保存延迟和重命名异常的问题了（希望🙃）
