### ISSUE TITLE
无法更改设置选项 “当...不创建作品文件夹”

### ISSUE THREAD

**Issue by BenmiaoZ** [leoding86/webextension-pixiv-toolkit#288]
**描述错误**
选项 “当...不创建作品文件夹” 无法被修改
选项默认为 “总是创建”
想要修改为 “总是不”
设置页点选修改后设置不会被保存，刷新设置页仍显示为 “总是创建”
导出配置文件，修改key "dontCreateWorkFolder"，再导入配置，也没用，修改-导入后再导出，发现key值被重置为0了

**截图**
![image](https://github.com/user-attachments/assets/3b087be7-bf19-429d-8fbd-119cf41d0697)

**浏览器以及版本（请填写以下信息）：**
Chrome 版本 128.0.6613.120（正式版本） （64 位）
插件版本：PixivToolkit Next v6.4.1

**Comment by leoding86** [comment]
已复现问题，会尽快修复。
