### ISSUE TITLE
只有一张图时获取不到pageNum？

### ISSUE THREAD

**Issue by liangjiancang** [leoding86/webextension-pixiv-toolkit#29]
RT，像 `{id}_{pageNum}_{title}` 这样的设置获取回来会变成 `534545454_名字名字`（只有一个下划线），`{id}_p{pageNum}_{title}` 则会变成 `534545454_p_名字名字`，非常诡异。
多P的图则没有任何问题。

**Comment by leoding86** [comment]
如果插曲里面只有一张图片，那么就会自动过滤掉页码参数，目前的逻辑是这样的。

**Comment by leoding86** [comment]
可以通过打开“保留页码”设置来保留页码
