### ISSUE TITLE
Firefox addon store

### ISSUE THREAD

**Issue by Mar2ck** [leoding86/webextension-pixiv-toolkit#3]
It would be helpful to publish this onto the firefox's addon website so firefox users dont have to compile the extension

**Comment by leoding86** [comment]
I've already submited this to Firefox addons. Waiting to be reviewed.

**Comment by leoding86** [comment]
You can download the addon in Firefox addons now. [https://addons.mozilla.org/en-US/firefox/addon/pixiv-toolkit/](https://addons.mozilla.org/en-US/firefox/addon/pixiv-toolkit/)

Please close the issue if you do not have further requests.
