### ISSUE TITLE
Ugoira option "Generate and download" does not work

### ISSUE THREAD

**Issue by autumn-lovelace** [leoding86/webextension-pixiv-toolkit#31]
Fairly straight forward, turning this option on and leave settings - this does not take effect, and returning to the settings you find it was turned off. This happens even after reloading the extension, or reinstalling it.
This issue is specifically that the option visually indicates it is 'off' when checking settings.

Downloads start automatically after it finishes converting ugoira to webm.

![image](https://user-images.githubusercontent.com/38334602/74628695-85d86000-5113-11ea-8cf8-e1ee25ec246a.png)

System info is:
**Pixiv Toolkit Version:** 3.7.3-20012112
**Pixiv Omina Version:** 0.4.1
**Operating System:** Windows 10 Home x64
**Browser:** Chrome Version 80.0.3987.106 (Official Build) (64-bit)

**Comment by leoding86** [comment]
Issue confirmed. I'll fix it later.
