### ISSUE TITLE
'Extension takes over downloads' seems to have no effect

### ISSUE THREAD

**Issue by autumn-lovelace** [leoding86/webextension-pixiv-toolkit#32]
The extension doesn't seem to handle downloading on it's own - I still get asked where I want to save a file.
Steps:
I turned this feature on.
I was asked to give permissions, and I granted them.
Initiating a webm download, I am still asked where to save the file (which is what happens normally before I tried enabling this option)

[screenshot of settings](https://i.imgur.com/NXTc8NO.png)

System info is:
**Pixiv Toolkit Version:** 3.7.3-20012112
**Pixiv Omina Version:** 0.4.1
**Operating System:** Windows 10 Home x64
**Browser:** Chrome Version 80.0.3987.106 (Official Build) (64-bit)

**Comment by leoding86** [comment]
If your the browser download setting "Ask where to save each file before downloading" is on, the extension download settings will have no effect.
