### ISSUE TITLE
(Suggestion) Easyer to customization illustration name

### ISSUE THREAD

**Issue by itsmenmd** [leoding86/webextension-pixiv-toolkit#33]
Hi i have some problem and suggestion :))

_1._ I want to save image like this format: _`{author} - {title} ({id}) .jpg`_  but saving like this _`{author} - {title} ({id}.jpg`_
_2._ Keep page number
Keep page number even if the illustration only has one image- I think that better start a one instead of zero
_3._ Pack and download, check again with problem 1 because have the same format.I want change name like that _`{author} - {title} ({id}) {ページ} ページ.jpg`_(ページ: that mean page ) that auto change name to _`{author} - {title} ({id}) .jpg`_ if the illustration only has one image, if not count from 1
_4._ Add option save directly or download as zip (over 2 image)

**Comment by leoding86** [comment]
Could you export the settings and parse here? You can export the settings on the bottom of the setting page.

I don't quite understand the 4th suggestion. Could you describe it more clearly?

**Comment by itsmenmd** [comment]
4. i mean that always zip download if that

 dont have only 1 image. If i download much like this. i have to extract and move file to my origin folder every time. i think that can save time with a new button :D

Here is my recent setting i'm using

`
{"autoActivateDownloadPanel":true,"downloadRelativeLocation":"relate/","downloadSaveAs":false,"enableExtTakeOverDownloads":true,"enableExtend":true,"enableExtension":true,"enablePackUgoiraFramesInfo":true,"enablePtkSearch":true,"enableSaveVisitHistory":true,"enableWhenUnderSeconds":3,"extendDuration":3,"featureKnown":false,"guideShowed":true,"illustrationDownloadIfReady":true,"illustrationImageRenameFormat":"{author} - {title} ({id})","illustrationKeepPageNumber":false,"illustrationRenameFormat":"{author} - {title} ({id})","mangaImageRenameFormat":"{author} - {title} ({id})","mangaPackAndDownload":false,"mangaPagesInChunk":500,"mangaRenameFormat":"{author} - {title} ({id})","notSaveNSFWWorkInHistory":false,"novelIncludeDescription":false,"novelRenameFormat":"{author} - {title} ({id})","statIllustDownloaded":145,"statMangaDownloaded":0,"statNovelDownloaded":0,"statUgoiraDownloaded":89,"subscribedUsers":{},"ugoiraDisplayDownloadProgress":true,"ugoiraGenerateAndDownload":true,"ugoiraQuanlity":1,"ugoiraRenameFormat":"{author} - {title} ({id})","version":"3.8.1","visitHistoryType":"list"}
`

**Comment by leoding86** [comment]
The ability of the browser extension is limited, especially the download and filesystem. If the browser setting "Ask where to save each file before downloading" is on, the save dialog will definitely show and the extension can't do anything for it. So for the 4th suggestion, I can't do anything.

Now for the 5th suggestion, the extension can't read filesystem to read filename for checking the work has been downloaded. But I can save the download information to the browser then use the information to check if the work has been downloaded. But there is a downside which is the extension will not update the download information if you delete the work from you machine. That will cause problems.

I think you can give the Pixiv Omina a try.

**Comment by itsmenmd** [comment]
Im try Pixiv Omina, It's good but, i dont want to copy and paste to download. On my 5th suggestion, u can check PixivDownloader extension for what im want to tell you. But that extensions now having bug on my country.

**Comment by leoding86** [comment]
I read through the code that PixivDownloader EX uses to check download information. The logic is easy and not suit this extension very well.

I'll think a better way to approach the feature.

**Comment by itsmenmd** [comment]
cant wait to see in new version, i dont know  about JS code XD

**Comment by leoding86** [comment]
All done. Please update to the latest version.
