### ISSUE TITLE
希望能设置个压缩开关。

### ISSUE THREAD

**Issue by 199548zyc** [leoding86/webextension-pixiv-toolkit#35]
很多画师喜欢发多图，结果被打包了，估计被识别为漫画了，希望设置个开关。

**Comment by leoding86** [comment]
插件在下载多图时是会将图片打包生成下载链接在进行下载。由于插件功能的限制，不能很好做到将图片连续的一张一张下载，如果浏览器下载设置开启了“下载文件前询问保存位置”就会导致弹出多个保存对话框并且无法避免。

你可以尝试用下Pixiv Omina，这个是一个独立下载程序，目前还在开发初期，不过基本功能已经比较稳定可用了。
