### ISSUE TITLE
Unable to download while logged into Pixiv.

### ISSUE THREAD

**Issue by MangoNation** [leoding86/webextension-pixiv-toolkit#36]
Tested this in both Chrome and Firefox so far with the same results & behavior. (Updated both Chrome and Firefox to see if that had any effect but it did not) 

Specifically with individual images or multiple. Ugoira looks like it downloads properly.

Chrome: 80.0.3987.116  (also happened on previous version)
Firefox: 73.0.1 (64-bit) (also happened on previous version)

Currently having an issue where there looks like a recent update happened on Pixiv with a side-header, and it going through a tutorial of sorts.

![left button](https://user-images.githubusercontent.com/61295492/74980219-12c63680-53fe-11ea-8eda-76668d10387c.png)

The sidebar that shows up when you click on the button:
![sidebar](https://user-images.githubusercontent.com/61295492/74980237-1954ae00-53fe-11ea-8d98-057d26f90af8.png)

From what I can tell, the extension is unable to properly download any pictures, but when logged out, the extension works.

**Comment by leoding86** [comment]
I cannot reproduce the problem. Could you reload the extension or restart the browser and try again? I don't use Firefox often and the extension's Firefox version is not the latest version.

**Comment by MangoNation** [comment]
I have reloaded, reinstalled and restarted the browsers but it did not work.

However when i registered with a new account, the extension is working, but has null in front of the names.

If i have just {id} in the name in settings, the files download as null{id}.

**Comment by leoding86** [comment]
Which work need to access the domain techorus-cdn.com? Could you paste the url here? And Could you paste your extension settings here too? You can export the settings at the bottom of the options page.

**Comment by TestPolygon** [comment]
> Access to XMLHttpRequest at 'https://tc-pximg01.techorus-cdn.com/img-original/img/2020/02/21/05/28/43/79624742_p0.png' ...

> Which work need to access the domain techorus-cdn.com?

> https://tc-pximg01.techorus-cdn.com/img-original/img/2020/02/21/05/28/43/79624742_p0.png
> 79624742_p0.png
> 79624742

https://www.pixiv.net/en/artworks/79624742

**Comment by leoding86** [comment]
@TestPolygon I did not find this work accessed this domain. But I'll add a setting for the extension to grant the extension access to this domain manually.

**Comment by killmysafe** [comment]
Have a same problem (On chrome), unable to download while logged in but able while logged out.
Happen after i decided to change pixiv name for no reason, dont know if related but the error as follow:

Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
Context
popup_page/index.html
Stack Trace

**Comment by leoding86** [comment]
@killmysafe The latest version I submit to Chrome is still pending review. I don't know how long time it will take. You can download the latest version [here](https://github.com/leoding86/webextension-pixiv-toolkit/releases) and install it manually.

**Comment by killmysafe** [comment]
@leoding86 i download the lastest version and installed it, still the same problem, the errors as follow:

db.type() is deprecated and will be removed in a future version of PouchDB
Context
https://www.pixiv.net/en/artworks/79546859
Stack Trace
lib/pouchdb.js:589 (guardedConsole)
lib/pouchdb.js:765 (isRemote)
lib/pouchdb.js:15430 (anonymous function)
lib/pouchdb.js:277 (anonymous function)
lib/pouchdb.js:264 (anonymous function)
lib/pouchdb.js:930 (anonymous function)
content_scripts/app.js:1 (value)
content_scripts/app.js:1 (t)
content_scripts/app.js:1 (value)
content_scripts/app.js:1 (t)
content_scripts/app.js:1 (value)
content_scripts/app.js:1 (value)
content_scripts/app.js:1 (initDownloadButtons)
content_scripts/app.js:1 (mounted)
lib/vue.min.js:6 (He)
lib/vue.min.js:6 (Yt)
lib/vue.min.js:6 (insert)
lib/vue.min.js:6 (k)
lib/vue.min.js:6 (anonymous function)
lib/vue.min.js:6 (e._update)
lib/vue.min.js:6 (r)
lib/vue.min.js:6 (fn.get)
lib/vue.min.js:6 (fn.run)
lib/vue.min.js:6 (un)
lib/vue.min.js:6 (anonymous function)
lib/vue.min.js:6 (qe)

--------------------
the line is highlighted yellow:

589     console[method].apply(console, args);

**Comment by MangoNation** [comment]
@leoding86 I just wanted to let you know the new version v3.9.1 works now after it prompts to grant that permission. Thank you again for working on this and adjusting it!

**Comment by leoding86** [comment]
You are welcome.
