### ISSUE TITLE
点击下载没有反应了

### ISSUE THREAD

**Issue by hyominli** [leoding86/webextension-pixiv-toolkit#37]
还有那个配套的软件也是打不开pixiv登录界面

**Comment by leoding86** [comment]
你可以在没有代理的情况下访问P站吗？如果不能需要设置代理。

**Comment by hyominli** [comment]
> 你可以在没有代理的情况下访问P站吗？如果不能需要设置代理。

我需要挂vpn才能访问P站

**Comment by leoding86** [comment]
不好意思这么晚才回复。如果你需要使用VPN访问，那么也需要在Pixiv Omina中设置代理。

**Comment by hyominli** [comment]
好的谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "leoding86"<notifications@github.com&gt;; 
发送时间: 2020年2月29日(星期六) 中午11:58
收件人: "leoding86/webextension-pixiv-toolkit"<webextension-pixiv-toolkit@noreply.github.com&gt;; 
抄送: "李文盛"<1500259680@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [leoding86/webextension-pixiv-toolkit] 点击下载没有反应了 (#37)




不好意思这么晚才回复。如果你需要使用VPN访问，那么也需要在Pixiv Omina中设置代理。
