### ISSUE TITLE
No download (images, manga, gifs), greetings.

### ISSUE THREAD

**Issue by EliasM27** [leoding86/webextension-pixiv-toolkit#38]
Hello friend, I wanted to inform you that since the last update the extension does not work (do not download), we hope you can solve the problem.
pstd: I wanted to ask you if in the following updates you could add the option (time of the photo in which it was uploaded to Pixiv), greetings.

**Comment by leoding86** [comment]
I want to know if you can't download all works or some works.

The extension has 'year', 'month', 'day' meta for renaming works. I think these are what you want.

**Comment by ian-coog** [comment]
3.9.0 has problems for me too, 3.8.2 works, sorry for repeating, I think it's the same issue in this report
https://github.com/leoding86/webextension-pixiv-toolkit/issues/39

**Comment by EliasM27** [comment]
I have 3 accounts and in 2 it works but in the third one it doesn't download I don't know what happens there, and regarding the issue of the date I was referring to the fact that it is currently written automated, for example, on February 25, 2020 and not on February 25, 2020 9:54 PM, greetings.

**Comment by leoding86** [comment]
Please update to 3.9.1.
