### ISSUE TITLE
下载按钮的功能问题

### ISSUE THREAD

**Issue by shinefine** [leoding86/webextension-pixiv-toolkit#40]
2020/2/27

下载文件功能仍然不正常，点击按钮后，有下载进度，进度100% 后，显示 “已下载”，同时按钮变绿，但是实际上浏览器并没有回馈文件保存到硬盘的信息提示。

插件版本 3.9  ，pixiv 账户已登录，grant the extension to access  techorus-cdn.com 的权限也有打开。

**Comment by leoding86** [comment]
请升级至3.9.1，3.9.0版本在赋予访问权限上有BUG。

**Comment by shinefine** [comment]
升级到3.9.1 问题仍然如故，  之前降级到了3.8.x 功能就是正常的

**Comment by leoding86** [comment]
我复现不了你说的问题。是否能将浏览器调试工具的信息截图？
