### ISSUE TITLE
Can't download ugoira

### ISSUE THREAD

**Issue by Tamren** [leoding86/webextension-pixiv-toolkit#43]
As soon as I open the control panel at the bottom of the screen the button says "Downloading 1%" for a split second and then goes back to "Interrupted, Click to Retry". Clicking the button just results in the same thing after a moment. I haven't tried to use this feature in a while but it worked fine a week/month ago. I'm using version 3.9.0, this is the latest that Firefox will provide.

**Comment by Tamren** [comment]
I just realized something, normally when I go to save an animation it first gives me a choice of options like GIF or APNG. But now when I open the download panel it only displays a message that the download was interrupted (but I didn't tell it to download anything yet) and the Pixiv Omnia button.

**Comment by leoding86** [comment]
If the addon can't download necessary resource then it will display "Interrupted, Click to Retry". There is a bug about grant the addon to access a cdn which been used by Pixiv recently. I'll fix the bug in the next version. If you are using Chrome or Chrome-like browser, you can try the latest version which is 3.9.1.

**Comment by leoding86** [comment]
I submitted the version 3.10.1 to Firefox Addon. Please update it after it's available and try again.

**Comment by Tamren** [comment]
I'm still having the same issue. I updated to 3.10.1 and gave it a new permission to access the cdn. But the download panel for animations still says Interrupted.

I thought the problem might be something to do with adblock so as a test I made a brand new firefox profile with the pixiv addon and nothing else. The result was the same, it immediately says Interrupted.
