### ISSUE TITLE
Can't download any picture with firefox

### ISSUE THREAD

**Issue by sleektako** [leoding86/webextension-pixiv-toolkit#44]
If I turn on extension takes over downloads I can't seem to download anything.

**Comment by leoding86** [comment]
It's weird. When I tested it using development package, all is good. I'll investigate it later.

**Comment by leoding86** [comment]
I submitted the version 3.10.1 to Firefox addon. Please update it after it's available and try again.

**Comment by sleektako** [comment]
Thanks for the fix, appreciated.
