### ISSUE TITLE
Still can't download ugoira or images after 3.10.1 update

### ISSUE THREAD

**Issue by Tamren** [leoding86/webextension-pixiv-toolkit#45]
I updated the addon and gave it the required permission to access the CDN. I then tried to download Ugoira again. It still doesn't work, the button says it was interrupted. I also can't download images properly either, the zip file will contain blank or corrupted images that can't be displayed, each one is 146 bytes in size. Sometimes the first couple of images in the set will download properly, but the rest will be 146 bytes.

I'm using firefox 73.0.1 64-bit.

**Comment by leoding86** [comment]
It's weird. Everything is fine to me. Maybe your network is not very well.
![](https://github.com/leoding86/image-storage/blob/master/web-pixiv-toolkit-issue%2345-00.gif?raw=true)

**Comment by DivineAsura** [comment]
I am having the same problems as Tamren. Single images can be downloaded without a problem, but something goes wrong for multiple image works and ugoira. I'm also on Firefox 73.0.1 64 bit. Everything works properly in Chrome.

Here's something I noticed when going through the page load process with pausing on exceptions on. This exception does not occur when the extension is disabled:

![firefoxerror](https://user-images.githubusercontent.com/54805371/75966913-e986bb00-5e7f-11ea-8d79-2b3905bd148d.png)

**Comment by leoding86** [comment]
I don't think it caused the problem. But I plan to remove the pouchdb from the content_scripts. And may I kwon which other addons you used at the same time?

**Comment by DivineAsura** [comment]
The other addons I have installed are DuckDuckGo Privacy Essentials, NoScript, and uBlock Origin. I disabled all of them and tried again, still the same.

One other error to report: I saw the below exception in app.js after clicking retry. The debugger shows that the variable t is undefined if I mouse over it.

![firefoxerror2](https://user-images.githubusercontent.com/54805371/76045957-69aa3080-5f13-11ea-9620-8ba5dd32edf4.png)

**Comment by Tamren** [comment]
I also use NoScript and uBlock Origin. I tried making a fresh profile in firefox without any addons at all except for pixiv toolkit and that didn't help, so it doesn't seem like the other addons are to blame. It's very odd that firefox works for you and not for us, if we are all using the same software maybe something on the server end is refusing the connection?

**Comment by DivineAsura** [comment]
I tried to download another image, didn't work. I then peeked at the console and found output as in the below image (the link in the image leads to https://developer.mozilla.org/en-US/docs/Tools/Debugger/Source_map_errors ).

![image](https://user-images.githubusercontent.com/54805371/76817858-40b25700-67c1-11ea-9568-66878b4e7892.png)

So I googled around a bit for this error and found a string of links starting with https://github.com/github/fetch/issues/310 and ending with https://www.reddit.com/r/firefox/comments/5yhwob/fetch_api_not_working_in_firefox_addon/

Perhaps this is caused by Firefox needing permission for localhost in the manifest or such?

**Comment by DivineAsura** [comment]
The plugin started working on my end. I was able to download a gif just now. The APNG is generating as I'm typing this.

I honestly am at a loss as to why it works now, but I'm not complaining. Now if only Mozilla would fix the webm generation support.

**Comment by Tamren** [comment]
Can confirm for ugoira, it just works now though I have no idea why. Instead of getting interrupted the menu says "parsing information" then displays the download options as normal.

I tested the image download and that also works fine, no more corrupted images.
