### ISSUE TITLE
techorus-cdn.com  ?

### ISSUE THREAD

**Issue by goldfish123415** [leoding86/webextension-pixiv-toolkit#46]
![new](https://user-images.githubusercontent.com/61824758/75965532-e7664000-5f03-11ea-8162-9f071f1d8962.JPG)

讀取變更techorus-cdn.com的資料是什麼意思？我不敢更新

**Comment by leoding86** [comment]
有的用户发现了Pixiv的部分资源放在了这个的cdn上。

**Comment by goldfish123415** [comment]
Thanks!
我有在patreon支持你(雖然是每月1美金)
你做的Pixiv Toolkit很棒！感謝你的付出！

**Comment by leoding86** [comment]
感谢你的支持！
