### ISSUE TITLE
绘画图片保存时重命名总会在末尾多出一个“0”

### ISSUE THREAD

**Issue by RadiationZ** [leoding86/webextension-pixiv-toolkit#47]
尝试了各种重命名方式，但不管怎样在保存时文件名末尾都会莫名其妙加上一个“0”
也没有打开“保留页码”按钮，就很奇怪这个0是什么东西
如果重命名为“not set”保存图片时就会只有一个0，所以这个“0”是为了防止空名称的占位吗？
但是我都重命名了它还在就很烦
希望大佬能给我一些指点！谢谢！

**Comment by leoding86** [comment]
能提供出问题的作品链接以及你的设置吗？你可以在设置的最下方导出插件的设置。

**Comment by RadiationZ** [comment]
您好，我尝试了不同作家的作品下载，都存在这个问题
我的设置文件已附于附件
下图为尝试了不同重命名格式后的下载情况
[cid:7BEF6F0E-C83F-4798-BD16-FE9FC26B161E@mailmaster]
在2020年3月16日 21:24，leoding86<notifications@github.com><mailto:notifications@github.com> 写道：

能提供出问题的作品链接以及你的设置吗？你可以在设置的最下方导出插件的设置。

**Comment by RadiationZ** [comment]
V4.0.0版本更新后依然存在此问题，是只有我有这个问题吗？是设置的相关问题吗？

**Comment by RadiationZ** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        您好，我之前反馈的那个下载文件会在文件名后加“0”是什么原因呢？
        之前有给您回复截图和设置文件
    
        
            
        
    
    
        
        

        
    

    在2020年3月16日 22:00，rmbenzemaz<rmbenzemaz@hotmail.com> 写道： 




    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    您好，我尝试了不同作家的作品下载，都存在这个问题
        我的设置文件已附于附件下图为尝试了不同重命名格式后的下载情况
    
        
            
        
    
    
        
        

        
    

    在2020年3月16日 21:24，leoding86<notifications@github.com> 写道： 




能提供出问题的作品链接以及你的设置吗？你可以在设置的最下方导出插件的设置。

**Comment by leoding86** [comment]
不好意思这么晚才回复，不知道你是否还在使用此扩展。你是通过邮件回复的吗？放在邮件中的附件在issue中是看不到的，需要在回复issue中添加附件。不过我还是没能复现你说的问题。

**Comment by RadiationZ** [comment]
你好，问题仍然存在
当重命名绘画图片为“{author}_{title}”时，保存的图片文件名末尾会自动加一个“0”
但我经过试验后将重命名绘画图片规则改为了“{author}_{title}#{pageNum}#”，此时保存图片文件名就正常了。

在issue中添加附件好像不能添加json文件，显示不支持的文件类型。

**Comment by leoding86** [comment]
这个是预期的结果，不过没有修改设置项的说明可能造成了一定的困惑，下个版本我会修改下设置项说明。

暂时先关闭了。
