### ISSUE TITLE
Can't download ugoiras and images seem iffy

### ISSUE THREAD

**Issue by Fsugoi** [leoding86/webextension-pixiv-toolkit#48]
I only noticed it today, and I noticed a similar post from a couple of weeks ago, but I am unable to download any ugoiras. Images seem to download fine but when trying to open them, my computer simply can't. When attempting to download an ugoira, the bubble will download to 1%, stop, and then  say "Interrupted. Click to retry.". Rinse and repeat indefinitely. If there is something wrong on my end, I'd like to try and fix it, but if it's something that multiple people are having, it could potentially be something that warrants more attention. Thanks for your help :)

**Comment by leoding86** [comment]
If you saw the "Interrupted. Click to retry" after you saw the "1%", it might be network issues. Could you screenshot the red lines in the browser's console?

Maybe I should add a diagnostic feature🤔
