### ISSUE TITLE
无法下载GIF

### ISSUE THREAD

**Issue by mikumiku5** [leoding86/webextension-pixiv-toolkit#49]
总是显示网络错误，但是网络情况良好，不知道为什么
![截屏2020-03-19上午11 11 46](https://user-images.githubusercontent.com/60222018/77028263-441d2c80-69d3-11ea-84fe-1661fcac241b.png)

**Comment by leoding86** [comment]
这个可能是下载权限没有正确赋予给插件所导致的问题。你可以看下扩展详情里面是否有下载权限。
