### ISSUE TITLE
浏览历史消失了

### ISSUE THREAD

**Issue by Sabermoon** [leoding86/webextension-pixiv-toolkit#50]
插件版本3.10，今天需要看浏览历史的时候发现历史被清空了，如果是出现bug导致新历史未记录还好理解，但现状是全部的历史都不存在了。
![Snipaste_2020-03-25_17-51-21](https://user-images.githubusercontent.com/20150947/77524055-ae493c00-6ec1-11ea-835f-916972ee5c8d.png)

**Comment by leoding86** [comment]
更新并没有执行清空浏览记录的操作。是在升级以后出现的问题还是突然出现的？有没有可能是使用了清空隐私数据功能的扩展或相关设置？

**Comment by Sabermoon** [comment]
差不多从插件增加cdn网址开始没看过历史记录了，以为不会出问题，今天需要时才发现。没有清空隐私数据功能插件，使用过浏览器的清理但也是很早的事了。

**Comment by leoding86** [comment]
你是否会用浏览器的调试模式，可以复制下一段代码到插件的浏览记录页面，看下是否有结果。
```javascrtip
(() => {
    let db = new PouchDB('illust_histories', { revs_limit: 1 });
    db.allDocs().then(result => console.log(result)).catch(error => console.error(error));
})();
```
例如：
![](https://raw.githubusercontent.com/leoding86/image-storage/master/webext-pixiv-toolkit-issue%2350.jpg.png)

**Comment by Sabermoon** [comment]
{total_rows: 1, offset: 0, rows: Array(1)}
total_rows: 1
offset: 0
rows: [{…}]
__proto__: Object

**Comment by leoding86** [comment]
那就是浏览记录被删除了。可能的原因有很多：
* 手动删除过插件
* 在插件中清空过浏览记录
* 浏览记录功能没有开启
* 由于硬件空间不足引起的浏览器自动回收
* 重装过浏览器

目前肯定是没有办法还原了。

**Comment by Sabermoon** [comment]
浏览器会自动回收，这是保存在缓存里的？能不能提供个自动或者快捷导出记录的方案，手动的话还是很麻烦。

**Comment by leoding86** [comment]
因为目前是将浏览数据存储在indexedDB中，每个浏览器根据所在的磁盘空间有相应的策略，当容量大于一定比例以后会清空一些存储的内容。

用扩展的方式肯定没法用自动导出的方案。倒是可以将数据简化存储一份到扩展的存储空间，可以在一些情况下恢复部分数据然后通过网络再完整数据。不过由于扩展的专用空间比较小，所以存储量也是个问题。需要仔细考虑下🤔

**Comment by Sabermoon** [comment]
想到了，不过在扩展的小窗加一个导出按钮应该是做得到的，能解决一点问题。

**Comment by leoding86** [comment]
不好意思这么晚才回复。添加了一个回复历史记录的功能，不过似乎有用户碰到了性能问题，这个还在关注中。问题暂时先关闭了。
