### ISSUE TITLE
有些小说不能弹出下载框，有些就可以

### ISSUE THREAD

**Issue by qweadfe** [leoding86/webextension-pixiv-toolkit#51]
之前是都可以下载的，最近有些下载不了，而且之前下载过的也不弹出下载框了

**Comment by leoding86** [comment]
能否提供不能下载的小说的地址？

**Comment by qweadfe** [comment]
> 能否提供不能下载的小说的地址？

https://www.pixiv.net/novel/show.php?id=12600136
也不止这篇，我是用的chrome浏览器无法下载，但是换成edge就可以下载

**Comment by leoding86** [comment]
可能是兼容性的问题，我抽时间看一看。

**Comment by leoding86** [comment]
问题已经定位了，是`fromCharCode`方法在Chrome中抛出了RangeError异常。同样的内核出现不一样的结果也是非常奇怪🤔
