### ISSUE TITLE
合成大型gif/apng网页崩溃

### ISSUE THREAD

**Issue by MoeShadows** [leoding86/webextension-pixiv-toolkit#52]
开始合成后占用超2g内存,然后网页崩溃了,pixiv omina可以正常保存,插件里的webm格式也可以正常保存

**Comment by leoding86** [comment]
可以提供下作品链接吗？另外这个没有太好的办法，因为插件需要将待下载的内容用blob方式暂存到浏览器，所以避不开如果文件过大导致的内容占用问题。

**Comment by MoeShadows** [comment]
id: 79521374

**Comment by leoding86** [comment]
我这边没有什么问题。可能还是机器内存不足导致的。还有两种可能：
* 就是有较多没有关闭的待下载页面。因为生成好的blob对象不会在下载后自动销毁（因为某些原因需要重新下载），如果有很多没有关闭的页面，将会吃掉非常多的内容。
* 同时进行生成任务，也会消耗大量的内存。

**Comment by MoeShadows** [comment]
电脑还剩6g内存,我是特意到电脑上面来保存gif

**Comment by leoding86** [comment]
不好意思这么晚才回复，不知是否还在使用此插件？还有类似的问题吗？

**Comment by MoeShadows** [comment]
换电脑了,具体没试过...

**Comment by MoeShadows** [comment]
现在已经换电脑了,以后再试一下

**Comment by leoding86** [comment]
好的，那我先关闭了。
