### ISSUE TITLE
小说无法下载epub

### ISSUE THREAD

**Issue by qweadfe** [leoding86/webextension-pixiv-toolkit#53]
epub格式无法下载，只能下载txt。也是chrome不行，edge正常

**Comment by leoding86** [comment]
能否提供不能下载的作品链接，以及使用的插件版本？

**Comment by qweadfe** [comment]
> 能否提供不能下载的作品链接，以及使用的插件版本？

id=12530102  v4.0.1

**Comment by leoding86** [comment]
我在Chrome和Edge上测试可以下载epub，没有复现错误。
