### ISSUE TITLE
Removed from AMO

### ISSUE THREAD

**Issue by nuenuewei** [leoding86/webextension-pixiv-toolkit#57]
Mozilla continues to prove that they cannot be relied on to host addons for their own browser.
The firefox version needs to be hosted somewhere else.

**Comment by Dragoon91786** [comment]
Is it possible to host the already built file for Firefox here based upon the most recent build file?

I'm having difficulty with my python and it keeps giving syntax errors (otherwise, I wouldn't ask).

Anyhow, many thanks!

**Comment by Dragoon91786** [comment]
Also, did Mozilla indicate how the program violated their ToS?

**Comment by leoding86** [comment]
I got the email from AMO. They need me to provide sources of third-party libs that are used in the addon. But I forget it because I was busy at that moment.

**Comment by leoding86** [comment]
Republished. Close.
