### ISSUE TITLE
关于动图的ZIP档里面的animation.json問題

### ISSUE THREAD

**Issue by ee092884** [leoding86/webextension-pixiv-toolkit#59]
在这作品里面用GIF下载的图片速度跟网页版上的速度是一样的
但使用ZIP下载后去看 速度却被加快了...@_@
用另一个扩充下载下来的ZIP档却是跟网页一样是正常的
想请问是哪里有出问题吗? 看两边的json都不一样
Pixiv Toolkit 4.1.0-2020052622下载ZIP呈现速度(经过处理有些残像请忽略)：
![bandicam 2020-06-18 11-16-56-055 00_00_00-00_00_30](https://user-images.githubusercontent.com/39590282/84974511-0658ad00-b156-11ea-850d-7239e789efd5.gif)

Px Downloader 3.4.4下载ZIP呈现速度(经过处理有些残像请忽略)：
![bandicam 2020-06-18 11-17-30-955_1](https://user-images.githubusercontent.com/39590282/84974676-50da2980-b156-11ea-8dc9-0be20821f878.gif)

作品(这作者的动图只要这作者的动图只要下载Pixiv Toolkit下载好像都会加速)：https://www.pixiv.net/artworks/82248179

另一个扩充下载：https://chrome.google.com/webstore/detail/px-downloader/bcbibglkpaimhgmoomembjhclhipoack

**Comment by leoding86** [comment]
已经定位到问题了，确实会有1毫秒的差别，会在下一个版本修复。另外问一下，你是使用的什么软件查看zip文件的？

**Comment by ee092884** [comment]
> 已經定位到問題了，確實會有1毫秒的差異，會在下一個版本修復。另外問一下，你是使用的什麼軟件查看zip文件的？

有QQ或者是Telegram嗎??
比較好溝通~

**Comment by leoding86** [comment]
zip所包含的帧数据文件和生成gif所需的帧数据是一致的。因为我没有直接播放过zip文件，所以可能是所用的播放器对于帧数据的格式要求不同导致的问题。

然后我下载了你说的扩展插件，但是在页面上看不到相关的下载按钮，所以不知道生产的帧数据有何不同。

**Comment by leoding86** [comment]
我看了下源码，应该就是软件或库对于帧数据格式不兼容导致的问题。

**Comment by ee092884** [comment]
> zip所包含的帧数据文件和生成gif所需的帧数据是一致的。因为我没有直接播放过zip文件，所以可能是所用的播放器对于帧数据的格式要求不同导致的问题。
> 
> 然后我下载了你说的扩展插件，但是在页面上看不到相关的下载按钮，所以不知道生产的帧数据有何不同。
因為Px Downloader有一段時間沒有更新維護過了 
所以導致用夜間模式顏色會被同化要反白才看的到
要關閉夜間模式後才會直接顯示出來 如果還是看不到 
那就用方向鍵的左右切換圖片來刷新頁面後才會顯示出來
用F5重整頁面不會顯示
![image](https://user-images.githubusercontent.com/39590282/85272589-f40ca500-b4ae-11ea-9564-7c2416ecb560.png)
![image](https://user-images.githubusercontent.com/39590282/85272627-fec73a00-b4ae-11ea-9a7f-7613830c8758.png)

**Comment by leoding86** [comment]
按照你的方法下载了zip看了下，帧时间数据是一致的，只是animiation.json内的数据格式不一样，不应该会出现速度不一致的问题。
在zip文件添加animation.json文件是因为当时有的用户用了一个专门播放此类动画的播放器需要这个格式的文件才能播放。所以如果要解决这个问题需要知道你使用的播放器的名字（如果你用了的话），否则我不太能解决你碰到的问题。

**Comment by ee092884** [comment]
> 按照你的方法下载了zip看了下，帧时间数据是一致的，只是animiation.json内的数据格式不一样，不应该会出现速度不一致的问题。
> 在zip文件添加animation.json文件是因为当时有的用户用了一个专门播放此类动画的播放器需要这个格式的文件才能播放。所以如果要解决这个问题需要知道你使用的播放器的名字（如果你用了的话），否则我不太能解决你碰到的问题。

我用的是TiefSee
先隨意點開一張圖片後 就可以直接用切換去預覽ZIP檔
或者是用空白鍵直接對ZIP做預覽也可以
[TiefSee.zip](https://github.com/leoding86/webextension-pixiv-toolkit/files/4813667/TiefSee.zip)

**Comment by leoding86** [comment]
我看了下TiefSee的源码，确定是animiation.json内容不同导致的。这个我需要想想怎么实现比较好。

**Comment by leoding86** [comment]
@ee092884 我在版本4.2.0中更改了打包帧信息选项，你可以选择“类型2”解决你碰到的问题。目前Chrome Web Store有点问题不能发布更新包，待发布后你就可以更新了。

**Comment by ee092884** [comment]
> @ee092884我在版本4.2.0中更改了打包幀信息選項，你可以選擇“類型2”解決你碰到的問題。目前Chrome Web Store有點問題不能發布更新包，待發布後你就可以更新了。

好的~如果現在當下不能更新的話 可以在github先丟擴充的ZIP壓縮檔 我可以先自行更新~等chrome通過後我在用官網上的
