### ISSUE TITLE
P* button doesn't show up unless I use a new tab or refresh the page.

### ISSUE THREAD

**Issue by Tamren** [leoding86/webextension-pixiv-toolkit#6]
Great addon, thanks! However the problem I'm having is that the P* button doesn't always appear. If I click a direct link like this example it works fine:

https://www.pixiv.net/en/artworks/77093460

However if I use the right or left arrows to flip to the next image the P* no longer appears. Any image link I click on from inside the pixiv website does not display the P* either. The only way to get the P* button to appear reliably is to open links in a new tab or refresh the page.

I'm using v3.2 of the addon with Firefox 70.0.1 on windows 7.

**Comment by leoding86** [comment]
I forgot to submit version 3.2.1 to Firefox. I'll do it tomorrow. Sorry.

**Comment by leoding86** [comment]
@Tamren You can update to 3.2.1 now. The issue should be fixed.
