### ISSUE TITLE
能增加付费图片(自己购买的月费赞助)打包下载么！

### ISSUE THREAD

**Issue by GraphaX** [leoding86/webextension-pixiv-toolkit#63]
平常都是用来下载漫画，各种功能都含好用。最近赞助了几个大佬的月费图片，因为不想浪费一次性都想下载下来，但是插件好像不支持赞助图片的页面！

**Comment by leoding86** [comment]
@GraphaX  你所说的付费图片是否有样例？比如地址之类。

**Comment by GraphaX** [comment]
作品页面 [https://himitsu2.fanbox.cc/posts/1094240](url) 
赞助页面 [https://himitsu2.fanbox.cc/](url)
![image](https://user-images.githubusercontent.com/48665204/86003645-b1197700-ba44-11ea-991d-9ead94ac4b76.png)

**Comment by leoding86** [comment]
fanbox的啊，我并没有使用过fanbox，所以只能尝试一下看能不能实现，但是不能保证能实现。

**Comment by GraphaX** [comment]
非常感谢，不能实现也没关系，本体的功能已经很完美了

**Comment by leoding86** [comment]
发布了一个测试版本，可以打包下载部分文章内的图片，你可以在[这里](https://github.com/leoding86/webextension-pixiv-toolkit/releases/tag/4.3.0-beta)下载试一试。

我先关掉这个issue。

**Comment by leoding86** [comment]
@GraphaX 需要注意的是，下载fanbox内图片的相关设置是复用的“绘画”设置。

**Comment by GraphaX** [comment]
感谢大佬，已经用上了下载也没问题，只是在扩展列表里报了2个错误
![image](https://user-images.githubusercontent.com/48665204/86120034-2a2cd300-bb06-11ea-81e4-9aa68e34ca82.png)
![image](https://user-images.githubusercontent.com/48665204/86120067-3b75df80-bb06-11ea-808d-30246719182b.png)
我发出来看下对大大更新有没有帮助

**Comment by leoding86** [comment]
@GraphaX 这两个异常应该不会影响使用。计划明天更新到正式版上去。
