### ISSUE TITLE
Not saving after latest update

### ISSUE THREAD

**Issue by Xyrexus** [leoding86/webextension-pixiv-toolkit#64]
My extension isn't working properly anymore, I just tried to use it on a page, it says downloading and goes up to 100%, but then nothing happens, usually I have to click it again and then it asks me where to save the .zip.

I went into settings and gave it download permissions, and to ask me where to put the files, but it's still doing the same thing.

**Comment by leoding86** [comment]
I need more information to investigate it, something like which browser do you use, url example.

**Comment by Xyrexus** [comment]
Ah sorry, I'm using Firefox 77.0.1 and I was trying to grab these pictures https://www.pixiv.net/en/artworks/67073090 

The plugin still seems to work for single images, but not multiple.

**Comment by leoding86** [comment]
Thanks for the further information. I can reproduce the issue. I'll fix it soon.

**Comment by leoding86** [comment]
Fixed in version 4.2.1, please update it when the version is available.

**Comment by Xyrexus** [comment]
Thanks very much.
