### ISSUE TITLE
想請問ID命名問題

### ISSUE THREAD

**Issue by ee092884** [leoding86/webextension-pixiv-toolkit#67]
![image](https://user-images.githubusercontent.com/39590282/86546035-3a5d0c00-bf65-11ea-981c-49d540ce649f.png)
就是pixiv上用右鍵存圖片時圖片命名都是ID_p0然後再多頁模式下是ID_p0 ID_p1 ID_p2 ID_p3 這樣排下去
但這個重新命名好像沒有辦法設定ID'_p0'這塊的部分 
我是希望可以做到說像這樣子的
![image](https://user-images.githubusercontent.com/39590282/86546146-d38c2280-bf65-11ea-9656-89763cb786a0.png)
因為我平常在使用的批量下載格式是按照跟pixiv上面是一樣的
但因為他無法額外打包GIF的幀數所以要用toolkit來做下載
但下載後的壓縮檔都要在手動額外命名
希望可以更改成"82064644_p0 - ハイレグ♂ボーイ⛱横ハミチン3000馬力🐴のザーメンシャワー.zip"
這樣類似的格式ID_pN - 標題.副檔名 大概像這樣
然後希望可以在重命名漫畫的設定區那邊可以做個自定義後的預覽
可以把可以把Example那行改成預覽
不然每更改完一次就要再下載一次 看是不是想到的命名有點麻煩

**Comment by leoding86** [comment]
压缩包上的p0表示的是什么意思不是太明白，如果只是为了加一个p0字符串的话，可以直接在重命名格式中将p0添加到想要的位置。

关于漫画的命名，我下个版本加一个页码的占位符吧，应该可以实现你要的功能。

**Comment by ee092884** [comment]
> 压缩包上的p0表示的是什么意思不是太明白，如果只是为了加一个p0字符串的话，可以直接在重命名格式中将p0添加到想要的位置。
> 
> 关于漫画的命名，我下个版本加一个页码的占位符吧，应该可以实现你要的功能。

![image](https://user-images.githubusercontent.com/39590282/86548408-d3445500-bf6e-11ea-8595-f9051151a578.png)
壓縮檔上的p0沒有特別意思 只是因為想要跟圖片的命名一樣對齊格式而已
就是通常直接在pixiv上面直接另存圖片時
他的命名方式就是p0起頭
第一頁p0 第二頁p1以此類推
GIF的只有單張所以都是用p0就是只有一頁的意思

**Comment by leoding86** [comment]
对于动图那可以使用 {id}_p0-{title} 这样来重命名。对于漫画内图片可以使用 {id}_p{pageNum}-{title} 来重命名。

**Comment by ee092884** [comment]
> 对于动图那可以使用 {id}_p0-{title} 这样来重命名。对于漫画内图片可以使用 {id}_p{pageNum}-{title} 来重命名。

喔喔!!~~太感謝了~~目前GIF跟圖片命名都解決了^W^感謝你
