### ISSUE TITLE
Remove "lib/babel-polyfill.min.js" from manifest.json

### ISSUE THREAD

**Issue by TestPolygon** [leoding86/webextension-pixiv-toolkit#72]
Just remove this line:
https://github.com/leoding86/webextension-pixiv-toolkit/blob/3aaaa6ca68b8127513cc9013ca86cec238b46c50/src/statics/manifest.json#L67

---

There is no `babel-polyfill.min.js` in `lib/` after building. And it's impossible to install the extension until you remove this line.
Even the version from the Webstore has no such line. Do you remove it manually every time?

**Comment by leoding86** [comment]
I think I messed up some commits. I'll fix it.

**Comment by leoding86** [comment]
fixed
