### ISSUE TITLE
Add "@types/chrome" to "devDependencies"

### ISSUE THREAD

**Issue by TestPolygon** [leoding86/webextension-pixiv-toolkit#73]
Just add `"@types/chrome": "^0.0.122",` to package.json as "devDependencies".
It allows IDE  to assist you better.

**Comment by leoding86** [comment]
I tried it before, but the types have some compatibility issues. If I use typescript, I will implement my own chrome type, but it is unlikely that I will use typescript to refactor the extension in the near future. Thanks anyway.
