### ISSUE TITLE
Limit the height of "v-menu > v-list" in IllustHistory.vue

### ISSUE THREAD

**Issue by TestPolygon** [leoding86/webextension-pixiv-toolkit#75]
The menu of the selecting of history pages looks OK only if you have not a lot of the history records (correspondingly the pages).

But if you have a lot of history records – you have a lot of pages in "illust-history" page, and this menu becomes very inconvenient because of it has unormal high height. The height of this menu (list) can be over 10000px!

https://github.com/leoding86/webextension-pixiv-toolkit/blob/35b902ae7658152f4ab1b0e317fb45a7b33b1297/src/options_page/components/IllustHistory.vue#L97-L102
You can add `style="max-height: XXXpx;"` to `v-list` to limit its height and to add the scrollbar.

Or, for example, check this input:
```js
      <v-text-field
        type="number"
        style="width: 88px; display: inline-block;"
        title="Page №" color="#eee"
        :min="1" :step="1"
        :max="pages" v-model="page"
      ></v-text-field>
```

---
By the way:

Add `:disabled="page === 1"` to
https://github.com/leoding86/webextension-pixiv-toolkit/blob/35b902ae7658152f4ab1b0e317fb45a7b33b1297/src/options_page/components/IllustHistory.vue#L79-L82
and `:disabled="page === pages"` to
https://github.com/leoding86/webextension-pixiv-toolkit/blob/35b902ae7658152f4ab1b0e317fb45a7b33b1297/src/options_page/components/IllustHistory.vue#L83-L86

I think it would be much better than to show the alert box.

---
By the way 2:

You can fix the URL to the gif file in [readme.md](https://github.com/leoding86/webextension-pixiv-toolkit/blob/master/readme.md#how-to-use)
https://github.com/leoding86/webextension-pixiv-toolkit/raw/master/src/statics/remote/img/example.gif

**Comment by leoding86** [comment]
This page will be removed in future, but thanks anyway.

**Comment by TestPolygon** [comment]
As I say in https://github.com/leoding86/webextension-pixiv-toolkit/issues/74 this page is very useful because of this allows to check existence of deleted arts.

Ok, remove history page, **but add the similar page for download records.** 

I want to check which works, that I have downloaded before, was deleted. (If the image preview downloads well – the picture was not deleted, if 404 – it was deleted).
