### ISSUE TITLE
Toolkit won't register in fanbox

### ISSUE THREAD

**Issue by Vladimir1010** [leoding86/webextension-pixiv-toolkit#77]
It says on the latest release that it can download images from the fanbox but the toolkit isn't even registering anything I open

**Comment by leoding86** [comment]
You can only download the images that you can view in page from FANBOX.

**Comment by sakurairsora** [comment]
but where?I don't see any bottom in fanbox？

**Comment by leoding86** [comment]
I could reproduced the issue. I'll fix in the next version.
