### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by basic2004** [leoding86/webextension-pixiv-toolkit#8]
1. Rename illust image file
Currently, illust image file is saved to 0 page of manga image filename.
please add 'Rename illust' in manga section,
when this is blank following 0 page of manga image filename.

2. Saving unpacked manga image files.
I thought 'Pack and download' is choose zip or image files when first use.
but this feature works auto saving zip file when completed download.
please add choose zip or image files option in manga section.
if this option if turned off browser will save these files to download folder or show many save file dialogs.

Thanks very much.

**Comment by leoding86** [comment]
First feature could be done, I'll put it on the list.

Second feature cannot be easily done through browser extension. The browser extension is very limited feature of saving files. For this feature, first you need turn off the option "Ask where to save each file before downloading" in Chrome and turn off the same option in extension, or save file dialog will pop up when you download every each file. Even so, the browser download management will store download tasks of every image and it's will become ugly very soon if you download often. So there is a not good way to implement the feature. But I'll keep it in mind.

**Comment by leoding86** [comment]
A separate 'Illustration' settings has been added. I will not implement the second feature because I plan to develop a desktop version has the similar feature.

**Comment by Tvtossen** [comment]
I look forward to this desktop version, since this is a feature I also think would be great

**Comment by leoding86** [comment]
You can try [Pixiv Omina](https://github.com/leoding86/pixiv-omina).
