### ISSUE TITLE
Non-zip option for multi-image illustration

### ISSUE THREAD

**Issue by Chiiruno** [leoding86/webextension-pixiv-toolkit#82]
**Describe the bug**
There does not appear to be an option to disable zipping multi-image illustrations.

**Expected behavior**
I would like to be able to save both images, into a folder, without having to zip them.

**Example work from Pixiv**
https://www.pixiv.net/en/artworks/84329882

**Browser and Version (please complete the following information):**
Chromium (Chrome): 85.0.4183.102

**Settings of extension**
[pixiv_toolkit_settings-1600163580848.zip](https://github.com/leoding86/webextension-pixiv-toolkit/files/5224051/pixiv_toolkit_settings-1600163580848.zip)

**Comment by leoding86** [comment]
You can't save multiple images into a folder while using web extension because some technical reason. You could try Pixiv Omina if you are using Windows.
