### ISSUE TITLE
Do not include `historyBackup` in the export of the settings

### ISSUE THREAD

**Issue by TestPolygon** [leoding86/webextension-pixiv-toolkit#83]
**Do not include `historyBackup` in the export of the settings.**

I sure that it is the unexpected behavior for people.
If someone decides to share his settings, then he also will share his history too – that is a private information leak.

Also there is "Export visit history" button that does that people expect of it. So there is no need to include `historyBackup` in the export of the settings.

**Comment by leoding86** [comment]
Closed with this [commit](https://github.com/leoding86/webextension-pixiv-toolkit/commit/4cffab09a7002901ef214d0cb18ea959dc35768e)
