### ISSUE TITLE
Export/Import the download history

### ISSUE THREAD

**Issue by TestPolygon** [leoding86/webextension-pixiv-toolkit#84]
Add the buttons like there are for the **visit** history, but for the **download** history too.

I think that these buttons can be placed in one line:
Visit history [EXPORT][IMPORT]
Download history [EXPORT][IMPORT]

**Comment by leoding86** [comment]
Closed with this [commit](https://github.com/leoding86/webextension-pixiv-toolkit/commit/4cffab09a7002901ef214d0cb18ea959dc35768e)
