### ISSUE TITLE
Download in the backgroud script

### ISSUE THREAD

**Issue by TestPolygon** [leoding86/webextension-pixiv-toolkit#85]
Chrome planned to disable CORS/CORB bypassing for content scripts in the near future.

**Your extension will not work** with these changes. 

You can test it now by setting 
`chrome://flags/#cors-for-content-scripts` to "Enabled" and 
`chrome://flags/#force-empty-CORB-and-CORS-allowlist` to "Enabled".

Here is more info:
https://www.chromium.org/Home/chromium-security/extension-content-script-fetches

---
Downloading in the backgroud script **will also help to bypass the background tabs throttling** (currectrly the download speed is significantly lower in the background tabs).
It happens when you click "DL image" and you switch to other tab.

In additional **it will allow to close the tab without waiting until the content is downloaded.**

**Comment by TestPolygon** [comment]
It also help to bypass the background tabs throttling (currectrly in the background tabs the download speed is significantly lower).

It's useful when you click "DL illus" and you switch to other tab.

**Comment by leoding86** [comment]
Confirmed. I don't think it need to implement download logic in background. Just modify response headers will fix this issue. But It will take me some time to think how to just modify the response headers which requested by extension.
