### ISSUE TITLE
添加命名规则后会在文件名后面添加0

### ISSUE THREAD

**Issue by moxiaoweng** [leoding86/webextension-pixiv-toolkit#89]
**描述错误**
清楚简明地描述错误是什么。

添加命名规则后会在文件名后面添加0

**预期行为**
对你期望发生的事情的简洁明了的描述。

**示例作品**
如果可以，请提供发生错误的作品链接。

**截图**
如果可以，请添加屏幕截图以帮助解释你的问题。

![image](https://user-images.githubusercontent.com/50871408/99510187-b494a700-29c1-11eb-9f83-f9c829deb9e6.png)

**浏览器以及版本（请填写以下信息）：**
  -例如 Chrome，Edge，Firefox

**插件设置**
你可以在设置页面导出插件设置。

**其他内容**
其他可用的信息。

**Comment by aq82997289** [comment]
出现了同样的情况。

**Comment by leoding86** [comment]
这个0是页码，如果没有在重命名规则中添加页码参数，则会在文件名的最后自动加上页码。如果不想保留页码参数，可以这样设置命名规则`{id}_{title}#_{pageNum}#`，如果下载的作品只有一张图片，则会自动去除#号之间的部分。
