### ISSUE TITLE
PixivToolkit v3.3.2 doesn't save anymore some zipped illustrations

### ISSUE THREAD

**Issue by ian-coog** [leoding86/webextension-pixiv-toolkit#9]
Example pixiv page not working for me
https://www.pixiv.net/en/artworks/77638788
after downloading all the 5 images it should create a zip but devtools console show:

Uncaught (in promise) ReferenceError: vm is not defined
    at s.getFilename (app.js:1)
    at Object.onDone (app.js:1)
    at app.js:1

I've set all rename Illustration and Manga options as {id}_{pageNum}

This one works for me
https://www.pixiv.net/en/artworks/77625914
77625914_0-1.zip downloaded correctly.

I'm on Win7 32bit, using Vivaldi 2.9.1719.3

**Comment by leoding86** [comment]
Thanks for feedback. The issue can be reproduced. I'll investigate it when I have some time.

**Comment by leoding86** [comment]
Fixed in version 3.3.3.

**Comment by ian-coog** [comment]
thanks, works in 3.3.3
