### ISSUE TITLE
Fanbox Downloads

### ISSUE THREAD

**Issue by 501stRookie** [leoding86/webextension-pixiv-toolkit#91]
**Describe the bug**
When downloading a post off Pixiv Fanbox, the zip file that downloads contains html files rather than the image files. This happens regularly, though occasionally it will download the actual image files.

**Expected behavior**
When downloading images from Pixiv Fanbox, the downloaded zip file will contain the image files of the post.

I use Google Chrome.

[pixiv_toolkit_settings-1606166739438.zip](https://github.com/leoding86/webextension-pixiv-toolkit/files/5585888/pixiv_toolkit_settings-1606166739438.zip)

https://i.imgur.com/wpOnIBv.png
https://i.imgur.com/6Ts3il7.png

**Comment by leoding86** [comment]
I can't test the fanbox work 386260. But I tested the work 1442615 which is from the same user and the extension work fine.

https://imgur.com/a/4BZyRTO

**Comment by 501stRookie** [comment]
Some posts work fine but others don't.

**Comment by 501stRookie** [comment]
I tried looking at the console from the developer tools, and it looked like this:

https://i.imgur.com/tkac2Hj.png

**Comment by leoding86** [comment]
I think the request which is created by the extension miss cookies, but I don't know why. It'll take some times for figuring this out.

**Comment by leoding86** [comment]
I release version [4.7.1](https://github.com/leoding86/webextension-pixiv-toolkit/releases/tag/4.7.1). In my browser, the extension can send request with cookies included, but I'm not sure it will fix your problem. You can download it in the release page and install it in browser with extension developer mode enabled (You need unzip the zip first) and see if the version solved the problem you experienced.

If the release solved the issue, then I'll public it to Chrome extension store.

**Comment by 501stRookie** [comment]
It seems to be working now.
