### ISSUE TITLE
the tool isn't working

### ISSUE THREAD

**Issue by Alleucifen** [leoding86/webextension-pixiv-toolkit#92]
the bug only come today, the toolbar to download didn't exist anymore. i can't download anything. the icon is greyed out. i can't open the toolkit.

https://www.pixiv.net/en/artworks/85843879 i mean i can't download anything so..

Chrome Version 87.0.4280.66 (Official Build) (64-bit)

i can't even go to the setting

![image](https://user-images.githubusercontent.com/75054763/100303560-540ff600-2fcf-11eb-8f34-56f7eab343a4.png)

the toolbar didn't pop up

![image](https://user-images.githubusercontent.com/75054763/100304145-b1587700-2fd0-11eb-9ded-580f1146ea58.png)

the extension is on

![image](https://user-images.githubusercontent.com/75054763/100303794-faf49200-2fcf-11eb-9cc8-dd2d593df2b3.png)

i also tried to reinstall the tool, but this still happen.

**Comment by leoding86** [comment]
Works find in my Chrome. Which version do you use?
[https://imgur.com/a/WHC7oG7](https://imgur.com/a/WHC7oG7)

**Comment by Alleucifen** [comment]
i use the latest version from chrome web store, i wonder if it's clashing with other extension? is there known issues with other extension?

**Comment by leoding86** [comment]
> is there known issues with other extension?

So far no.

You could try this disable all extensions except this one and see if it works properly.

**Comment by leoding86** [comment]
Close for not responding.
