### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by liangjiancang** [leoding86/webextension-pixiv-toolkit#93]
点击 DL Image 没有反应
![QQ截图20201203172050](https://user-images.githubusercontent.com/42267675/100989700-16d9d400-358c-11eb-84d8-cf32e2981b99.jpg)

使用的是 Edge 浏览器的最新版：https://microsoftedge.microsoft.com/addons/detail/pixiv%E5%B7%A5%E5%85%B7%E7%AE%B1/kjbdcfnalffdkdbomnmcgjpjhkngijkc

**Comment by leoding86** [comment]
微软商店的版本很长时间没有更新了，可以去chrome商店下载或者等我去微软商店发布。

**Comment by leoding86** [comment]
新版本已经提交了，审核中。等待审核完成应该就可以自动更新到最新版。
