### ISSUE TITLE
Downloading Infinity%

### ISSUE THREAD

**Issue by TestPolygon** [leoding86/webextension-pixiv-toolkit#94]
_**Sometime**_, usually when downloading is slow, the downloading progress is not showed. But it shows "Downloading Infinity%".
![Screenshot](https://user-images.githubusercontent.com/38364068/102926806-bbbe4180-44a6-11eb-8c2a-0a03c62120d5.png)

**Comment by Rich-Richie** [comment]
I have a few profiles of firefox. One profile have this problem while another profile doesn't have this problem

**Comment by leoding86** [comment]
Closed.

I think it is a old problem in old version. If you encounter similar problem, feel free to open a new issue.

**Comment by TestPolygon** [comment]
It still exists, usually it happens when I switch to an other tab and return back.

**Comment by leoding86** [comment]
I still can't reproduce the issue. Tested in Chrome 94 and Firefox 90.
