### ISSUE TITLE
downloaded file will be opened automatically is not desired behavior

### ISSUE THREAD

**Issue by dyf19118** [leoding86/webextension-pixiv-toolkit#97]
It's a feature request.
Everytime i download the gif and after downloading, the macos built-in app 'previewer' will be opened and showing the frames of the downloaded gif file.
It's quite useless from my point of view.
 
OS version: mac bigsur 11.2
Chrome version:  88.0.4324.146
Plugin version: 4.7.1

**Comment by dyf19118** [comment]
another feature request: provide an option whether to pack illustration images even when count larger than 1.
want to spread files into selected folder instead of creating a zip file.

**Comment by leoding86** [comment]
The preview shouldn't pop up after download is complete. I cannot reproduce the issue in your first comment on my windows 10. I don't have a mac so I can't test on macos.

Because so technical limitation, the feature you wanted can't be done in webextension.
